use super::*;

impl<H: UiHost> Default for UiTree<H> {
    fn default() -> Self {
        Self {
            nodes: SlotMap::with_key(),
            layers: SlotMap::with_key(),
            layer_order: Vec::new(),
            root_to_layer: HashMap::new(),
            base_layer: None,
            focus: None,
            captured: HashMap::new(),
            active_touch_drag_target: HashMap::new(),
            last_pointer_move_hit: HashMap::new(),
            touch_pointer_down_outside_candidates: HashMap::new(),
            hit_test_path_cache: None,
            hit_test_bounds_trees: bounds_tree::HitTestBoundsTrees::default(),
            last_internal_drag_target: None,
            window: None,
            ime_allowed: false,
            ime_composing: false,
            suppress_text_input_until_key_up: None,
            pending_shortcut: PendingShortcut::default(),
            replaying_pending_shortcut: false,
            alt_menu_bar_arm_key: None,
            alt_menu_bar_canceled: false,
            observed_in_layout: ObservationIndex::default(),
            observed_in_paint: ObservationIndex::default(),
            observed_globals_in_layout: GlobalObservationIndex::default(),
            observed_globals_in_paint: GlobalObservationIndex::default(),
            measure_stack: Vec::new(),
            measure_cache_this_frame: HashMap::new(),
            frame_arena: FrameArenaScratch::default(),
            paint_pass: 0,
            scratch_pending_invalidations: HashMap::new(),
            scratch_node_stack: Vec::new(),
            scratch_element_nodes: Vec::new(),
            scratch_bounds_records: Vec::new(),
            scratch_visual_bounds_records: Vec::new(),
            measure_reentrancy_diagnostics: MeasureReentrancyDiagnostics::default(),
            layout_engine: crate::layout_engine::TaffyLayoutEngine::default(),
            layout_invalidations_count: 0,
            last_layout_frame_id: None,
            last_layout_bounds: None,
            last_layout_scale_factor: None,
            interactive_resize_active: false,
            interactive_resize_needs_full_rebuild: false,
            interactive_resize_stable_frames: 0,
            interactive_resize_last_updated_frame: None,
            interactive_resize_last_bounds_delta: None,
            viewport_roots: Vec::new(),
            pending_barrier_relayouts: Vec::new(),
            pending_declarative_window_snapshot_roots: HashSet::new(),
            pending_post_layout_window_runtime_snapshot_refine: false,
            #[cfg(debug_assertions)]
            debug_last_declarative_render_root_frame_id: None,
            debug_enabled: false,
            debug_stats: UiDebugFrameStats::default(),
            debug_view_cache_roots: Vec::new(),
            debug_view_cache_contained_relayout_roots: Vec::new(),
            debug_paint_cache_replays: HashMap::new(),
            debug_paint_widget_exclusive_started: None,
            debug_layout_engine_solves: Vec::new(),
            debug_layout_hotspots: Vec::new(),
            debug_layout_inclusive_hotspots: Vec::new(),
            debug_layout_stack: Vec::new(),
            debug_widget_measure_hotspots: Vec::new(),
            debug_widget_measure_stack: Vec::new(),
            debug_paint_widget_hotspots: Vec::new(),
            debug_paint_text_prepare_hotspots: Vec::new(),
            debug_paint_stack: Vec::new(),
            debug_measure_children: HashMap::new(),
            debug_invalidation_walks: Vec::new(),
            debug_model_change_hotspots: Vec::new(),
            debug_model_change_unobserved: Vec::new(),
            debug_global_change_hotspots: Vec::new(),
            debug_global_change_unobserved: Vec::new(),
            debug_hover_edge_this_frame: false,
            debug_hover_declarative_invalidations: HashMap::new(),
            debug_dirty_views: Vec::new(),
            #[cfg(feature = "diagnostics")]
            debug_notify_requests: Vec::new(),
            debug_virtual_list_windows: Vec::new(),
            debug_virtual_list_window_shift_samples: Vec::new(),
            debug_retained_virtual_list_reconciles: Vec::new(),
            debug_scroll_handle_changes: Vec::new(),
            debug_scroll_nodes: Vec::new(),
            debug_scrollbars: Vec::new(),
            debug_prepaint_actions: Vec::new(),
            #[cfg(feature = "diagnostics")]
            debug_set_children_writes: HashMap::new(),
            #[cfg(feature = "diagnostics")]
            debug_parent_sever_writes: HashMap::new(),
            #[cfg(feature = "diagnostics")]
            debug_layer_visible_writes: Vec::new(),
            #[cfg(feature = "diagnostics")]
            debug_overlay_policy_decisions: Vec::new(),
            #[cfg(feature = "diagnostics")]
            debug_remove_subtree_frame_context: HashMap::new(),
            #[cfg(feature = "diagnostics")]
            debug_removed_subtrees: Vec::new(),
            #[cfg(feature = "diagnostics")]
            debug_reachable_from_layer_roots: None,
            #[cfg(feature = "diagnostics")]
            debug_dispatch_snapshot: None,
            #[cfg(feature = "diagnostics")]
            debug_text_constraints_measured: HashMap::new(),
            #[cfg(feature = "diagnostics")]
            debug_text_constraints_prepared: HashMap::new(),
            view_cache_enabled: false,
            paint_cache_policy: PaintCachePolicy::Auto,
            inspection_active: false,
            paint_cache: PaintCacheState::default(),
            interaction_cache: prepaint::InteractionCacheState::default(),
            dirty_cache_roots: HashSet::new(),
            dirty_cache_root_reasons: HashMap::new(),
            last_redraw_request_tick: None,
            propagation_depth_generation: 0,
            propagation_depth_cache: SecondaryMap::new(),
            propagation_chain: Vec::new(),
            propagation_entries: Vec::new(),
            invalidation_dedup: InvalidationDedupTable::default(),
            invalidated_layout_nodes: 0,
            invalidated_paint_nodes: 0,
            invalidated_hit_test_nodes: 0,
            semantics: None,
            semantics_requested: false,
            layout_node_profile: None,
            measure_node_profile: None,
            deferred_cleanup: Vec::new(),
        }
    }
}

impl<H: UiHost> UiTree<H> {
    pub fn new() -> Self {
        Self::default()
    }
}
