use crate::GeneratePackError;
use crate::contracts::{
    DependencySpec, GeneratePackRequest, PresentationDefaults, PresentationRenderMode,
    SemanticAlias,
};
use crate::fs::crate_module_name;
use crate::naming::{normalize_const_name, normalize_module_name};
use crate::svg_dir::CollectedSvg;

pub(crate) fn render_cargo_toml(request: &GeneratePackRequest, has_aliases: bool) -> String {
    let dependency_lines = dependency_lines(&request.dependency_spec);
    let feature_lines = if has_aliases {
        r#"default = ["semantic-ui"]
semantic-ui = []
app-integration = ["dep:fret-app", "dep:fret-core"]"#
    } else {
        r#"default = []
app-integration = ["dep:fret-app", "dep:fret-core"]"#
    };

    format!(
        r#"[package]
name = "{package_name}"
version = "0.1.0"
edition = "2024"
description = "Generated {vendor_namespace} icon pack for Fret (embedded SVGs + optional app registry wiring)."

[features]
{feature_lines}

[dependencies]
{dependency_lines}

[workspace]
"#,
        package_name = request.package_name,
        vendor_namespace = request.vendor_namespace,
        feature_lines = feature_lines,
        dependency_lines = dependency_lines,
    )
}

pub(crate) fn render_icon_list(request: &GeneratePackRequest, icons: &[CollectedSvg]) -> String {
    let mut lines = vec![
        format!(
            "# Generated by {}. Do not edit manually.",
            request.generator_label
        ),
        format!("# Source: {}", source_label(request)),
        String::new(),
    ];
    lines.extend(icons.iter().map(|icon| format!("{}.svg", icon.icon_name)));
    format!("{}\n", lines.join("\n"))
}

pub(crate) fn render_generated_ids(
    request: &GeneratePackRequest,
    icons: &[CollectedSvg],
) -> String {
    let module_name = normalize_module_name(&request.vendor_namespace);
    let mut lines = vec![
        format!("// @generated by {}. DO NOT EDIT.", request.generator_label),
        format!(
            "//! Generated vendor icon constants for {}.",
            request.vendor_namespace
        ),
        String::new(),
        "use fret_icons::IconId;".to_string(),
        String::new(),
        format!("pub mod {module_name} {{"),
        "    use super::IconId;".to_string(),
        String::new(),
    ];

    for icon in icons {
        let const_name = normalize_const_name(&icon.icon_name);
        lines.push(format!(
            "    pub const {const_name}: IconId = IconId::new_static(\"{vendor}.{icon_name}\");",
            vendor = request.vendor_namespace,
            icon_name = icon.icon_name,
        ));
    }

    lines.push("}".to_string());
    lines.push(String::new());
    lines.join("\n")
}

pub(crate) fn render_lib_rs(request: &GeneratePackRequest, icons: &[CollectedSvg]) -> String {
    let has_aliases = !request.semantic_aliases.is_empty();
    let registration_lines = render_registration_lines(icons);
    let alias_pack_const = if has_aliases {
        r#"
#[cfg(feature = "semantic-ui")]
pub const UI_SEMANTIC_ALIAS_PACK: IconPackRegistration =
    IconPackRegistration::new(PACK_METADATA, register_ui_semantic_aliases);
"#
        .to_string()
    } else {
        String::new()
    };

    let alias_register_call = if has_aliases {
        r#"
    #[cfg(feature = "semantic-ui")]
    register_ui_semantic_aliases(reg);"#
            .to_string()
    } else {
        String::new()
    };

    let alias_public_fn = if has_aliases {
        r#"
/// Register semantic `ui.*` aliases for this icon pack.
#[cfg(feature = "semantic-ui")]
pub fn register_ui_semantic_aliases(reg: &mut IconRegistry) {
    semantic_ui::register(reg);
}
"#
        .to_string()
    } else {
        String::new()
    };

    let alias_module = if has_aliases {
        format!(
            r#"
#[cfg(feature = "semantic-ui")]
mod semantic_ui {{
    use super::*;

    pub fn register(reg: &mut IconRegistry) {{
{alias_lines}
    }}
}}
"#,
            alias_lines = render_alias_lines(&request.vendor_namespace, &request.semantic_aliases)
        )
    } else {
        String::new()
    };

    format!(
        r#"//! A generated {vendor_namespace} SVG icon pack for Fret.
//!
//! This crate registers vendored SVG icons into [`fret_icons::IconRegistry`].

use fret_icons::{{
    IconId, IconPackImportModel, IconPackMetadata, IconPackRegistration, IconPresentation,
    IconRegistry, IconRenderMode,
}};
use rust_embed::RustEmbed;
use std::{{borrow::Cow, sync::Arc}};

pub mod generated_ids;

pub const PACK_METADATA: IconPackMetadata = IconPackMetadata {{
    pack_id: "{pack_id}",
    vendor_namespace: "{vendor_namespace}",
    import_model: IconPackImportModel::Generated,
}};

pub const VENDOR_PACK: IconPackRegistration =
    IconPackRegistration::new(PACK_METADATA, register_vendor_icons);
{alias_pack_const}
pub const PACK: IconPackRegistration = IconPackRegistration::new(PACK_METADATA, register_icons);

#[derive(RustEmbed)]
#[folder = "assets"]
#[include = "icons/*.svg"]
struct Assets;

pub fn register_icons(reg: &mut IconRegistry) {{
    register_vendor_icons(reg);{alias_register_call}
}}

/// Register vendor icon IDs (`{vendor_namespace}.*`) into an [`IconRegistry`].
pub fn register_vendor_icons(reg: &mut IconRegistry) {{
    register_generated_list(reg);
}}
{alias_public_fn}
#[cfg(feature = "app-integration")]
pub mod advanced;
#[cfg(feature = "app-integration")]
pub mod app;

fn register_generated_list(reg: &mut IconRegistry) {{
{registration_lines}
}}

fn register_vendor_icon(reg: &mut IconRegistry, icon_name: &str, render_mode: IconRenderMode) {{
    let path = format!("icons/{{icon_name}}.svg");
    let Some(file) = Assets::get(&path) else {{
        return;
    }};

    let bytes: Arc<[u8]> = match file.data {{
        Cow::Borrowed(bytes) => Arc::from(bytes),
        Cow::Owned(bytes) => Arc::from(bytes),
    }};

    let _ = reg.register_svg_bytes_with_presentation(
        IconId::new(format!("{vendor_namespace}.{{icon_name}}")),
        bytes,
        IconPresentation {{ render_mode }},
    );
}}
{alias_module}"#,
        pack_id = request.pack_id,
        vendor_namespace = request.vendor_namespace,
        registration_lines = registration_lines.trim_end(),
        alias_pack_const = alias_pack_const.trim_end(),
        alias_register_call = alias_register_call,
        alias_public_fn = alias_public_fn.trim_end(),
        alias_module = alias_module.trim_end(),
    )
}

pub(crate) fn render_app_rs(crate_module_name: &str) -> String {
    format!(
        r#"use fret_icons::{{
    IconRegistry, InstalledIconPacks, panic_on_icon_pack_metadata_conflict,
    panic_on_icon_registry_freeze_failure,
}};

/// Install this icon pack into a `fret-app` application.
///
/// This registers the pack's icons into the global `IconRegistry`.
pub fn install(app: &mut fret_app::App) {{
    app.with_global_mut(IconRegistry::default, |icons, app| {{
        crate::PACK.register_into_registry(icons);
        let frozen = icons.freeze().unwrap_or_else(|errors| {{
            panic_on_icon_registry_freeze_failure(
                "{crate_module_name}.app.install",
                Some(crate::PACK_METADATA.pack_id),
                errors,
            )
        }});
        app.set_global(frozen);
    }});
    app.with_global_mut(InstalledIconPacks::default, |installed, _app| {{
        installed.record(crate::PACK_METADATA).unwrap_or_else(|err| {{
            panic_on_icon_pack_metadata_conflict("{crate_module_name}.app.install", err)
        }});
    }});
}}
"#
    )
}

pub(crate) fn render_advanced_rs() -> &'static str {
    r#"use fret_core::UiServices;

/// Install this icon pack at the UI services boundary.
///
/// Icon packs are data-only; UI services are not required. This signature exists to fit the
/// ecosystem installer shape used by `fret-bootstrap`.
pub fn install_with_ui_services(app: &mut fret_app::App, _services: &mut dyn UiServices) {
    let _ = _services;
    crate::app::install(app);
}
"#
}

pub(crate) fn render_readme_md(request: &GeneratePackRequest, icons: &[CollectedSvg]) -> String {
    let module_name = crate_module_name(&request.package_name);
    let semantic_ids = if request.semantic_aliases.is_empty() {
        "- No semantic aliases were configured for this generated pack.\n".to_string()
    } else {
        request
            .semantic_aliases
            .iter()
            .map(|alias| {
                format!(
                    "- `{}` -> `{}.{}`",
                    alias.semantic_id, request.vendor_namespace, alias.target_icon
                )
            })
            .collect::<Vec<_>>()
            .join("\n")
            + "\n"
    };
    let presentation_defaults = render_presentation_defaults_readme(
        &request.presentation_defaults,
        icons,
        &request.vendor_namespace,
    );

    format!(
        r#"This crate provides a generated {vendor_namespace} SVG icon pack embedded via `rust-embed`.

## Integration surface

- `register_vendor_icons(...)` / `register_icons(...)` are the low-level registry hooks.
- `PACK_METADATA` / `PACK` keep the pack's provenance and default registration shape explicit.
- Enable `app-integration` when you want explicit installer surfaces under
  `{module_name}::app::install(...)` and
  `{module_name}::advanced::install_with_ui_services(...)`.
- `pack-provenance.json` records the imported source inventory, alias policy, and presentation
  defaults used to generate this pack crate.

## Source provenance

- Source kind: `{source_kind}`
- Source label: `{source_label}`
- Imported icons: `{icon_count}`
- Import model: `Generated`

## Pack metadata

- `PACK_METADATA.pack_id`: `{pack_id}`
- `PACK_METADATA.vendor_namespace`: `{vendor_namespace}`
- `PACK_METADATA.import_model`: `Generated`

## Vendor IDs

This crate registers `{vendor_namespace}.<icon-name>` for every SVG listed in `icon-list.txt`.

Generated vendor constants are exposed under `generated_ids::{module_name_generated}::*`.

## Semantic IDs

{semantic_ids}

## Presentation defaults

{presentation_defaults}

## App integration examples

- `FretApp::setup({module_name}::app::install)`
- `BootstrapBuilder::register_icon_pack_contract({module_name}::PACK)`
"#,
        vendor_namespace = request.vendor_namespace,
        module_name = module_name,
        source_kind = source_kind(request),
        source_label = source_label(request),
        icon_count = icons.len(),
        pack_id = request.pack_id,
        module_name_generated = normalize_module_name(&request.vendor_namespace),
        semantic_ids = semantic_ids.trim_end(),
        presentation_defaults = presentation_defaults.trim_end(),
    )
}

pub(crate) fn render_provenance_json(
    request: &GeneratePackRequest,
    icons: &[CollectedSvg],
) -> Result<String, GeneratePackError> {
    let document = ProvenanceDocument {
        generator: GeneratorMetadata {
            tool: request.generator_label.clone(),
        },
        pack: PackMetadata {
            package_name: request.package_name.clone(),
            pack_id: request.pack_id.clone(),
            vendor_namespace: request.vendor_namespace.clone(),
            import_model: "Generated".to_string(),
        },
        source: SourceMetadata {
            kind: source_kind(request).to_string(),
            label: source_label(request),
        },
        semantic_aliases: request.semantic_aliases.clone(),
        presentation_defaults: request.presentation_defaults.clone(),
        icons: icons
            .iter()
            .map(|icon| ProvenanceIcon {
                icon_name: icon.icon_name.clone(),
                source_relative_path: icon.source_relative_path.clone(),
                render_mode: icon.render_mode,
            })
            .collect(),
    };

    let mut rendered = serde_json::to_string_pretty(&document)?;
    rendered.push('\n');
    Ok(rendered)
}

fn render_alias_lines(vendor_namespace: &str, aliases: &[SemanticAlias]) -> String {
    aliases
        .iter()
        .map(|alias| {
            format!(
                "        let _ = reg.alias_if_missing(\n            IconId::new_static(\"{semantic_id}\"),\n            IconId::new_static(\"{vendor_namespace}.{target_icon}\"),\n        );",
                semantic_id = alias.semantic_id,
                vendor_namespace = vendor_namespace,
                target_icon = alias.target_icon,
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_registration_lines(icons: &[CollectedSvg]) -> String {
    icons
        .iter()
        .map(|icon| {
            format!(
                "    register_vendor_icon(reg, \"{icon_name}\", IconRenderMode::{render_mode});",
                icon_name = icon.icon_name,
                render_mode = render_mode_ident(icon.render_mode),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn render_presentation_defaults_readme(
    defaults: &PresentationDefaults,
    icons: &[CollectedSvg],
    vendor_namespace: &str,
) -> String {
    let default_render_mode = defaults
        .default_render_mode
        .unwrap_or(PresentationRenderMode::Mask);
    let mut lines = vec![format!(
        "- Pack default render mode: `{}`",
        render_mode_code(default_render_mode)
    )];

    if defaults.icon_overrides.is_empty() {
        lines.push("- Per-icon overrides: none".to_string());
    } else {
        lines.push("- Per-icon overrides:".to_string());
        lines.extend(defaults.icon_overrides.iter().map(|override_entry| {
            format!(
                "  - `{}.{}` -> `{}`",
                vendor_namespace,
                override_entry.icon_name,
                render_mode_code(override_entry.render_mode)
            )
        }));
    }

    let authored_icons = icons
        .iter()
        .filter(|icon| icon.render_mode == PresentationRenderMode::OriginalColors)
        .map(|icon| format!("`{}.{}`", vendor_namespace, icon.icon_name))
        .collect::<Vec<_>>();
    if authored_icons.is_empty() {
        lines.push("- Generated authored-color registrations: none".to_string());
    } else {
        lines.push(format!(
            "- Generated authored-color registrations: {}",
            authored_icons.join(", ")
        ));
    }

    lines.join("\n")
}

fn render_mode_ident(render_mode: PresentationRenderMode) -> &'static str {
    match render_mode {
        PresentationRenderMode::Mask => "Mask",
        PresentationRenderMode::OriginalColors => "OriginalColors",
    }
}

fn render_mode_code(render_mode: PresentationRenderMode) -> &'static str {
    match render_mode {
        PresentationRenderMode::Mask => "mask",
        PresentationRenderMode::OriginalColors => "original-colors",
    }
}

fn source_label(request: &GeneratePackRequest) -> String {
    match &request.source {
        crate::contracts::SourceSpec::SvgDirectory(source) => source.label.clone(),
        crate::contracts::SourceSpec::IconifyCollection(source) => source.label.clone(),
    }
}

fn source_kind(request: &GeneratePackRequest) -> &'static str {
    match &request.source {
        crate::contracts::SourceSpec::SvgDirectory(_) => "svg-directory",
        crate::contracts::SourceSpec::IconifyCollection(_) => "iconify-collection",
    }
}

fn dependency_lines(spec: &DependencySpec) -> String {
    match spec {
        DependencySpec::Published {
            fret_version,
            rust_embed_version,
        } => format!(
            r#"fret-icons = {{ version = "{fret_version}" }}
fret-app = {{ version = "{fret_version}", optional = true }}
fret-core = {{ version = "{fret_version}", optional = true }}
rust-embed = {{ version = "{rust_embed_version}", features = ["include-exclude"] }}"#
        ),
        DependencySpec::WorkspacePath {
            workspace_prefix,
            rust_embed_version,
        } => {
            let fret_icons_path = join_workspace_path(workspace_prefix, "ecosystem/fret-icons");
            let fret_app_path = join_workspace_path(workspace_prefix, "crates/fret-app");
            let fret_core_path = join_workspace_path(workspace_prefix, "crates/fret-core");
            format!(
                r#"fret-icons = {{ path = "{fret_icons_path}" }}
fret-app = {{ path = "{fret_app_path}", optional = true }}
fret-core = {{ path = "{fret_core_path}", optional = true }}
rust-embed = {{ version = "{rust_embed_version}", features = ["include-exclude"] }}"#
            )
        }
    }
}

fn join_workspace_path(workspace_prefix: &str, subpath: &str) -> String {
    if workspace_prefix == "." {
        subpath.to_string()
    } else {
        format!("{workspace_prefix}/{subpath}")
    }
}

#[derive(Debug, serde::Serialize)]
struct ProvenanceDocument {
    generator: GeneratorMetadata,
    pack: PackMetadata,
    source: SourceMetadata,
    semantic_aliases: Vec<SemanticAlias>,
    presentation_defaults: PresentationDefaults,
    icons: Vec<ProvenanceIcon>,
}

#[derive(Debug, serde::Serialize)]
struct GeneratorMetadata {
    tool: String,
}

#[derive(Debug, serde::Serialize)]
struct PackMetadata {
    package_name: String,
    pack_id: String,
    vendor_namespace: String,
    import_model: String,
}

#[derive(Debug, serde::Serialize)]
struct SourceMetadata {
    kind: String,
    label: String,
}

#[derive(Debug, serde::Serialize)]
struct ProvenanceIcon {
    icon_name: String,
    source_relative_path: String,
    render_mode: PresentationRenderMode,
}
