#[cfg(not(target_arch = "wasm32"))]
pub mod alloc_profile;

pub(crate) mod hotpatch;

pub mod area_demo;
pub mod bars_demo;
pub mod candlestick_demo;
pub mod components_gallery;
#[cfg(not(target_arch = "wasm32"))]
pub mod docking_arbitration_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod docking_demo;
pub mod drag_demo;
pub mod error_bars_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod first_frame_smoke_demo;
pub mod grouped_bars_demo;
pub mod heatmap_demo;
pub mod histogram_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod image_upload_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod ime_smoke_demo;
pub mod inf_lines_demo;
pub mod linked_cursor_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod markdown_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod plot3d_demo;
pub mod plot_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod plot_stress_demo;
pub mod shaded_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod sonner_demo;
pub mod stacked_bars_demo;
pub mod stairs_demo;
pub mod stems_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod table_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod table_stress_demo;
pub mod tags_demo;
#[cfg(not(target_arch = "wasm32"))]
pub mod virtual_list_stress_demo;
