use super::*;

#[allow(clippy::too_many_arguments)]
pub(crate) fn push_perf_json_row(
    rows: &mut Vec<serde_json::Value>,
    script_key: &str,
    sort: BundleStatsSort,
    top_total: impl serde::Serialize,
    top_layout: impl serde::Serialize,
    top_solve: impl serde::Serialize,
    top_solves: impl serde::Serialize,
    top_prepaint: impl serde::Serialize,
    top_paint: impl serde::Serialize,
    top_dispatch: impl serde::Serialize,
    top_hit_test: impl serde::Serialize,
    top_dispatch_events: impl serde::Serialize,
    top_hit_test_queries: impl serde::Serialize,
    pointer_move_frames_present: impl serde::Serialize,
    pointer_move_frames_considered: impl serde::Serialize,
    pointer_move_max_dispatch_time_us: impl serde::Serialize,
    pointer_move_max_hit_test_time_us: impl serde::Serialize,
    pointer_move_snapshots_with_global_changes: impl serde::Serialize,
    top_hit_test_bounds_tree_queries: impl serde::Serialize,
    top_hit_test_bounds_tree_disabled: impl serde::Serialize,
    top_hit_test_bounds_tree_misses: impl serde::Serialize,
    top_hit_test_bounds_tree_hits: impl serde::Serialize,
    top_hit_test_bounds_tree_candidate_rejected: impl serde::Serialize,
    top_frame_arena_capacity_estimate_bytes: impl serde::Serialize,
    top_frame_arena_grow_events: impl serde::Serialize,
    top_element_children_vec_pool_reuses: impl serde::Serialize,
    top_element_children_vec_pool_misses: impl serde::Serialize,
    top_tick: impl serde::Serialize,
    top_frame: impl serde::Serialize,
    top_view_cache_contained_relayouts: impl serde::Serialize,
    top_view_cache_roots_total: impl serde::Serialize,
    top_view_cache_roots_reused: impl serde::Serialize,
    top_view_cache_roots_first_mount: impl serde::Serialize,
    top_view_cache_roots_node_recreated: impl serde::Serialize,
    top_view_cache_roots_cache_key_mismatch: impl serde::Serialize,
    top_view_cache_roots_not_marked_reuse_root: impl serde::Serialize,
    top_view_cache_roots_needs_rerender: impl serde::Serialize,
    top_view_cache_roots_layout_invalidated: impl serde::Serialize,
    top_view_cache_roots_manual: impl serde::Serialize,
    top_cache_roots_contained_relayout: impl serde::Serialize,
    top_set_children_barrier_writes: impl serde::Serialize,
    top_barrier_relayouts_scheduled: impl serde::Serialize,
    top_barrier_relayouts_performed: impl serde::Serialize,
    top_virtual_list_visible_range_checks: impl serde::Serialize,
    top_virtual_list_visible_range_refreshes: impl serde::Serialize,
    top_renderer_tick_id: impl serde::Serialize,
    top_renderer_frame_id: impl serde::Serialize,
    top_renderer_encode_scene_us: impl serde::Serialize,
    top_renderer_prepare_text_us: impl serde::Serialize,
    top_renderer_prepare_svg_us: impl serde::Serialize,
    top_renderer_draw_calls: impl serde::Serialize,
    top_renderer_pipeline_switches: impl serde::Serialize,
    top_renderer_bind_group_switches: impl serde::Serialize,
    top_renderer_scissor_sets: impl serde::Serialize,
    top_renderer_scene_encoding_cache_misses: impl serde::Serialize,
    top_renderer_material_quad_ops: impl serde::Serialize,
    top_renderer_material_sampled_quad_ops: impl serde::Serialize,
    top_renderer_material_distinct: impl serde::Serialize,
    top_renderer_material_unknown_ids: impl serde::Serialize,
    top_renderer_material_degraded_due_to_budget: impl serde::Serialize,
    top_renderer_text_atlas_upload_bytes: impl serde::Serialize,
    top_renderer_text_atlas_evicted_pages: impl serde::Serialize,
    top_renderer_svg_upload_bytes: impl serde::Serialize,
    top_renderer_image_upload_bytes: impl serde::Serialize,
    top_renderer_svg_raster_cache_misses: impl serde::Serialize,
    top_renderer_svg_raster_budget_evictions: impl serde::Serialize,
    top_renderer_svg_raster_budget_bytes: impl serde::Serialize,
    top_renderer_svg_rasters_live: impl serde::Serialize,
    top_renderer_svg_standalone_bytes_live: impl serde::Serialize,
    top_renderer_svg_mask_atlas_pages_live: impl serde::Serialize,
    top_renderer_svg_mask_atlas_bytes_live: impl serde::Serialize,
    top_renderer_svg_mask_atlas_used_px: impl serde::Serialize,
    top_renderer_svg_mask_atlas_capacity_px: impl serde::Serialize,
    top_renderer_svg_raster_cache_hits: impl serde::Serialize,
    top_renderer_svg_mask_atlas_page_evictions: impl serde::Serialize,
    top_renderer_svg_mask_atlas_entries_evicted: impl serde::Serialize,
    top_renderer_intermediate_budget_bytes: impl serde::Serialize,
    top_renderer_intermediate_in_use_bytes: impl serde::Serialize,
    top_renderer_intermediate_peak_in_use_bytes: impl serde::Serialize,
    top_renderer_intermediate_release_targets: impl serde::Serialize,
    top_renderer_intermediate_pool_allocations: impl serde::Serialize,
    top_renderer_intermediate_pool_reuses: impl serde::Serialize,
    top_renderer_intermediate_pool_releases: impl serde::Serialize,
    top_renderer_intermediate_pool_evictions: impl serde::Serialize,
    top_renderer_intermediate_pool_free_bytes: impl serde::Serialize,
    top_renderer_intermediate_pool_free_textures: impl serde::Serialize,
    bundle_path: &Path,
) {
    rows.push(serde_json::json!({
        "script": script_key.to_string(),
        "sort": sort.as_str(),
        "top_total_time_us": top_total,
        "top_layout_time_us": top_layout,
        "top_layout_engine_solve_time_us": top_solve,
        "top_layout_engine_solves": top_solves,
        "top_prepaint_time_us": top_prepaint,
        "top_paint_time_us": top_paint,
        "top_dispatch_time_us": top_dispatch,
        "top_hit_test_time_us": top_hit_test,
        "top_dispatch_events": top_dispatch_events,
        "top_hit_test_queries": top_hit_test_queries,
        "pointer_move_frames_present": pointer_move_frames_present,
        "pointer_move_frames_considered": pointer_move_frames_considered,
        "pointer_move_max_dispatch_time_us": pointer_move_max_dispatch_time_us,
        "pointer_move_max_hit_test_time_us": pointer_move_max_hit_test_time_us,
        "pointer_move_snapshots_with_global_changes": pointer_move_snapshots_with_global_changes,
        "top_hit_test_bounds_tree_queries": top_hit_test_bounds_tree_queries,
        "top_hit_test_bounds_tree_disabled": top_hit_test_bounds_tree_disabled,
        "top_hit_test_bounds_tree_misses": top_hit_test_bounds_tree_misses,
        "top_hit_test_bounds_tree_hits": top_hit_test_bounds_tree_hits,
        "top_hit_test_bounds_tree_candidate_rejected": top_hit_test_bounds_tree_candidate_rejected,
        "top_frame_arena_capacity_estimate_bytes": top_frame_arena_capacity_estimate_bytes,
        "top_frame_arena_grow_events": top_frame_arena_grow_events,
        "top_element_children_vec_pool_reuses": top_element_children_vec_pool_reuses,
        "top_element_children_vec_pool_misses": top_element_children_vec_pool_misses,
        "top_tick_id": top_tick,
        "top_frame_id": top_frame,
        "top_view_cache_contained_relayouts": top_view_cache_contained_relayouts,
        "top_view_cache_roots_total": top_view_cache_roots_total,
        "top_view_cache_roots_reused": top_view_cache_roots_reused,
        "top_view_cache_roots_first_mount": top_view_cache_roots_first_mount,
        "top_view_cache_roots_node_recreated": top_view_cache_roots_node_recreated,
        "top_view_cache_roots_cache_key_mismatch": top_view_cache_roots_cache_key_mismatch,
        "top_view_cache_roots_not_marked_reuse_root": top_view_cache_roots_not_marked_reuse_root,
        "top_view_cache_roots_needs_rerender": top_view_cache_roots_needs_rerender,
        "top_view_cache_roots_layout_invalidated": top_view_cache_roots_layout_invalidated,
        "top_view_cache_roots_manual": top_view_cache_roots_manual,
        "top_cache_roots_contained_relayout": top_cache_roots_contained_relayout,
        "top_set_children_barrier_writes": top_set_children_barrier_writes,
        "top_barrier_relayouts_scheduled": top_barrier_relayouts_scheduled,
        "top_barrier_relayouts_performed": top_barrier_relayouts_performed,
        "top_virtual_list_visible_range_checks": top_virtual_list_visible_range_checks,
        "top_virtual_list_visible_range_refreshes": top_virtual_list_visible_range_refreshes,
        "top_renderer_tick_id": top_renderer_tick_id,
        "top_renderer_frame_id": top_renderer_frame_id,
        "top_renderer_encode_scene_us": top_renderer_encode_scene_us,
        "top_renderer_prepare_text_us": top_renderer_prepare_text_us,
        "top_renderer_prepare_svg_us": top_renderer_prepare_svg_us,
        "top_renderer_draw_calls": top_renderer_draw_calls,
        "top_renderer_pipeline_switches": top_renderer_pipeline_switches,
        "top_renderer_bind_group_switches": top_renderer_bind_group_switches,
        "top_renderer_scissor_sets": top_renderer_scissor_sets,
        "top_renderer_scene_encoding_cache_misses": top_renderer_scene_encoding_cache_misses,
        "top_renderer_material_quad_ops": top_renderer_material_quad_ops,
        "top_renderer_material_sampled_quad_ops": top_renderer_material_sampled_quad_ops,
        "top_renderer_material_distinct": top_renderer_material_distinct,
        "top_renderer_material_unknown_ids": top_renderer_material_unknown_ids,
        "top_renderer_material_degraded_due_to_budget": top_renderer_material_degraded_due_to_budget,
        "top_renderer_text_atlas_upload_bytes": top_renderer_text_atlas_upload_bytes,
        "top_renderer_text_atlas_evicted_pages": top_renderer_text_atlas_evicted_pages,
        "top_renderer_svg_upload_bytes": top_renderer_svg_upload_bytes,
        "top_renderer_image_upload_bytes": top_renderer_image_upload_bytes,
        "top_renderer_svg_raster_cache_misses": top_renderer_svg_raster_cache_misses,
        "top_renderer_svg_raster_budget_evictions": top_renderer_svg_raster_budget_evictions,
        "top_renderer_svg_raster_budget_bytes": top_renderer_svg_raster_budget_bytes,
        "top_renderer_svg_rasters_live": top_renderer_svg_rasters_live,
        "top_renderer_svg_standalone_bytes_live": top_renderer_svg_standalone_bytes_live,
        "top_renderer_svg_mask_atlas_pages_live": top_renderer_svg_mask_atlas_pages_live,
        "top_renderer_svg_mask_atlas_bytes_live": top_renderer_svg_mask_atlas_bytes_live,
        "top_renderer_svg_mask_atlas_used_px": top_renderer_svg_mask_atlas_used_px,
        "top_renderer_svg_mask_atlas_capacity_px": top_renderer_svg_mask_atlas_capacity_px,
        "top_renderer_svg_raster_cache_hits": top_renderer_svg_raster_cache_hits,
        "top_renderer_svg_mask_atlas_page_evictions": top_renderer_svg_mask_atlas_page_evictions,
        "top_renderer_svg_mask_atlas_entries_evicted": top_renderer_svg_mask_atlas_entries_evicted,
        "top_renderer_intermediate_budget_bytes": top_renderer_intermediate_budget_bytes,
        "top_renderer_intermediate_in_use_bytes": top_renderer_intermediate_in_use_bytes,
        "top_renderer_intermediate_peak_in_use_bytes": top_renderer_intermediate_peak_in_use_bytes,
        "top_renderer_intermediate_release_targets": top_renderer_intermediate_release_targets,
        "top_renderer_intermediate_pool_allocations": top_renderer_intermediate_pool_allocations,
        "top_renderer_intermediate_pool_reuses": top_renderer_intermediate_pool_reuses,
        "top_renderer_intermediate_pool_releases": top_renderer_intermediate_pool_releases,
        "top_renderer_intermediate_pool_evictions": top_renderer_intermediate_pool_evictions,
        "top_renderer_intermediate_pool_free_bytes": top_renderer_intermediate_pool_free_bytes,
        "top_renderer_intermediate_pool_free_textures": top_renderer_intermediate_pool_free_textures,
        "bundle": bundle_path.display().to_string(),
    }));
}

