use super::*;

pub(super) struct SingleRunThresholdInputs<'a> {
    pub script_key: &'a str,
    pub sort: BundleStatsSort,
    pub perf_threshold_agg: PerfThresholdAggregate,
    pub cli_thresholds: PerfThresholds,
    pub baseline_thresholds: PerfThresholds,

    pub top_total: u64,
    pub top_layout: u64,
    pub top_solve: u64,
    pub top_solves: u64,
    pub top_tick: u64,
    pub top_frame: u64,

    pub frame_p95_total_time_us: u64,
    pub frame_p95_layout_time_us: u64,
    pub frame_p95_layout_engine_solve_time_us: u64,

    pub pointer_move_frames_present: bool,
    pub pointer_move_frames_considered: u64,
    pub pointer_move_max_dispatch_time_us: u64,
    pub pointer_move_max_hit_test_time_us: u64,
    pub pointer_move_snapshots_with_global_changes: u64,

    pub run_paint_cache_hit_test_only_replay_allowed_max: u64,
    pub run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max: u64,

    pub max_renderer_encode_scene_us: u64,
    pub max_renderer_upload_us: u64,
    pub max_renderer_record_passes_us: u64,
    pub max_renderer_encoder_finish_us: u64,
    pub max_renderer_prepare_text_us: u64,
    pub max_renderer_prepare_svg_us: u64,

    pub bundle_path: &'a Path,

    pub thr_total: Option<u64>,
    pub src_total: Option<&'static str>,
    pub thr_layout: Option<u64>,
    pub src_layout: Option<&'static str>,
    pub thr_solve: Option<u64>,
    pub src_solve: Option<&'static str>,
    pub thr_frame_p95_total: Option<u64>,
    pub src_frame_p95_total: Option<&'static str>,
    pub thr_frame_p95_layout: Option<u64>,
    pub src_frame_p95_layout: Option<&'static str>,
    pub thr_frame_p95_solve: Option<u64>,
    pub src_frame_p95_solve: Option<&'static str>,
    pub thr_pointer_move_dispatch: Option<u64>,
    pub src_pointer_move_dispatch: Option<&'static str>,
    pub thr_pointer_move_hit_test: Option<u64>,
    pub src_pointer_move_hit_test: Option<&'static str>,
    pub thr_pointer_move_global_changes: Option<u64>,
    pub src_pointer_move_global_changes: Option<&'static str>,
    pub thr_paint_cache_hit_test_only_replay_allowed_max: Option<u64>,
    pub src_paint_cache_hit_test_only_replay_allowed_max: Option<&'static str>,
    pub thr_paint_cache_hit_test_only_replay_rejected_key_mismatch_max: Option<u64>,
    pub src_paint_cache_hit_test_only_replay_rejected_key_mismatch_max: Option<&'static str>,
}

pub(super) fn push_single_run_threshold_row_and_failures(
    perf_threshold_rows: &mut Vec<serde_json::Value>,
    perf_threshold_failures: &mut Vec<serde_json::Value>,
    input: SingleRunThresholdInputs<'_>,
) {
    let SingleRunThresholdInputs {
        script_key,
        sort,
        perf_threshold_agg,
        cli_thresholds,
        baseline_thresholds,
        top_total,
        top_layout,
        top_solve,
        top_solves,
        top_tick,
        top_frame,
        frame_p95_total_time_us,
        frame_p95_layout_time_us,
        frame_p95_layout_engine_solve_time_us,
        pointer_move_frames_present,
        pointer_move_frames_considered,
        pointer_move_max_dispatch_time_us,
        pointer_move_max_hit_test_time_us,
        pointer_move_snapshots_with_global_changes,
        run_paint_cache_hit_test_only_replay_allowed_max,
        run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        max_renderer_encode_scene_us,
        max_renderer_upload_us,
        max_renderer_record_passes_us,
        max_renderer_encoder_finish_us,
        max_renderer_prepare_text_us,
        max_renderer_prepare_svg_us,
        bundle_path,
        thr_total,
        src_total,
        thr_layout,
        src_layout,
        thr_solve,
        src_solve,
        thr_frame_p95_total,
        src_frame_p95_total,
        thr_frame_p95_layout,
        src_frame_p95_layout,
        thr_frame_p95_solve,
        src_frame_p95_solve,
        thr_pointer_move_dispatch,
        src_pointer_move_dispatch,
        thr_pointer_move_hit_test,
        src_pointer_move_hit_test,
        thr_pointer_move_global_changes,
        src_pointer_move_global_changes,
        thr_paint_cache_hit_test_only_replay_allowed_max,
        src_paint_cache_hit_test_only_replay_allowed_max,
        thr_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        src_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
    } = input;

    let run = serde_json::json!({
        "run_index": 0,
        "top_total_time_us": top_total,
        "top_layout_time_us": top_layout,
        "top_layout_engine_solve_time_us": top_solve,
        "top_layout_engine_solves": top_solves,
        "pointer_move_frames_present": pointer_move_frames_present,
        "pointer_move_frames_considered": pointer_move_frames_considered,
        "pointer_move_max_dispatch_time_us": pointer_move_max_dispatch_time_us,
        "pointer_move_max_hit_test_time_us": pointer_move_max_hit_test_time_us,
        "pointer_move_snapshots_with_global_changes": pointer_move_snapshots_with_global_changes,
        "run_paint_cache_hit_test_only_replay_allowed_max": run_paint_cache_hit_test_only_replay_allowed_max,
        "run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max": run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        "top_tick_id": top_tick,
        "top_frame_id": top_frame,
        "bundle": bundle_path.display().to_string(),
    });
    let row = serde_json::json!({
        "script": script_key,
        "sort": sort.as_str(),
        "repeat": 1,
        "runs": [run],
        "observed_aggregate": perf_threshold_agg.as_str(),
        "observed": {
            "top_total_time_us": top_total,
            "top_layout_time_us": top_layout,
            "top_layout_engine_solve_time_us": top_solve,
        },
        "worst_run": {
            "top_total_time_us": top_total,
            "bundle": bundle_path.display().to_string(),
            "trace_chrome": bundle_path
                .parent()
                .map(|dir| dir.join("trace.chrome.json"))
                .filter(|p| p.is_file())
                .map(|p| p.display().to_string()),
        },
        "max": {
            "top_total_time_us": top_total,
            "top_layout_time_us": top_layout,
            "top_layout_engine_solve_time_us": top_solve,
            "frame_p95_total_time_us": frame_p95_total_time_us,
            "frame_p95_layout_time_us": frame_p95_layout_time_us,
            "frame_p95_layout_engine_solve_time_us": frame_p95_layout_engine_solve_time_us,
            "pointer_move_max_dispatch_time_us": pointer_move_max_dispatch_time_us,
            "pointer_move_max_hit_test_time_us": pointer_move_max_hit_test_time_us,
            "pointer_move_snapshots_with_global_changes": pointer_move_snapshots_with_global_changes,
            "run_paint_cache_hit_test_only_replay_allowed_max": run_paint_cache_hit_test_only_replay_allowed_max,
            "run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max": run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        },
        "p50": {
            "top_total_time_us": top_total,
            "top_layout_time_us": top_layout,
            "top_layout_engine_solve_time_us": top_solve,
            "frame_p95_total_time_us": frame_p95_total_time_us,
            "frame_p95_layout_time_us": frame_p95_layout_time_us,
            "frame_p95_layout_engine_solve_time_us": frame_p95_layout_engine_solve_time_us,
        },
        "p95": {
            "top_total_time_us": top_total,
            "top_layout_time_us": top_layout,
            "top_layout_engine_solve_time_us": top_solve,
            "frame_p95_total_time_us": frame_p95_total_time_us,
            "frame_p95_layout_time_us": frame_p95_layout_time_us,
            "frame_p95_layout_engine_solve_time_us": frame_p95_layout_engine_solve_time_us,
        },
        "thresholds": {
            "max_top_total_us": thr_total,
            "max_top_layout_us": thr_layout,
            "max_top_solve_us": thr_solve,
            "max_frame_p95_total_us": thr_frame_p95_total,
            "max_frame_p95_layout_us": thr_frame_p95_layout,
            "max_frame_p95_solve_us": thr_frame_p95_solve,
            "max_pointer_move_dispatch_us": thr_pointer_move_dispatch,
            "max_pointer_move_hit_test_us": thr_pointer_move_hit_test,
            "max_pointer_move_global_changes": thr_pointer_move_global_changes,
            "min_run_paint_cache_hit_test_only_replay_allowed_max": thr_paint_cache_hit_test_only_replay_allowed_max,
            "max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max": thr_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        },
        "threshold_sources": {
            "max_top_total_us": src_total,
            "max_top_layout_us": src_layout,
            "max_top_solve_us": src_solve,
            "max_frame_p95_total_us": src_frame_p95_total,
            "max_frame_p95_layout_us": src_frame_p95_layout,
            "max_frame_p95_solve_us": src_frame_p95_solve,
            "max_pointer_move_dispatch_us": src_pointer_move_dispatch,
            "max_pointer_move_hit_test_us": src_pointer_move_hit_test,
            "max_pointer_move_global_changes": src_pointer_move_global_changes,
            "min_run_paint_cache_hit_test_only_replay_allowed_max": src_paint_cache_hit_test_only_replay_allowed_max,
            "max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max": src_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        },
    });

    perf_threshold_rows.push(row);
    perf_threshold_failures.extend(scan_perf_threshold_failures(
        script_key,
        sort,
        perf_threshold_agg,
        cli_thresholds,
        baseline_thresholds,
        top_total,
        top_total,
        top_total,
        top_layout,
        top_layout,
        top_layout,
        top_solve,
        top_solve,
        top_solve,
        frame_p95_total_time_us,
        frame_p95_total_time_us,
        frame_p95_total_time_us,
        frame_p95_layout_time_us,
        frame_p95_layout_time_us,
        frame_p95_layout_time_us,
        frame_p95_layout_engine_solve_time_us,
        frame_p95_layout_engine_solve_time_us,
        frame_p95_layout_engine_solve_time_us,
        pointer_move_frames_present,
        pointer_move_max_dispatch_time_us,
        pointer_move_max_hit_test_time_us,
        pointer_move_snapshots_with_global_changes,
        run_paint_cache_hit_test_only_replay_allowed_max,
        run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        max_renderer_encode_scene_us,
        max_renderer_encode_scene_us,
        max_renderer_encode_scene_us,
        max_renderer_upload_us,
        max_renderer_upload_us,
        max_renderer_upload_us,
        max_renderer_record_passes_us,
        max_renderer_record_passes_us,
        max_renderer_record_passes_us,
        max_renderer_encoder_finish_us,
        max_renderer_encoder_finish_us,
        max_renderer_encoder_finish_us,
        max_renderer_prepare_text_us,
        max_renderer_prepare_text_us,
        max_renderer_prepare_text_us,
        max_renderer_prepare_svg_us,
        max_renderer_prepare_svg_us,
        max_renderer_prepare_svg_us,
        Some(bundle_path),
        Some(0),
        None,
        None,
        None,
        None,
    ));
}

pub(super) struct RepeatThresholdInputs<'a> {
    pub script_key: &'a str,
    pub sort: BundleStatsSort,
    pub repeat: usize,
    pub runs_json: &'a Vec<serde_json::Value>,
    pub perf_threshold_agg: PerfThresholdAggregate,
    pub cli_thresholds: PerfThresholds,
    pub baseline_thresholds: PerfThresholds,

    pub observed_total: u64,
    pub max_total: u64,
    pub p95_total: u64,
    pub sorted_total: &'a Vec<u64>,
    pub p90_total: u64,

    pub observed_layout: u64,
    pub max_layout: u64,
    pub p95_layout: u64,
    pub sorted_layout: &'a Vec<u64>,
    pub p90_layout: u64,

    pub observed_solve: u64,
    pub max_solve: u64,
    pub p95_solve: u64,
    pub sorted_solve: &'a Vec<u64>,
    pub p90_solve: u64,

    pub observed_frame_p95_total: u64,
    pub max_frame_p95_total: u64,
    pub p95_frame_p95_total: u64,
    pub sorted_frame_p95_total: &'a Vec<u64>,
    pub p90_frame_p95_total: u64,

    pub observed_frame_p95_layout: u64,
    pub max_frame_p95_layout: u64,
    pub p95_frame_p95_layout: u64,
    pub sorted_frame_p95_layout: &'a Vec<u64>,
    pub p90_frame_p95_layout: u64,

    pub observed_frame_p95_solve: u64,
    pub max_frame_p95_solve: u64,
    pub p95_frame_p95_solve: u64,
    pub sorted_frame_p95_solve: &'a Vec<u64>,
    pub p90_frame_p95_solve: u64,

    pub pointer_move_frames_present: bool,
    pub max_pointer_move_dispatch: u64,
    pub max_pointer_move_hit_test: u64,
    pub max_pointer_move_global_changes: u64,

    pub max_run_paint_cache_hit_test_only_replay_allowed_max: u64,
    pub max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max: u64,

    pub observed_renderer_encode_scene_us: u64,
    pub max_renderer_encode_scene_us: u64,
    pub p95_renderer_encode_scene_us: u64,

    pub observed_renderer_upload_us: u64,
    pub max_renderer_upload_us: u64,
    pub p95_renderer_upload_us: u64,

    pub observed_renderer_record_passes_us: u64,
    pub max_renderer_record_passes_us: u64,
    pub p95_renderer_record_passes_us: u64,

    pub observed_renderer_encoder_finish_us: u64,
    pub max_renderer_encoder_finish_us: u64,
    pub p95_renderer_encoder_finish_us: u64,

    pub observed_renderer_prepare_text_us: u64,
    pub max_renderer_prepare_text_us: u64,
    pub p95_renderer_prepare_text_us: u64,

    pub observed_renderer_prepare_svg_us: u64,
    pub max_renderer_prepare_svg_us: u64,
    pub p95_renderer_prepare_svg_us: u64,

    pub script_worst: &'a Option<(u64, PathBuf, u64)>,
    pub script_worst_layout: &'a Option<(u64, PathBuf, u64)>,
    pub script_worst_solve: &'a Option<(u64, PathBuf, u64)>,

    pub thr_total: Option<u64>,
    pub src_total: Option<&'static str>,
    pub thr_layout: Option<u64>,
    pub src_layout: Option<&'static str>,
    pub thr_solve: Option<u64>,
    pub src_solve: Option<&'static str>,
    pub thr_frame_p95_total: Option<u64>,
    pub src_frame_p95_total: Option<&'static str>,
    pub thr_frame_p95_layout: Option<u64>,
    pub src_frame_p95_layout: Option<&'static str>,
    pub thr_frame_p95_solve: Option<u64>,
    pub src_frame_p95_solve: Option<&'static str>,
    pub thr_pointer_move_dispatch: Option<u64>,
    pub src_pointer_move_dispatch: Option<&'static str>,
    pub thr_pointer_move_hit_test: Option<u64>,
    pub src_pointer_move_hit_test: Option<&'static str>,
    pub thr_pointer_move_global_changes: Option<u64>,
    pub src_pointer_move_global_changes: Option<&'static str>,
    pub thr_paint_cache_hit_test_only_replay_allowed_max: Option<u64>,
    pub src_paint_cache_hit_test_only_replay_allowed_max: Option<&'static str>,
    pub thr_paint_cache_hit_test_only_replay_rejected_key_mismatch_max: Option<u64>,
    pub src_paint_cache_hit_test_only_replay_rejected_key_mismatch_max: Option<&'static str>,
}

pub(super) fn push_repeat_threshold_row_and_failures(
    perf_threshold_rows: &mut Vec<serde_json::Value>,
    perf_threshold_failures: &mut Vec<serde_json::Value>,
    input: RepeatThresholdInputs<'_>,
) {
    let RepeatThresholdInputs {
        script_key,
        sort,
        repeat,
        runs_json,
        perf_threshold_agg,
        cli_thresholds,
        baseline_thresholds,
        observed_total,
        max_total,
        p95_total,
        sorted_total,
        p90_total,
        observed_layout,
        max_layout,
        p95_layout,
        sorted_layout,
        p90_layout,
        observed_solve,
        max_solve,
        p95_solve,
        sorted_solve,
        p90_solve,
        observed_frame_p95_total,
        max_frame_p95_total,
        p95_frame_p95_total,
        sorted_frame_p95_total,
        p90_frame_p95_total,
        observed_frame_p95_layout,
        max_frame_p95_layout,
        p95_frame_p95_layout,
        sorted_frame_p95_layout,
        p90_frame_p95_layout,
        observed_frame_p95_solve,
        max_frame_p95_solve,
        p95_frame_p95_solve,
        sorted_frame_p95_solve,
        p90_frame_p95_solve,
        pointer_move_frames_present,
        max_pointer_move_dispatch,
        max_pointer_move_hit_test,
        max_pointer_move_global_changes,
        max_run_paint_cache_hit_test_only_replay_allowed_max,
        max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        observed_renderer_encode_scene_us,
        max_renderer_encode_scene_us,
        p95_renderer_encode_scene_us,
        observed_renderer_upload_us,
        max_renderer_upload_us,
        p95_renderer_upload_us,
        observed_renderer_record_passes_us,
        max_renderer_record_passes_us,
        p95_renderer_record_passes_us,
        observed_renderer_encoder_finish_us,
        max_renderer_encoder_finish_us,
        p95_renderer_encoder_finish_us,
        observed_renderer_prepare_text_us,
        max_renderer_prepare_text_us,
        p95_renderer_prepare_text_us,
        observed_renderer_prepare_svg_us,
        max_renderer_prepare_svg_us,
        p95_renderer_prepare_svg_us,
        script_worst,
        script_worst_layout,
        script_worst_solve,
        thr_total,
        src_total,
        thr_layout,
        src_layout,
        thr_solve,
        src_solve,
        thr_frame_p95_total,
        src_frame_p95_total,
        thr_frame_p95_layout,
        src_frame_p95_layout,
        thr_frame_p95_solve,
        src_frame_p95_solve,
        thr_pointer_move_dispatch,
        src_pointer_move_dispatch,
        thr_pointer_move_hit_test,
        src_pointer_move_hit_test,
        thr_pointer_move_global_changes,
        src_pointer_move_global_changes,
        thr_paint_cache_hit_test_only_replay_allowed_max,
        src_paint_cache_hit_test_only_replay_allowed_max,
        thr_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        src_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
    } = input;

    let row = serde_json::json!({
        "script": script_key,
        "sort": sort.as_str(),
        "repeat": repeat,
        "runs": runs_json,
        "observed_aggregate": perf_threshold_agg.as_str(),
        "observed": {
            "top_total_time_us": observed_total,
            "top_layout_time_us": observed_layout,
            "top_layout_engine_solve_time_us": observed_solve,
            "frame_p95_total_time_us": observed_frame_p95_total,
            "frame_p95_layout_time_us": observed_frame_p95_layout,
            "frame_p95_layout_engine_solve_time_us": observed_frame_p95_solve,
        },
        "worst_run": script_worst.as_ref().map(|(us, bundle, run_index)| serde_json::json!({
            "top_total_time_us": us,
            "bundle": bundle.display().to_string(),
            "run_index": run_index,
            "trace_chrome": bundle
                .parent()
                .map(|dir| dir.join("trace.chrome.json"))
                .filter(|p| p.is_file())
                .map(|p| p.display().to_string()),
        })),
        "max": {
            "top_total_time_us": max_total,
            "top_layout_time_us": max_layout,
            "top_layout_engine_solve_time_us": max_solve,
            "frame_p95_total_time_us": max_frame_p95_total,
            "frame_p95_layout_time_us": max_frame_p95_layout,
            "frame_p95_layout_engine_solve_time_us": max_frame_p95_solve,
            "pointer_move_max_dispatch_time_us": max_pointer_move_dispatch,
            "pointer_move_max_hit_test_time_us": max_pointer_move_hit_test,
            "pointer_move_snapshots_with_global_changes": max_pointer_move_global_changes,
            "run_paint_cache_hit_test_only_replay_allowed_max": max_run_paint_cache_hit_test_only_replay_allowed_max,
            "run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max": max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        },
        "p50": {
            "top_total_time_us": percentile_nearest_rank_sorted(sorted_total, 0.50),
            "top_layout_time_us": percentile_nearest_rank_sorted(sorted_layout, 0.50),
            "top_layout_engine_solve_time_us": percentile_nearest_rank_sorted(sorted_solve, 0.50),
            "frame_p95_total_time_us": percentile_nearest_rank_sorted(sorted_frame_p95_total, 0.50),
            "frame_p95_layout_time_us": percentile_nearest_rank_sorted(sorted_frame_p95_layout, 0.50),
            "frame_p95_layout_engine_solve_time_us": percentile_nearest_rank_sorted(sorted_frame_p95_solve, 0.50),
        },
        "p90": {
            "top_total_time_us": p90_total,
            "top_layout_time_us": p90_layout,
            "top_layout_engine_solve_time_us": p90_solve,
            "frame_p95_total_time_us": p90_frame_p95_total,
            "frame_p95_layout_time_us": p90_frame_p95_layout,
            "frame_p95_layout_engine_solve_time_us": p90_frame_p95_solve,
        },
        "p95": {
            "top_total_time_us": p95_total,
            "top_layout_time_us": p95_layout,
            "top_layout_engine_solve_time_us": p95_solve,
            "frame_p95_total_time_us": p95_frame_p95_total,
            "frame_p95_layout_time_us": p95_frame_p95_layout,
            "frame_p95_layout_engine_solve_time_us": p95_frame_p95_solve,
        },
        "thresholds": {
            "max_top_total_us": thr_total,
            "max_top_layout_us": thr_layout,
            "max_top_solve_us": thr_solve,
            "max_frame_p95_total_us": thr_frame_p95_total,
            "max_frame_p95_layout_us": thr_frame_p95_layout,
            "max_frame_p95_solve_us": thr_frame_p95_solve,
            "max_pointer_move_dispatch_us": thr_pointer_move_dispatch,
            "max_pointer_move_hit_test_us": thr_pointer_move_hit_test,
            "max_pointer_move_global_changes": thr_pointer_move_global_changes,
            "min_run_paint_cache_hit_test_only_replay_allowed_max": thr_paint_cache_hit_test_only_replay_allowed_max,
            "max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max": thr_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        },
        "threshold_sources": {
            "max_top_total_us": src_total,
            "max_top_layout_us": src_layout,
            "max_top_solve_us": src_solve,
            "max_frame_p95_total_us": src_frame_p95_total,
            "max_frame_p95_layout_us": src_frame_p95_layout,
            "max_frame_p95_solve_us": src_frame_p95_solve,
            "max_pointer_move_dispatch_us": src_pointer_move_dispatch,
            "max_pointer_move_hit_test_us": src_pointer_move_hit_test,
            "max_pointer_move_global_changes": src_pointer_move_global_changes,
            "min_run_paint_cache_hit_test_only_replay_allowed_max": src_paint_cache_hit_test_only_replay_allowed_max,
            "max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max": src_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        },
    });

    perf_threshold_rows.push(row);
    perf_threshold_failures.extend(scan_perf_threshold_failures(
        script_key,
        sort,
        perf_threshold_agg,
        cli_thresholds,
        baseline_thresholds,
        observed_total,
        max_total,
        p95_total,
        observed_layout,
        max_layout,
        p95_layout,
        observed_solve,
        max_solve,
        p95_solve,
        observed_frame_p95_total,
        max_frame_p95_total,
        p95_frame_p95_total,
        observed_frame_p95_layout,
        max_frame_p95_layout,
        p95_frame_p95_layout,
        observed_frame_p95_solve,
        max_frame_p95_solve,
        p95_frame_p95_solve,
        pointer_move_frames_present,
        max_pointer_move_dispatch,
        max_pointer_move_hit_test,
        max_pointer_move_global_changes,
        max_run_paint_cache_hit_test_only_replay_allowed_max,
        max_run_paint_cache_hit_test_only_replay_rejected_key_mismatch_max,
        observed_renderer_encode_scene_us,
        max_renderer_encode_scene_us,
        p95_renderer_encode_scene_us,
        observed_renderer_upload_us,
        max_renderer_upload_us,
        p95_renderer_upload_us,
        observed_renderer_record_passes_us,
        max_renderer_record_passes_us,
        p95_renderer_record_passes_us,
        observed_renderer_encoder_finish_us,
        max_renderer_encoder_finish_us,
        p95_renderer_encoder_finish_us,
        observed_renderer_prepare_text_us,
        max_renderer_prepare_text_us,
        p95_renderer_prepare_text_us,
        observed_renderer_prepare_svg_us,
        max_renderer_prepare_svg_us,
        p95_renderer_prepare_svg_us,
        script_worst
            .as_ref()
            .map(|(_us, bundle, _run)| bundle.as_path()),
        script_worst.as_ref().map(|(_us, _bundle, run)| *run),
        script_worst_layout
            .as_ref()
            .map(|(_us, bundle, _run)| bundle.as_path()),
        script_worst_layout.as_ref().map(|(_us, _bundle, run)| *run),
        script_worst_solve
            .as_ref()
            .map(|(_us, bundle, _run)| bundle.as_path()),
        script_worst_solve.as_ref().map(|(_us, _bundle, run)| *run),
    ));
}
