//! MVU-style authoring helpers (inspired by `iced`).
//!
//! Goals:
//! - Keep application state local and typed (`struct State`, `enum Message`).
//! - Avoid stringly `CommandId` parsing in app code.
//! - Stay ecosystem-level (built on top of `UiAppDriver`), preserving `fret-ui` contract boundaries.

use std::collections::HashMap;
use std::hash::Hash;

use fret_app::App;
use fret_core::{AppWindowId, UiServices};
use fret_runtime::{CommandId, Model};
use fret_ui::element::Elements;
use fret_ui::{ElementContext, Invalidation, UiTree};

use crate::{BootstrapError, Result, UiAppBuilder, UiAppDriver};

/// A per-frame message router that turns typed messages into `CommandId`.
///
/// This avoids hand-written `"my.command.prefix.{id}"` parsing in app code. The router stores a
/// frame-local map from generated command IDs to message values and resolves them in the driver's
/// `on_command` hook.
///
/// Notes:
/// - Commands generated by this router are intended to be used inside the same frame.
/// - If a `CommandId` arrives that is not present in the current map, it will be ignored.
/// - This is not a good fit for dynamic commands inside a `view_cache(...)` subtree that can be
///   reused without rebuilding: the router relies on rebuilding the view to (re)register the
///   current-frame command->message bindings.
#[derive(Debug)]
pub struct MessageRouter<M> {
    prefix: String,
    next: u64,
    by_key: HashMap<String, M>,
}

impl<M> MessageRouter<M> {
    pub fn new(prefix: impl Into<String>) -> Self {
        Self {
            prefix: prefix.into(),
            next: 0,
            by_key: HashMap::new(),
        }
    }

    /// Clear any previously registered message bindings.
    ///
    /// This is called automatically by the MVU driver once per frame.
    pub fn clear(&mut self) {
        self.by_key.clear();
        self.next = 0;
    }

    /// Allocate a `CommandId` that resolves to `message`.
    pub fn cmd(&mut self, message: M) -> CommandId {
        let key = format!("{}{id}", self.prefix, id = self.next);
        self.next = self.next.saturating_add(1);
        self.by_key.insert(key.clone(), message);
        CommandId::new(key)
    }

    /// Resolve and remove a previously allocated message binding.
    ///
    /// This is intended for routing `CommandId` back to typed messages in a driver hook.
    /// If `command` is not present in the current map, returns `None`.
    pub fn try_take(&mut self, command: &CommandId) -> Option<M> {
        self.by_key.remove(command.as_str())
    }
}

/// A persistent, keyed message router that maps typed messages to stable `CommandId`s.
///
/// Compared to `MessageRouter`:
///
/// - Commands are keyed (stable per key) rather than per-frame sequential.
/// - Mappings persist until explicitly cleared or pruned.
/// - Resolution returns a clone and does not consume the entry.
///
/// This is intended for dynamic commands used inside `view_cache(...)` subtrees, where reuse can
/// skip rebuilding the view and therefore skip re-registering per-frame bindings.
#[derive(Debug)]
pub struct KeyedMessageRouter<K, M> {
    prefix: String,
    next: u64,
    command_by_key: HashMap<K, CommandId>,
    message_by_command: HashMap<CommandId, M>,
}

impl<K, M> KeyedMessageRouter<K, M>
where
    K: Eq + Hash,
{
    pub fn new(prefix: impl Into<String>) -> Self {
        Self {
            prefix: prefix.into(),
            next: 0,
            command_by_key: HashMap::new(),
            message_by_command: HashMap::new(),
        }
    }

    /// Clear all registered bindings.
    ///
    /// Call this when the corresponding UI subtree is unmounted or when a page switches, to avoid
    /// unbounded growth.
    pub fn clear(&mut self) {
        self.command_by_key.clear();
        self.message_by_command.clear();
        self.next = 0;
    }

    /// Remove a binding for `key`, if present.
    pub fn remove_key(&mut self, key: &K) -> bool {
        let Some(cmd) = self.command_by_key.remove(key) else {
            return false;
        };
        self.message_by_command.remove(&cmd);
        true
    }

    /// Retain only keys that match `keep`.
    pub fn retain_keys(&mut self, mut keep: impl FnMut(&K) -> bool) {
        let message_by_command = &mut self.message_by_command;
        self.command_by_key.retain(|k, cmd| {
            if keep(k) {
                true
            } else {
                message_by_command.remove(cmd);
                false
            }
        });
    }

    /// Allocate a stable `CommandId` for `key`, and associate it with `message`.
    ///
    /// If `key` was previously seen, the same `CommandId` will be returned and the stored message
    /// will be replaced.
    pub fn cmd(&mut self, key: K, message: M) -> CommandId {
        let cmd = self.command_by_key.get(&key).cloned().unwrap_or_else(|| {
            let id = format!("{}{n}", self.prefix, n = self.next);
            self.next = self.next.saturating_add(1);
            let cmd = CommandId::new(id);
            self.command_by_key.insert(key, cmd.clone());
            cmd
        });

        self.message_by_command.insert(cmd.clone(), message);
        cmd
    }
}

impl<K, M> KeyedMessageRouter<K, M>
where
    K: Eq + Hash,
    M: Clone,
{
    /// Resolve a previously registered `CommandId` to a typed message.
    pub fn try_resolve(&self, command: &CommandId) -> Option<M> {
        self.message_by_command.get(command).cloned()
    }
}

/// Minimal MVU program definition.
///
/// This trait-based shape is intentional: the golden-path driver uses `fn` pointers for hotpatch
/// predictability, so we cannot capture arbitrary closures in the runner wiring.
pub trait Program: 'static {
    type State: 'static;
    type Message: 'static;

    fn init(app: &mut App, window: AppWindowId) -> Self::State;
    fn update(app: &mut App, state: &mut Self::State, message: Self::Message);
    fn view(
        cx: &mut ElementContext<'_, App>,
        state: &mut Self::State,
        msg: &mut MessageRouter<Self::Message>,
    ) -> Elements;

    fn on_command(
        _app: &mut App,
        _services: &mut dyn UiServices,
        _window: AppWindowId,
        _ui: &mut UiTree<App>,
        _state: &mut Self::State,
        _command: &CommandId,
    ) -> bool {
        false
    }
}

#[derive(Debug)]
#[doc(hidden)]
pub struct MvuWindowState<S, M> {
    pub(crate) user: S,
    pub(crate) router: MessageRouter<M>,
    pub(crate) tick: Model<u64>,
}

/// `UiAppDriver` wrapper used by MVU entry points.
///
/// Intentionally does not expose `.on_command(...)` to avoid accidentally overriding MVU routing.
pub struct MvuUiAppDriver<S, M> {
    inner: UiAppDriver<MvuWindowState<S, M>>,
}

impl<S, M> MvuUiAppDriver<S, M> {
    fn new(inner: UiAppDriver<MvuWindowState<S, M>>) -> Self {
        Self { inner }
    }

    fn into_inner(self) -> UiAppDriver<MvuWindowState<S, M>> {
        self.inner
    }

    pub fn close_on_window_close_requested(mut self, enabled: bool) -> Self {
        self.inner = self.inner.close_on_window_close_requested(enabled);
        self
    }

    #[cfg(feature = "ui-assets")]
    pub fn drive_ui_assets(mut self, enabled: bool) -> Self {
        self.inner = self.inner.drive_ui_assets(enabled);
        self
    }

    pub fn on_event(
        mut self,
        f: fn(
            &mut App,
            &mut dyn UiServices,
            AppWindowId,
            &mut UiTree<App>,
            &mut MvuWindowState<S, M>,
            &fret_core::Event,
        ),
    ) -> Self {
        self.inner = self.inner.on_event(f);
        self
    }

    pub fn viewport_input(mut self, f: fn(&mut App, fret_core::ViewportInputEvent)) -> Self {
        self.inner = self.inner.viewport_input(f);
        self
    }

    pub fn record_engine_frame(
        mut self,
        f: fn(
            &mut App,
            AppWindowId,
            &mut UiTree<App>,
            &mut MvuWindowState<S, M>,
            &crate::fret::render::WgpuContext,
            &mut crate::fret::render::Renderer,
            f32,
            fret_runtime::TickId,
            fret_runtime::FrameId,
        ) -> fret_launch::EngineFrameUpdate,
    ) -> Self {
        self.inner = self.inner.record_engine_frame(f);
        self
    }

    pub fn dock_op(mut self, f: fn(&mut App, fret_core::DockOp)) -> Self {
        self.inner = self.inner.dock_op(f);
        self
    }

    #[cfg(feature = "command-palette")]
    pub fn command_palette(mut self, enabled: bool) -> Self {
        self.inner = self.inner.command_palette(enabled);
        self
    }
}

fn mvu_init_window<P: Program>(
    app: &mut App,
    window: AppWindowId,
) -> MvuWindowState<P::State, P::Message> {
    let user = P::init(app, window);
    let tick = app.models_mut().insert(0u64);
    let prefix = format!("mvu.{window:?}.");
    MvuWindowState {
        user,
        router: MessageRouter::new(prefix),
        tick,
    }
}

fn mvu_view<P: Program>(
    cx: &mut ElementContext<'_, App>,
    st: &mut MvuWindowState<P::State, P::Message>,
) -> fret_bootstrap::ui_app_driver::ViewElements {
    cx.observe_model(&st.tick, Invalidation::Layout);
    st.router.clear();
    P::view(cx, &mut st.user, &mut st.router).into()
}

fn mvu_on_command<P: Program>(
    app: &mut App,
    services: &mut dyn UiServices,
    window: AppWindowId,
    ui: &mut UiTree<App>,
    st: &mut MvuWindowState<P::State, P::Message>,
    command: &CommandId,
) {
    if let Some(message) = st.router.try_take(command) {
        P::update(app, &mut st.user, message);
        let _ = app
            .models_mut()
            .update(&st.tick, |v| *v = v.saturating_add(1));
        app.request_redraw(window);
        return;
    }

    if !P::on_command(app, services, window, ui, &mut st.user, command) {
        return;
    }

    let _ = app
        .models_mut()
        .update(&st.tick, |v| *v = v.saturating_add(1));
    app.request_redraw(window);
}

/// Create a desktop-first MVU app builder with conservative defaults applied.
///
/// Compared to `app_with_hooks`, this adds:
/// - a `MessageRouter<M>` parameter to `Program::view` to build typed commands
/// - a default `on_command` that routes these messages to `Program::update`
/// - an internal `tick` model to force a full layout refresh after each `update`
#[cfg(all(not(target_arch = "wasm32"), feature = "desktop"))]
pub fn app_with_hooks<P: Program>(
    root_name: &'static str,
    configure: fn(MvuUiAppDriver<P::State, P::Message>) -> MvuUiAppDriver<P::State, P::Message>,
) -> Result<UiAppBuilder<MvuWindowState<P::State, P::Message>>> {
    let driver =
        fret_bootstrap::ui_app_driver::UiAppDriver::new(
            root_name,
            mvu_init_window::<P>,
            mvu_view::<P>,
        )
        .on_command(mvu_on_command::<P>)
        .on_preferences(
            fret_bootstrap::ui_app_driver::default_on_preferences::<
                MvuWindowState<P::State, P::Message>,
            >,
        );
    #[cfg(feature = "shadcn")]
    let driver = driver.on_global_changes_middleware(
        crate::shadcn_sync_theme_from_environment_on_global_changes::<
            MvuWindowState<P::State, P::Message>,
        >,
    );
    let driver = configure(MvuUiAppDriver::new(UiAppDriver::new(driver))).into_inner();
    let driver = driver.into_inner();

    let builder = fret_bootstrap::BootstrapBuilder::new(App::new(), driver.into_fn_driver());

    #[cfg(feature = "diagnostics")]
    let builder = builder.with_default_diagnostics();

    let builder = builder
        .with_default_config_files()
        .map_err(BootstrapError::from)?;

    #[cfg(feature = "shadcn")]
    let builder = builder.install_app(fret_ui_shadcn::install_app);

    #[cfg(feature = "ui-assets")]
    let builder = builder.with_ui_assets_budgets(64 * 1024 * 1024, 4096, 16 * 1024 * 1024, 4096);

    #[cfg(feature = "icons-lucide")]
    let builder = builder.with_lucide_icons();

    #[cfg(feature = "icons-radix")]
    let builder = builder.with_radix_icons();

    #[cfg(feature = "preload-icon-svgs")]
    let builder = builder.preload_icon_svgs_on_gpu_ready();

    Ok(UiAppBuilder::new(builder))
}

/// Same as [`app_with_hooks`], but without a driver configuration hook.
#[cfg(all(not(target_arch = "wasm32"), feature = "desktop"))]
pub fn app<P: Program>(
    root_name: &'static str,
) -> Result<UiAppBuilder<MvuWindowState<P::State, P::Message>>> {
    app_with_hooks::<P>(root_name, |d| d)
}

/// Run a desktop-first MVU app using default window settings.
#[cfg(all(not(target_arch = "wasm32"), feature = "desktop"))]
pub fn run_with_hooks<P: Program>(
    root_name: &'static str,
    configure: fn(MvuUiAppDriver<P::State, P::Message>) -> MvuUiAppDriver<P::State, P::Message>,
) -> Result<()> {
    app_with_hooks::<P>(root_name, configure)?
        .with_main_window(root_name, (960.0, 720.0))
        .run()?;
    Ok(())
}

/// Run a desktop-first MVU app using default window settings.
#[cfg(all(not(target_arch = "wasm32"), feature = "desktop"))]
pub fn run<P: Program>(root_name: &'static str) -> Result<()> {
    run_with_hooks::<P>(root_name, |d| d)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_router_allocates_unique_commands_and_routes() {
        let mut router = MessageRouter::new("test.");

        let c1 = router.cmd(1u32);
        let c2 = router.cmd(2u32);
        assert_ne!(c1, c2);

        assert_eq!(router.try_take(&c1), Some(1u32));
        assert_eq!(router.try_take(&c1), None);
        assert_eq!(router.try_take(&c2), Some(2u32));

        router.clear();
        let c3 = router.cmd(3u32);
        assert_eq!(router.try_take(&c3), Some(3u32));
    }
}
