//! MVU-style command routing helpers (portable).
//!
//! This module is intended to be usable across desktop + web builds.
//! It is intentionally self-contained and does not depend on the desktop-only `UiAppDriver`.

use std::collections::HashMap;
use std::hash::Hash;

use fret_runtime::CommandId;

/// A per-frame message router that turns typed messages into `CommandId`.
///
/// This avoids hand-written `"my.command.prefix.{id}"` parsing in app code. The router stores a
/// frame-local map from generated command IDs to message values and resolves them by consuming the
/// entry.
///
/// Notes:
/// - Commands generated by this router are intended to be used inside the same frame.
/// - If a `CommandId` arrives that is not present in the current map, it will be ignored.
#[derive(Debug)]
pub struct MessageRouter<M> {
    prefix: String,
    next: u64,
    by_key: HashMap<String, M>,
}

impl<M> MessageRouter<M> {
    pub fn new(prefix: impl Into<String>) -> Self {
        Self {
            prefix: prefix.into(),
            next: 0,
            by_key: HashMap::new(),
        }
    }

    /// Clear any previously registered message bindings.
    pub fn clear(&mut self) {
        self.by_key.clear();
        self.next = 0;
    }

    /// Allocate a `CommandId` that resolves to `message`.
    pub fn cmd(&mut self, message: M) -> CommandId {
        let key = format!("{}{id}", self.prefix, id = self.next);
        self.next = self.next.saturating_add(1);
        self.by_key.insert(key.clone(), message);
        CommandId::new(key)
    }

    /// Resolve and remove a previously allocated message binding.
    pub fn try_take(&mut self, command: &CommandId) -> Option<M> {
        self.by_key.remove(command.as_str())
    }
}

/// A persistent, keyed message router that maps typed messages to stable `CommandId`s.
///
/// This is intended for dynamic commands used inside cached/reused UI subtrees.
#[derive(Debug)]
pub struct KeyedMessageRouter<K, M> {
    prefix: String,
    next: u64,
    command_by_key: HashMap<K, CommandId>,
    message_by_command: HashMap<CommandId, M>,
}

impl<K, M> KeyedMessageRouter<K, M>
where
    K: Eq + Hash,
{
    pub fn new(prefix: impl Into<String>) -> Self {
        Self {
            prefix: prefix.into(),
            next: 0,
            command_by_key: HashMap::new(),
            message_by_command: HashMap::new(),
        }
    }

    pub fn clear(&mut self) {
        self.command_by_key.clear();
        self.message_by_command.clear();
        self.next = 0;
    }

    pub fn retain_keys(&mut self, mut keep: impl FnMut(&K) -> bool) {
        let message_by_command = &mut self.message_by_command;
        self.command_by_key.retain(|k, cmd| {
            if keep(k) {
                true
            } else {
                message_by_command.remove(cmd);
                false
            }
        });
    }

    /// Allocate a stable `CommandId` for `key`, and associate it with `message`.
    pub fn cmd(&mut self, key: K, message: M) -> CommandId {
        let cmd = self.command_by_key.get(&key).cloned().unwrap_or_else(|| {
            let id = format!("{}{n}", self.prefix, n = self.next);
            self.next = self.next.saturating_add(1);
            let cmd = CommandId::new(id);
            self.command_by_key.insert(key, cmd.clone());
            cmd
        });

        self.message_by_command.insert(cmd.clone(), message);
        cmd
    }
}

impl<K, M> KeyedMessageRouter<K, M>
where
    K: Eq + Hash,
    M: Clone,
{
    pub fn try_resolve(&self, command: &CommandId) -> Option<M> {
        self.message_by_command.get(command).cloned()
    }
}
