pub(crate) mod agent;
pub(crate) mod ai_packet;
mod args;
pub(crate) mod artifact;
pub(crate) mod artifacts;
pub(crate) mod bundle_v2;
pub(crate) mod config;
pub(crate) mod dock_graph;
pub(crate) mod dock_routing;
pub(crate) mod doctor;
pub(crate) mod doctor_scripts;
pub(crate) mod extensions;
pub(crate) mod hotspots;
pub(crate) mod index;
pub(crate) mod inspect;
pub(crate) mod layout_perf_summary;
pub(crate) mod layout_sidecar;
pub(crate) mod pick;
pub(crate) mod query;
pub(crate) mod resolve;
pub(crate) mod screenshots;
pub(crate) mod script;
pub(crate) mod session;
mod sidecars;
pub(crate) mod slice;
mod slice_payload;
mod slice_streaming;
pub(crate) mod windows;
