use super::*;

#[test]
fn default_preset_keeps_existing_editor_patch_baseline() {
    let mut app = App::new();
    apply_editor_theme_preset_v1(&mut app, EditorThemePresetV1::Default);

    let theme = Theme::global(&app);
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::DENSITY_ROW_HEIGHT),
        Some(Px(24.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::TEXT_FIELD_MIN_HEIGHT),
        Some(Px(24.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_LABEL_WIDTH),
        Some(Px(124.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_TRAILING_GAP),
        Some(Px(6.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_VALUE_MAX_WIDTH),
        Some(Px(1024.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_STATUS_SLOT_WIDTH),
        Some(Px(56.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_RESET_SLOT_WIDTH),
        Some(Px(24.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_GROUP_CONTENT_GAP),
        Some(Px(10.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_PANEL_GAP),
        Some(Px(14.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_GAP),
        Some(Px(12.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_GROUP_HEADER_HEIGHT),
        Some(Px(28.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::SLIDER_THUMB_DIAMETER),
        Some(Px(12.0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_TRACK_BG),
        Some(Color::from_srgb_hex_rgb(0x17_1d_26))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_FILL_BG),
        Some(Color::from_srgb_hex_rgb(0x35_5a_86))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_THUMB_BG),
        Some(Color::from_srgb_hex_rgb(0x14_1b_24))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_THUMB_BORDER),
        Some(Color::from_srgb_hex_rgb(0x3b_47_58))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_BG),
        Some(Color::from_srgb_hex_rgb(0x14_1b_24))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_CHECKED_BG),
        Some(Color::from_srgb_hex_rgb(0x35_5a_86))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_CHECKED_FG),
        Some(Color::from_srgb_hex_rgb(0xed_f3_fa))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_RING),
        Some(Color::from_srgb_hex_rgb(0x7f_ae_e8))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::TEXT_FIELD_BG),
        Some(Color::from_srgb_hex_rgb(0x14_1b_24))
    );
    assert_eq!(
        theme.color_by_key("background"),
        Some(Color::from_srgb_hex_rgb(0x0c_11_18))
    );
    assert_eq!(
        theme.color_by_key("input"),
        Some(Color::from_srgb_hex_rgb(0x3b_47_58))
    );
    assert_eq!(theme.metric_by_key("component.text_field.min_height"), None);
    assert_eq!(theme.color_by_key("component.text_field.bg"), None);
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_BG),
        Some(Color::from_srgb_hex_rgb(0x0f_15_1d))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::POPUP_BG),
        Some(Color::from_srgb_hex_rgb(0x13_1b_25))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::POPUP_BORDER),
        Some(Color::from_srgb_hex_rgb(0x46_59_6c))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::POPUP_SHADOW_COLOR),
        Some(Color::from_srgb_hex_rgb(0x17_1d_26))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_RADIUS),
        Some(Px(8.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_SHADOW_OFFSET_Y),
        Some(Px(6.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_SHADOW_BLUR),
        Some(Px(16.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_SHADOW_SPREAD),
        Some(Px(-4.0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_BORDER),
        Some(Color::from_srgb_hex_rgb(0x3d_4d_5f))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_PANEL_RADIUS),
        Some(Px(6.0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_BG),
        Some(Color::from_srgb_hex_rgb(0x24_34_45))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_BORDER),
        Some(Color::from_srgb_hex_rgb(0x5a_70_87))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_GROUP_BORDER),
        Some(Color::from_srgb_hex_rgb(0x33_41_4f))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_HEADER_BG),
        Some(Color::from_srgb_hex_rgb(0x19_23_2e))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_HEADER_BORDER),
        Some(Color::from_srgb_hex_rgb(0x38_48_57))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CONTROL_INVALID_BORDER),
        Some(Color::from_srgb_hex_rgb(0xc7_6f_77))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_SPEED),
        Some(Px(0.02))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_SLOW_MULTIPLIER),
        Some(Px(0.1))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_FAST_MULTIPLIER),
        Some(Px(10.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_DRAG_THRESHOLD),
        Some(Px(4.0))
    );
}

#[test]
fn imgui_like_dense_preset_overrides_density_and_field_chrome() {
    let mut app = App::new();
    apply_editor_theme_preset_v1(&mut app, EditorThemePresetV1::ImguiLikeDense);

    let theme = Theme::global(&app);
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::DENSITY_ROW_HEIGHT),
        Some(Px(22.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_DRAG_THRESHOLD),
        Some(Px(2.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_TRAILING_GAP),
        Some(Px(3.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_VALUE_MAX_WIDTH),
        Some(Px(840.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_STATUS_SLOT_WIDTH),
        Some(Px(48.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_RESET_SLOT_WIDTH),
        Some(Px(22.0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::POPUP_BG),
        Some(Color::from_srgb_hex_rgb(0x24_29_2f))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::POPUP_BORDER),
        Some(Color::from_srgb_hex_rgb(0x68_76_86))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::POPUP_SHADOW_COLOR),
        Some(Color::from_srgb_hex_rgb(0x2a_2d_33))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_RADIUS),
        Some(Px(4.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_SHADOW_OFFSET_Y),
        Some(Px(4.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_SHADOW_BLUR),
        Some(Px(12.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::POPUP_SHADOW_SPREAD),
        Some(Px(-3.0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_BG),
        Some(Color::from_srgb_hex_rgb(0x36_41_4c))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_PANEL_RADIUS),
        Some(Px(2.0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_BORDER),
        Some(Color::from_srgb_hex_rgb(0x72_82_94))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_HEADER_BG),
        Some(Color::from_srgb_hex_rgb(0x28_30_39))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_HEADER_BORDER),
        Some(Color::from_srgb_hex_rgb(0x56_62_6f))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_GROUP_CONTENT_GAP),
        Some(Px(6.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_PANEL_GAP),
        Some(Px(10.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_GAP),
        Some(Px(8.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::PROPERTY_GROUP_HEADER_HEIGHT),
        Some(Px(24.0))
    );
    assert_eq!(
        theme.metric_by_key(EditorTokenKeys::TEXT_FIELD_RADIUS),
        Some(Px(2.0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_TRACK_BG),
        Some(Color::from_srgb_hex_rgb(0x2a_2d_33))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_FILL_BG),
        Some(Color::from_srgb_hex_rgb(0x4c_88_c7))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_THUMB_BG),
        Some(Color::from_srgb_hex_rgb(0x1a_1c_20))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::SLIDER_THUMB_BORDER),
        Some(Color::from_srgb_hex_rgb(0x4b_55_63))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_BG),
        Some(Color::from_srgb_hex_rgb(0x1a_1c_20))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_CHECKED_BG),
        Some(Color::from_srgb_hex_rgb(0x4c_88_c7))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_CHECKED_FG),
        Some(Color::from_srgb_hex_rgb(0xe6_e8_eb))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CHECKBOX_RING),
        Some(Color::from_srgb_hex_rgb(0x6e_a8_e0))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::TEXT_FIELD_BG),
        Some(Color::from_srgb_hex_rgb(0x1a_1c_20))
    );
    assert_eq!(theme.metric_by_key("component.text_field.radius"), None);
    assert_eq!(theme.color_by_key("component.text_field.bg"), None);
    assert_eq!(
        theme.color_by_key("border"),
        Some(Color::from_srgb_hex_rgb(0x45_4d_59))
    );
    assert_eq!(
        theme.color_by_key("background"),
        Some(Color::from_srgb_hex_rgb(0x17_1a_1f))
    );
    assert_eq!(
        theme.color_by_key("input"),
        Some(Color::from_srgb_hex_rgb(0x4b_55_63))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_BG),
        Some(Color::from_srgb_hex_rgb(0x1d_21_27))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_BG),
        Some(Color::from_srgb_hex_rgb(0x36_41_4c))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_PANEL_HEADER_BORDER),
        Some(Color::from_srgb_hex_rgb(0x72_82_94))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_GROUP_BORDER),
        Some(Color::from_srgb_hex_rgb(0x47_51_5d))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_HEADER_BG),
        Some(Color::from_srgb_hex_rgb(0x28_30_39))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::PROPERTY_HEADER_BORDER),
        Some(Color::from_srgb_hex_rgb(0x56_62_6f))
    );
    assert_eq!(
        theme.color_by_key(EditorTokenKeys::CONTROL_INVALID_BG),
        Some(Color::from_srgb_hex_rgb(0x36_22_25))
    );
}

#[test]
fn default_preset_resets_dense_numeric_scrub_tokens() {
    let mut app = App::new();
    apply_editor_theme_preset_v1(&mut app, EditorThemePresetV1::ImguiLikeDense);
    assert_eq!(
        Theme::global(&app).metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_SPEED),
        Some(Px(0.035))
    );
    assert_eq!(
        Theme::global(&app).metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_DRAG_THRESHOLD),
        Some(Px(2.0))
    );

    apply_editor_theme_preset_v1(&mut app, EditorThemePresetV1::Default);
    assert_eq!(
        Theme::global(&app).metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_SPEED),
        Some(Px(0.02))
    );
    assert_eq!(
        Theme::global(&app).metric_by_key(EditorTokenKeys::NUMERIC_SCRUB_DRAG_THRESHOLD),
        Some(Px(4.0))
    );
}
