from __future__ import annotations

from pathlib import Path
from typing import Any, Callable


ADVANCED_HELPER_CONTEXT_POLICIES = [
    (
        'app_component_cx',
        'assets_demo.rs',
        [
            "fn render_view<'a, Cx>(cx: &mut Cx) -> Ui",
            "Cx: fret::app::RenderContextAccess<'a, KernelApp>",
            'let theme = cx.theme_snapshot();',
            'let cx = cx.elements();',
            'render_view(cx)',
            "fn assets_page<C>(cx: &mut AppComponentCx<'_>, theme: &ThemeSnapshot, card: C) -> Ui",
            'C: IntoUiElement<KernelApp>',
            'fn render_image_panel(',
            'theme: &ThemeSnapshot,',
            'stats: fret_ui_assets::image_asset_cache::ImageAssetStats,',
            ') -> impl IntoUiElement<KernelApp> + use<>',
            'fn render_svg_panel(',
            'svg: Option<fret_core::SvgId>,',
            ') -> impl IntoUiElement<KernelApp> + use<>',
        ],
        [
            "fn render_view(cx: &mut AppComponentCx<'_>) -> Ui",
            'render_view(cx.elements())',
            "fn assets_page<C>(cx: &mut AppComponentCx<'_>, theme: &Theme, card: C) -> Ui",
            "fn render_image_panel(cx: &mut AppComponentCx<'_>, theme: &Theme,",
            "fn render_svg_panel(cx: &mut AppComponentCx<'_>, theme: &Theme,",
            "fn render_image_panel(cx: &mut ElementContext<'_, KernelApp>,",
            "fn render_svg_panel(cx: &mut ElementContext<'_, KernelApp>,",
        ],
    ),
    (
        'app_component_cx',
        'genui_demo.rs',
        [
            "fn genui_page<L, R>(cx: &mut AppComponentCx<'_>, theme: ThemeSnapshot, left: L, right: R) -> Ui",
            'L: IntoUiElement<KernelApp>,',
            'R: IntoUiElement<KernelApp>,',
            'genui_page(cx, theme, left, right)',
        ],
        [
            'let page = ui::container(move |cx| {',
        ],
    ),
    (
        'app_component_cx',
        'imui_editor_proof_demo.rs',
        [
            "fn render_authoring_parity_surface(cx: &mut AppComponentCx<'_>,",
            "fn render_authoring_parity_shared_state(cx: &mut AppComponentCx<'_>,",
            "fn render_authoring_parity_declarative_group(cx: &mut AppComponentCx<'_>,",
            "fn render_authoring_parity_imui_group(cx: &mut AppComponentCx<'_>,",
        ],
        [
            "fn render_authoring_parity_surface(cx: &mut ElementContext<'_, KernelApp>,",
            "fn render_authoring_parity_shared_state(cx: &mut ElementContext<'_, KernelApp>,",
            "fn render_authoring_parity_declarative_group(cx: &mut ElementContext<'_, KernelApp>,",
            "fn render_authoring_parity_imui_group(cx: &mut ElementContext<'_, KernelApp>,",
        ],
    ),
    (
        'app_component_cx',
        'markdown_demo.rs',
        [
            "let spinner_box = |cx: &mut AppComponentCx<'_>|",
        ],
        [
            "let spinner_box = |cx: &mut fret_ui::ElementContext<'_, KernelApp>|",
        ],
    ),
    (
        'app_component_cx',
        'custom_effect_v1_demo.rs',
        [
            "fn watch_first_f32(cx: &mut AppComponentCx<'_>,",
            "fn stage(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, blur_radius_px: f32, blur_downsample: f32, refraction_height_px: f32, refraction_amount_px: f32, depth_effect: f32, chromatic_aberration: f32, corner_radius_px: f32, grain_strength: f32, grain_scale: f32,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn lens_row(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, blur_radius_px: f32, blur_downsample: f32, refraction_height_px: f32, refraction_amount_px: f32, depth_effect: f32, chromatic_aberration: f32, corner_radius_px: f32, grain_strength: f32, grain_scale: f32,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn inspector(cx: &mut AppComponentCx<'_>, st: &mut CustomEffectV1State, blur_radius_px: f32, blur_downsample: f32, refraction_height_px: f32, refraction_amount_px: f32, depth_effect: f32, chromatic_aberration: f32, corner_radius_px: f32, grain_strength: f32, grain_scale: f32,) -> impl IntoUiElement<KernelApp> + use<>",
            "let label_row = |cx: &mut AppComponentCx<'_>, label: &str, value: String|",
        ],
        [
            "fn watch_first_f32(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, blur_radius_px: f32, blur_downsample: f32, refraction_height_px: f32, refraction_amount_px: f32, depth_effect: f32, chromatic_aberration: f32, corner_radius_px: f32, grain_strength: f32, grain_scale: f32,) -> AnyElement",
            "fn lens_row(cx: &mut ElementContext<'_, KernelApp>,",
            "fn lens_row(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, blur_radius_px: f32, blur_downsample: f32, refraction_height_px: f32, refraction_amount_px: f32, depth_effect: f32, chromatic_aberration: f32, corner_radius_px: f32, grain_strength: f32, grain_scale: f32,) -> AnyElement",
            "fn inspector(cx: &mut ElementContext<'_, KernelApp>,",
            "fn inspector(cx: &mut AppComponentCx<'_>, st: &mut CustomEffectV1State, blur_radius_px: f32, blur_downsample: f32, refraction_height_px: f32, refraction_amount_px: f32, depth_effect: f32, chromatic_aberration: f32, corner_radius_px: f32, grain_strength: f32, grain_scale: f32,) -> AnyElement",
            "let label_row = |cx: &mut ElementContext<'_, KernelApp>, label: &str, value: String|",
        ],
    ),
    (
        'app_component_cx',
        'custom_effect_v2_demo.rs',
        [
            "fn watch_first_f32(cx: &mut AppComponentCx<'_>,",
            "fn stage(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, input_image: Option<ImageId>, sampling: ImageSamplingHint, uv_span: f32, input_strength: f32, rim_strength: f32, blur_radius_px: f32, debug_input: bool,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn lens_row(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, input_image: Option<ImageId>, sampling: ImageSamplingHint, uv_span: f32, input_strength: f32, rim_strength: f32, blur_radius_px: f32, debug_input: bool,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn inspector(cx: &mut AppComponentCx<'_>, st: &mut CustomEffectV2State, sampling_value: &str, uv_span: f32, input_strength: f32, rim_strength: f32, blur_radius_px: f32,) -> impl IntoUiElement<KernelApp> + use<>",
            "let label_row = |cx: &mut AppComponentCx<'_>, label: &str, value: String|",
        ],
        [
            "fn watch_first_f32(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, input_image: Option<ImageId>, sampling: ImageSamplingHint, uv_span: f32, input_strength: f32, rim_strength: f32, blur_radius_px: f32, debug_input: bool,) -> AnyElement",
            "fn lens_row(cx: &mut ElementContext<'_, KernelApp>,",
            "fn lens_row(cx: &mut AppComponentCx<'_>, enabled: bool, effect: EffectId, input_image: Option<ImageId>, sampling: ImageSamplingHint, uv_span: f32, input_strength: f32, rim_strength: f32, blur_radius_px: f32, debug_input: bool,) -> AnyElement",
            "fn inspector(cx: &mut ElementContext<'_, KernelApp>,",
            "fn inspector(cx: &mut AppComponentCx<'_>, st: &mut CustomEffectV2State, sampling_value: &str, uv_span: f32, input_strength: f32, rim_strength: f32, blur_radius_px: f32,) -> AnyElement",
            "let label_row = |cx: &mut ElementContext<'_, KernelApp>, label: &str, value: String|",
        ],
    ),
    (
        'app_component_cx',
        'custom_effect_v3_demo.rs',
        [
            "fn stage(cx: &mut AppComponentCx<'_>, st: &mut State, enabled: bool, show_user0_probe: bool, use_non_filterable_user0: bool, lens_effect: EffectId, user0_probe_effect: Option<EffectId>, show_user1_probe: bool, use_non_filterable_user1: bool, user1_probe_effect: Option<EffectId>, user01_probe_effect: Option<EffectId>, user0_image: Option<ImageId>, user1_image: Option<ImageId>,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn stage_controls(cx: &mut AppComponentCx<'_>, st: &mut State, enabled: bool, show_user0_probe: bool, show_user1_probe: bool, use_non_filterable_user0: bool, use_non_filterable_user1: bool,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn animated_backdrop(cx: &mut AppComponentCx<'_>) -> impl IntoUiElement<KernelApp> + use<>",
            "fn lens_row(cx: &mut AppComponentCx<'_>, enabled: bool, show_user0_probe: bool, lens_effect: EffectId, user0_probe_effect: Option<EffectId>, show_user1_probe: bool, user1_probe_effect: Option<EffectId>, user01_probe_effect: Option<EffectId>, user0_image: Option<ImageId>, user1_image: Option<ImageId>,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn lens_shell(cx: &mut AppComponentCx<'_>, title: &'static str, radius: Px, lens_w: Px, lens_h: Px, with_effect: Option<EffectChain>,) -> impl IntoUiElement<KernelApp> + use<>",
            "fn custom_effect_user01_probe_lens(cx: &mut AppComponentCx<'_>,",
        ],
        [
            "fn stage(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage(cx: &mut AppComponentCx<'_>, st: &mut State, enabled: bool, show_user0_probe: bool, use_non_filterable_user0: bool, lens_effect: EffectId, user0_probe_effect: Option<EffectId>, show_user1_probe: bool, use_non_filterable_user1: bool, user1_probe_effect: Option<EffectId>, user01_probe_effect: Option<EffectId>, user0_image: Option<ImageId>, user1_image: Option<ImageId>,) -> AnyElement",
            "fn stage_controls(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage_controls(cx: &mut AppComponentCx<'_>, st: &mut State, enabled: bool, show_user0_probe: bool, show_user1_probe: bool, use_non_filterable_user0: bool, use_non_filterable_user1: bool,) -> AnyElement",
            "fn animated_backdrop(cx: &mut ElementContext<'_, KernelApp>) -> AnyElement",
            "fn animated_backdrop(cx: &mut AppComponentCx<'_>) -> AnyElement",
            "fn lens_row(cx: &mut ElementContext<'_, KernelApp>,",
            "fn lens_row(cx: &mut AppComponentCx<'_>, enabled: bool, show_user0_probe: bool, lens_effect: EffectId, user0_probe_effect: Option<EffectId>, show_user1_probe: bool, user1_probe_effect: Option<EffectId>, user01_probe_effect: Option<EffectId>, user0_image: Option<ImageId>, user1_image: Option<ImageId>,) -> AnyElement",
            "fn lens_shell(cx: &mut ElementContext<'_, KernelApp>,",
            "fn lens_shell(cx: &mut AppComponentCx<'_>, title: &'static str, radius: Px, lens_w: Px, lens_h: Px, with_effect: Option<EffectChain>,) -> AnyElement",
            "fn custom_effect_user01_probe_lens(cx: &mut ElementContext<'_, KernelApp>,",
        ],
    ),
    (
        'advanced_generic',
        'custom_effect_v3_demo.rs',
        [
            'fn plain_lens(',
            'lens_h: Px,',
            ') -> impl IntoUiElement<KernelApp> + use<>',
            'fn custom_effect_lens(',
            'effect: EffectId,',
            'fn custom_effect_user0_probe_lens(',
            'user0_image: ImageId,',
            'fn custom_effect_user1_probe_lens(',
            'user1_image: ImageId,',
            'fn custom_effect_user01_probe_lens(',
            'user0_image: ImageId,',
            'user1_image: ImageId,',
        ],
        [
            "fn plain_lens(cx: &mut AppComponentCx<'_>, title: &'static str, radius: Px, lens_w: Px, lens_h: Px) -> AnyElement",
            "fn custom_effect_lens(cx: &mut AppComponentCx<'_>, title: &'static str, effect: EffectId, radius: Px, lens_w: Px, lens_h: Px) -> AnyElement",
            "fn custom_effect_user0_probe_lens(cx: &mut AppComponentCx<'_>, title: &'static str, effect: EffectId, user0_image: ImageId, radius: Px, lens_w: Px, lens_h: Px) -> AnyElement",
            "fn custom_effect_user1_probe_lens(cx: &mut AppComponentCx<'_>, title: &'static str, effect: EffectId, user1_image: ImageId, radius: Px, lens_w: Px, lens_h: Px) -> AnyElement",
            "fn custom_effect_user01_probe_lens(cx: &mut AppComponentCx<'_>, title: &'static str, effect: EffectId, user0_image: ImageId, user1_image: ImageId, radius: Px, lens_w: Px, lens_h: Px) -> AnyElement",
        ],
    ),
    (
        'app_component_cx',
        'liquid_glass_demo.rs',
        [
            "fn watch_first_f32(cx: &mut AppComponentCx<'_>,",
            "let mk_card = |cx: &mut AppComponentCx<'_>,",
            "|cx: &mut AppComponentCx<'_>, label: &str, value: String|",
        ],
        [
            "fn watch_first_f32(cx: &mut ElementContext<'_, KernelApp>,",
            "let mk_card = |cx: &mut ElementContext<'_, KernelApp>,",
            "|cx: &mut ElementContext<'_, KernelApp>, label: &str, value: String|",
        ],
    ),
    (
        'app_component_cx',
        'postprocess_theme_demo.rs',
        [
            "fn watch_first_f32(cx: &mut AppComponentCx<'_>,",
            "fn inspector(cx: &mut AppComponentCx<'_>, st: &mut ThemePostprocessState, theme: &str, chromatic_offset_px: f32, scanline_strength: f32, scanline_spacing_px: f32, vignette_strength: f32, grain_strength: f32, grain_scale: f32, retro_pixel_scale: f32, retro_dither: bool,) -> impl IntoUiElement<KernelApp> + use<>",
            "let label_row = |cx: &mut AppComponentCx<'_>, label: &str, value: String|",
            "fn stage(cx: &mut AppComponentCx<'_>, enabled: bool, compare: bool, theme: &str, effect: EffectId, chromatic_offset_px: f32, scanline_strength: f32, scanline_spacing_px: f32, vignette_strength: f32, grain_strength: f32, grain_scale: f32, retro_pixel_scale: f32, retro_dither: bool,) -> impl IntoUiElement<KernelApp> + use<>",
            'fn stage_body(',
            'postprocess_applied: bool,',
            'label: &str,',
            "fn stage_cards(cx: &mut AppComponentCx<'_>) -> impl IntoUiElement<KernelApp> + use<>",
            "let card = |cx: &mut AppComponentCx<'_>, title: &str, subtitle: &str|",
        ],
        [
            "fn watch_first_f32(cx: &mut ElementContext<'_, KernelApp>,",
            "fn inspector(cx: &mut ElementContext<'_, KernelApp>,",
            "fn inspector(cx: &mut AppComponentCx<'_>, st: &mut ThemePostprocessState, theme: &str, chromatic_offset_px: f32, scanline_strength: f32, scanline_spacing_px: f32, vignette_strength: f32, grain_strength: f32, grain_scale: f32, retro_pixel_scale: f32, retro_dither: bool,) -> AnyElement",
            "let label_row = |cx: &mut ElementContext<'_, KernelApp>, label: &str, value: String|",
            "fn stage(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage(cx: &mut AppComponentCx<'_>, enabled: bool, compare: bool, theme: &str, effect: EffectId, chromatic_offset_px: f32, scanline_strength: f32, scanline_spacing_px: f32, vignette_strength: f32, grain_strength: f32, grain_scale: f32, retro_pixel_scale: f32, retro_dither: bool,) -> AnyElement",
            "fn stage_body(cx: &mut AppComponentCx<'_>, postprocess_applied: bool, label: &str) -> AnyElement",
            "fn stage_cards(cx: &mut AppComponentCx<'_>) -> AnyElement",
            "fn stage_body(cx: &mut ElementContext<'_, KernelApp>,",
            "fn stage_cards(cx: &mut ElementContext<'_, KernelApp>) -> AnyElement",
            "let card = |cx: &mut ElementContext<'_, KernelApp>, title: &str, subtitle: &str|",
        ],
    ),
    (
        'app_render_context',
        'async_playground_demo.rs',
        [
            'use fret::app::{AppRenderContext, RenderContextAccess as _};',
            'use fret_ui_kit::IntoUiElementInExt as _;',
            "fn header_bar<'a, Cx>(",
            "fn body<'a, Cx>(",
            "fn catalog_panel<'a, Cx>(",
            "fn catalog_item<'a, Cx>(",
            "fn main_panel<'a, Cx>(",
            "fn inspector_panel<'a, Cx>(",
            "fn policy_editor<'a, Cx>(",
            "fn query_panel_for_mode<'a, Cx>(",
            "fn query_inputs_row<'a, Cx>(",
            "fn query_result_view<'a, Cx>(",
            "fn active_mode<'a, Cx>(",
            "fn query_policy<'a, Cx>(",
            "fn query_fail_mode<'a, Cx>(",
            "fn tracked_query_inputs<'a, Cx>(",
            "fn query_key_for_id<'a, Cx>(",
            "fn status_badge<'a, Cx>(",
            "fn snapshot_entry_for_key<'a, Cx>(",
            "Cx: AppRenderContext<'a>,",
            'cx.elements().pressable(',
            'let state = handle.read_layout(cx);',
        ],
        [
            "fn header_bar(cx: &mut AppComponentCx<'_>,",
            "fn body(cx: &mut AppComponentCx<'_>,",
            "fn catalog_panel(cx: &mut AppComponentCx<'_>,",
            "fn catalog_item(cx: &mut AppComponentCx<'_>,",
            "fn main_panel(cx: &mut AppComponentCx<'_>,",
            "fn inspector_panel(cx: &mut AppComponentCx<'_>,",
            "fn policy_editor(cx: &mut AppComponentCx<'_>,",
            "fn query_panel_for_mode(cx: &mut AppComponentCx<'_>,",
            "fn query_inputs_row(cx: &mut AppComponentCx<'_>,",
            "fn query_result_view(cx: &mut AppComponentCx<'_>,",
            "fn active_mode(cx: &mut AppComponentCx<'_>,",
            "fn query_policy(cx: &mut AppComponentCx<'_>,",
            "fn query_fail_mode(cx: &mut AppComponentCx<'_>,",
            "fn tracked_query_inputs(cx: &mut AppComponentCx<'_>,",
            "fn query_key_for_id(cx: &mut AppComponentCx<'_>,",
            "fn status_badge(cx: &mut AppComponentCx<'_>,",
            "fn snapshot_entry_for_key(cx: &mut AppComponentCx<'_>,",
            'handle.layout_query(cx).value_or_default()',
        ],
    ),
    (
        'advanced_generic',
        'custom_effect_v1_demo.rs',
        [
            'fn lens_shell<B>(',
            'body: B,',
            ') -> impl IntoUiElement<KernelApp> + use<B>',
            'B: IntoUiElement<KernelApp>,',
            'body.into_element(cx)',
            'fn plain_lens<L>(',
            'label: L,',
            'radius: Px',
            ') -> impl IntoUiElement<KernelApp> + use<L>',
            'fn custom_effect_lens<L>(',
            'grain_scale: f32,',
            ') -> impl IntoUiElement<KernelApp> + use<L>',
        ],
        [
            "fn lens_shell(cx: &mut AppComponentCx<'_>, label: Arc<str>, radius: Px, body: AnyElement) -> AnyElement",
            "fn plain_lens(cx: &mut AppComponentCx<'_>, label: impl Into<Arc<str>>, radius: Px) -> AnyElement",
            "fn custom_effect_lens(cx: &mut AppComponentCx<'_>, label: impl Into<Arc<str>>, effect: EffectId, blur_radius_px: f32, blur_downsample: f32, refraction_height_px: f32, refraction_amount_px: f32, depth_effect: f32, chromatic_aberration: f32, corner_radius_px: f32, grain_strength: f32, grain_scale: f32) -> AnyElement",
        ],
    ),
    (
        'advanced_generic',
        'custom_effect_v2_demo.rs',
        [
            'fn lens_shell<B>(',
            'body: B,',
            ') -> impl IntoUiElement<KernelApp> + use<B>',
            'B: IntoUiElement<KernelApp>,',
            'body.into_element(cx)',
            'fn plain_lens<L>(',
            'label: L,',
            'radius: Px',
            ') -> impl IntoUiElement<KernelApp> + use<L>',
            'fn custom_effect_lens<L>(',
            'debug_input: bool,',
            ') -> impl IntoUiElement<KernelApp> + use<L>',
        ],
        [
            "fn lens_shell(cx: &mut AppComponentCx<'_>, label: Arc<str>, radius: Px, body: AnyElement) -> AnyElement",
            "fn plain_lens(cx: &mut AppComponentCx<'_>, label: impl Into<Arc<str>>, radius: Px) -> AnyElement",
            "fn custom_effect_lens(cx: &mut AppComponentCx<'_>, label: impl Into<Arc<str>>, effect: EffectId, input_image: Option<ImageId>, sampling: ImageSamplingHint, uv_span: f32, input_strength: f32, rim_strength: f32, blur_radius_px: f32, debug_input: bool) -> AnyElement",
        ],
    ),
    (
        'advanced_generic',
        'drop_shadow_demo.rs',
        [
            'fn card<H: UiHost>(',
            'title: Arc<str>,',
            'subtitle: Arc<str>,',
            'enabled: bool',
            ') -> impl IntoUiElement<H> + use<H>',
        ],
        [
            "fn card<H: UiHost>(cx: &mut ElementContext<'_, H>, title: Arc<str>, subtitle: Arc<str>, enabled: bool) -> AnyElement",
        ],
    ),
    (
        'advanced_generic',
        'markdown_demo.rs',
        [
            'fn render_image_placeholder<H: fret_ui::UiHost>(',
            'theme: fret_ui::ThemeSnapshot,',
            'on_link_activate: Option<markdown::OnLinkActivate>,',
            'link: markdown::LinkInfo,',
            ') -> impl IntoUiElement<H> + use<H>',
        ],
        [
            "fn render_image_placeholder<H: fret_ui::UiHost>(cx: &mut fret_ui::ElementContext<'_, H>, theme: fret_ui::ThemeSnapshot, on_link_activate: Option<markdown::OnLinkActivate>, link: markdown::LinkInfo) -> AnyElement",
        ],
    ),
    (
        'advanced_generic',
        'liquid_glass_demo.rs',
        [
            'fn lens_panel<H: UiHost>(',
            'label: Arc<str>,',
            'radius: Px,',
            'mode: EffectMode,',
            'chain: EffectChain,',
            ') -> impl IntoUiElement<H> + use<H>',
        ],
        [
            "fn lens_panel<H: UiHost>(cx: &mut ElementContext<'_, H>, label: Arc<str>, radius: Px, mode: EffectMode, chain: EffectChain) -> AnyElement",
        ],
    ),
    (
        'default_app_generic',
        'custom_effect_v2_identity_web_demo.rs',
        [
            'fn stage_tile(',
            ') -> impl IntoUiElement<App> + use<>',
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2IdentityWebViewSettings,) -> impl IntoUiElement<App> + use<>",
            "fn inspector(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2IdentityWebViewSettings,) -> impl IntoUiElement<App> + use<>",
            'items.push(Self::stage_tile(',
            '.into_element(cx),',
            'let view_settings = Self::view_settings(cx, &controls);',
            'let inspector = Self::inspector(cx, &controls, &inspector_settings).into_element(cx);',
            'Self::lens(cx, &stage_settings).into_element(cx)',
        ],
        [
            "fn stage_tile(cx: &mut ElementContext<'_, App>, color: fret_core::Color, left: Px, top: Px, w: Px, h: Px, corner_radius_px: Px,) -> AnyElement",
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2IdentityWebViewSettings) -> AnyElement",
            "fn inspector(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2IdentityWebViewSettings) -> AnyElement",
        ],
    ),
    (
        'default_app_generic',
        'custom_effect_v2_web_demo.rs',
        [
            'fn stage_tile(',
            ') -> impl IntoUiElement<App> + use<>',
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2WebViewSettings,) -> impl IntoUiElement<App> + use<>",
            "fn inspector(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2WebViewSettings,) -> impl IntoUiElement<App> + use<>",
            'items.push(Self::stage_tile(',
            '.into_element(cx),',
            'let view_settings = Self::view_settings(cx, &controls);',
            'let inspector = Self::inspector(cx, &controls, &inspector_settings).into_element(cx);',
            'Self::lens(cx, &stage_settings).into_element(cx)',
        ],
        [
            "fn stage_tile(cx: &mut ElementContext<'_, App>, color: fret_core::Color, left: Px, top: Px, w: Px, h: Px, corner_radius_px: Px,) -> AnyElement",
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2WebViewSettings) -> AnyElement",
            "fn inspector(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2WebViewSettings) -> AnyElement",
        ],
    ),
    (
        'default_app_generic',
        'custom_effect_v2_lut_web_demo.rs',
        [
            'fn stage_tile(',
            ') -> impl IntoUiElement<App> + use<>',
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2LutWebViewSettings,) -> impl IntoUiElement<App> + use<>",
            "fn inspector(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2LutWebViewSettings,) -> impl IntoUiElement<App> + use<>",
            'items.push(Self::stage_tile(',
            '.into_element(cx),',
            'let view_settings = Self::view_settings(cx, &controls);',
            'let inspector = Self::inspector(cx, &controls, &inspector_settings).into_element(cx);',
            'Self::lens(cx, &stage_settings).into_element(cx)',
        ],
        [
            "fn stage_tile(cx: &mut ElementContext<'_, App>, color: fret_core::Color, left: Px, top: Px, w: Px, h: Px, corner_radius_px: Px,) -> AnyElement",
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2LutWebViewSettings) -> AnyElement",
            "fn inspector(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2LutWebViewSettings) -> AnyElement",
        ],
    ),
    (
        'default_app_generic',
        'custom_effect_v2_glass_chrome_web_demo.rs',
        [
            "fn label_row(cx: &mut ElementContext<'_, App>, label: &str, value: String,) -> impl IntoUiElement<App> + use<>",
            'fn stage_tile(',
            ') -> impl IntoUiElement<App> + use<>',
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2GlassChromeWebViewSettings,) -> impl IntoUiElement<App> + use<>",
            "fn controls_panel(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2GlassChromeWebViewSettings,) -> impl IntoUiElement<App> + use<>",
            'Self::label_row(cx, "Uv span", format!("{uv_span:.2}")).into_element(cx)',
            'items.push(Self::stage_tile(',
            '.into_element(cx),',
            'let view_settings = Self::view_settings(cx, &controls);',
            'let inspector = Self::controls_panel(cx, &controls, &inspector_settings).into_element(cx);',
            'items.push(Self::lens(cx, &stage_settings).into_element(cx));',
        ],
        [
            "fn label_row(cx: &mut ElementContext<'_, App>, label: &str, value: String) -> AnyElement",
            "fn stage_tile(cx: &mut ElementContext<'_, App>, color: fret_core::Color, left: Px, top: Px, w: Px, h: Px, corner_radius_px: Px,) -> AnyElement",
            "fn lens(cx: &mut ElementContext<'_, App>, view_settings: &CustomEffectV2GlassChromeWebViewSettings) -> AnyElement",
            "fn controls_panel(cx: &mut ElementContext<'_, App>, controls: &DemoControls, view_settings: &CustomEffectV2GlassChromeWebViewSettings) -> AnyElement",
        ],
    ),
]


CheckMarkers = Callable[..., None]
ReadSource = Callable[[Path], str]


def check_advanced_helper_context_source_policies(
    failures: list[Any],
    *,
    examples_src: Path,
    read_source: ReadSource,
    check_required_forbidden_markers: CheckMarkers,
) -> None:
    for kind, source_name, required, forbidden in ADVANCED_HELPER_CONTEXT_POLICIES:
        path = examples_src / source_name
        required_markers = list(required)
        forbidden_markers = list(forbidden)
        if kind == "app_render_context":
            required_markers.append("AppRenderContext<'a>")
        elif kind == "default_app_generic":
            required_markers.append("ElementContext<'_, App>")
            forbidden_markers.append("KernelApp")

        check_required_forbidden_markers(
            path,
            read_source(path),
            required=required_markers,
            forbidden=forbidden_markers,
            failures=failures,
        )
