from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Callable


SELECTED_GROUPED_STATE_POLICIES = [
    (
        '../../fret-examples-imui/src/imui_hello_demo.rs',
        [
            'let count_state = cx.state().local_init(|| 0u32);',
            'let enabled_state = cx.state().local_init(|| false);',
            'let count = count_state.layout_value(cx);',
            'let enabled = enabled_state.paint_value(cx);',
        ],
        [
            'cx.use_local_with(|| 0u32)',
            'cx.use_local_with(|| false)',
            'count_state.layout(cx).value_or_default()',
            'enabled_state.paint(cx).value_or_default()',
        ],
    ),
    (
        'drop_shadow_demo.rs',
        [
            'let enabled_state = cx.state().local_init(|| false);',
            'let stress_state = cx.state().local_init(|| false);',
            'let enabled = enabled_state.layout_value(cx);',
            'let stress = stress_state.layout_value(cx);',
            'shadcn::Switch::new(&enabled_state)',
            'shadcn::Switch::new(&stress_state)',
        ],
        [
            'enabled: app.models_mut().insert(false)',
            'stress: app.models_mut().insert(false)',
            'self.st.enabled.layout(cx).value_or_default()',
            'self.st.stress.layout(cx).value_or_default()',
            'enabled_state.clone_model()',
            'stress_state.clone_model()',
        ],
    ),
    (
        '../../fret-examples-imui/src/imui_floating_windows_demo.rs',
        [
            'let open_a_state = cx.state().local_init(|| true);',
            'let select_mode_state = cx.state().local_init(|| None::<Arc<str>>);',
            'let a_overlap_clicked_state = cx.state().local_init(|| false);',
            '"Window A",',
            '.with_open(open_a_state.model())',
            'let clicked = a_overlap_clicked_state.paint_value_in(cx);',
            '"Mode",',
            'select_mode_state.model(),',
        ],
        [
            'open_a: app.models_mut().insert(true)',
            'select_mode: app.models_mut().insert(None::<Arc<str>>)',
            'a_overlap_clicked: app.models_mut().insert(false)',
            'let clicked = a_overlap_clicked_state.paint_in(cx).value_or(false);',
            '&self.open_a',
            'read_model(',
            '&self.a_overlap_clicked',
            '&self.select_mode',
        ],
    ),
    (
        '../../fret-examples-imui/src/imui_shadcn_adapter_demo.rs',
        [
            'let count_state = cx.state().local_init(|| 0u32);',
            'let enabled_state = cx.state().local_init(|| false);',
            'let value_state = cx.state().local_init(|| 32.0f32);',
            'let mode_state = cx.state().local_init(|| None::<Arc<str>>);',
            'let draft_state = cx.state().local_init(String::new);',
            'let count = count_state.layout_value(cx);',
            'let enabled = enabled_state.paint_value(cx);',
            'let value = value_state.paint_value(cx);',
            'let mode = mode_state.paint_value(cx);',
            'let draft = draft_state.paint_value(cx);',
            'let _ = ui.switch_model_with_options("Enabled (switch)", enabled_state.model(),',
        ],
        [
            'count: app.models_mut().insert(0)',
            'enabled: app.models_mut().insert(false)',
            'value: app.models_mut().insert(32.0)',
            'mode: app.models_mut().insert(None::<Arc<str>>)',
            'draft: app.models_mut().insert(String::new())',
            'let count = self.count.layout(cx).value_or_default();',
            'let enabled = self.enabled.paint(cx).value_or_default();',
        ],
    ),
    (
        'async_playground_demo.rs',
        [
            'use fret::app::{AppRenderContext, RenderContextAccess as _};',
            'value: LocalState::new_in(app.models_mut(), initial.map(Arc::from)),',
            'open: LocalState::new_in(app.models_mut(), false),',
            'stale_time_s: LocalState::new_in(app.models_mut(), "2".to_string()),',
            'cache_time_s: LocalState::new_in(app.models_mut(), "30".to_string()),',
            'keep_prev: LocalState::new_in(app.models_mut(), true),',
            'fail_mode: LocalState::new_in(app.models_mut(), false),',
            'selected: cx.state().local_init(|| QueryId::Tip),',
            'dark: cx.state().local_init(|| false),',
            'global_slow: cx.state().local_init(|| false),',
            'tabs: cx.state().local_init(|| Some(Arc::<str>::from("async"))),',
            'search_input: cx.state().local_init(|| "react".to_string()),',
            'stock_symbol: cx.state().local_init(|| "FRET".to_string()),',
            'let selected = locals.selected.layout_value(cx);',
            'let dark = locals.dark.layout_value(cx);',
            'let global_slow = locals.global_slow.layout_value(cx);',
            'let theme = cx.theme_snapshot();',
            'let namespace_input = locals.namespace_input.layout_value(cx);',
            '.locals_with((&locals.selected, &locals.namespace_input))',
            'cx.actions().local(&locals.dark)',
            '.toggle_bool::<act::ToggleTheme>();',
            'shadcn::Switch::new(&locals.global_slow)',
            'shadcn::Tabs::new(&locals.tabs)',
            'shadcn::Switch::new(&config.keep_prev)',
            'shadcn::Switch::new(&config.fail_mode)',
            'shadcn::Select::new(&config.cancel_mode.value, &config.cancel_mode.open)',
            'shadcn::Input::new(&locals.namespace_input)',
            'shadcn::Input::new(&locals.search_input)',
            'shadcn::Input::new(&locals.stock_symbol)',
            'if cx.effects().take_transient(TRANSIENT_INVALIDATE_SELECTED)',
            'cx.actions().transient::<act::InvalidateSelected>(TRANSIENT_INVALIDATE_SELECTED);',
        ],
        [
            'selected: app.models_mut().insert(QueryId::Tip)',
            'dark: app.models_mut().insert(false)',
            'global_slow: app.models_mut().insert(false)',
            'tabs: app.models_mut().insert(Some(Arc::<str>::from("async")))',
            'namespace_input: app.models_mut().insert("tip".to_string())',
            'search_input: app.models_mut().insert("react".to_string())',
            'stock_symbol: app.models_mut().insert("FRET".to_string())',
            'LocalState::from_model(app.models_mut().insert(',
            'cx.take_transient_on_action_root(TRANSIENT_INVALIDATE_SELECTED)',
            'cx.on_action_notify_models::<act::SelectTip>',
            'cx.actions().models::<act::SelectTip>({',
            'cx.actions().models::<act::ToggleTheme>({',
            'cx.on_action_notify_transient::<act::InvalidateSelected>',
            'shadcn::Switch::new(locals.global_slow.clone_model())',
            'shadcn::Tabs::new(locals.tabs.clone_model())',
            'shadcn::Switch::new(config.keep_prev.clone_model())',
            'shadcn::Switch::new(config.fail_mode.clone_model())',
            'Theme::global(&*cx.app).snapshot()',
            'config.cancel_mode.open.clone_model()',
        ],
    ),
    (
        'embedded_viewport_demo.rs',
        [
            'let theme = cx.theme_snapshot();',
            "fn embedded_viewport_page<'a, Cx, C>(",
            "Cx: fret::app::ElementContextAccess<'a, KernelApp>",
            'let cx = cx.elements();',
            'embedded_viewport_page(cx, theme, viewport_card, diag_enabled())',
        ],
        [
            'embedded_viewport_page(cx.elements(), theme, viewport_card, diag_enabled())',
        ],
    ),
    (
        'editor_notes_demo.rs',
        [
            'let theme = cx.theme_snapshot();',
            "fn selection_button<'a, Cx>(",
            "Cx: fret::app::ElementContextAccess<'a, App>,",
            '.into_element_in(cx)',
            "fn render_inspector_panel<'a, Cx>(",
            '.into_element_in(cx,',
            'let (name_value, committed_notes, notes_outcome, summary_status) = cx.data().selector_model_paint(',
            '(&asset.name_model, &asset.notes_model, &asset.notes_outcome_model, &asset.summary_status_model,)',
        ],
        [
            "fn selection_button(cx: &mut AppUi<'_, '_>,",
            "fn render_inspector_panel(cx: &mut AppUi<'_, '_>,",
            '.watch_model(&asset.notes_model)',
            '.watch_model(&asset.notes_outcome_model)',
            'Theme::global(&*cx.app).snapshot()',
        ],
    ),
    (
        'image_heavy_memory_demo.rs',
        [
            "fn render_view<'a, Cx>(cx: &mut Cx) -> Ui",
            "Cx: fret::app::ElementContextAccess<'a, KernelApp>",
            'let cx = cx.elements();',
            'render_view(cx)',
        ],
        [
            "fn render_view(cx: &mut AppComponentCx<'_>) -> Ui",
            'render_view(cx.elements())',
        ],
    ),
    (
        'custom_effect_v1_demo.rs',
        [
            'enabled: cx.state().local_init(|| true),',
            'blur_radius_px: cx.state().local_init(|| vec![14.0]),',
            'blur_downsample: cx.state().local_init(|| vec![2.0]),',
            'refraction_height_px: cx.state().local_init(|| vec![20.0]),',
            'refraction_amount_px: cx.state().local_init(|| vec![12.0]),',
            'depth_effect: cx.state().local_init(|| vec![0.35]),',
            'chromatic_aberration: cx.state().local_init(|| vec![0.75]),',
            'corner_radius_px: cx.state().local_init(|| vec![20.0]),',
            'grain_strength: cx.state().local_init(|| vec![0.06]),',
            'grain_scale: cx.state().local_init(|| vec![1.0]),',
            'cx.actions().local(&st.enabled).set::<act::Reset>(true);',
            '.local(&st.blur_radius_px)',
            '.set::<act::Reset>(vec![14.0]);',
            '.local(&st.grain_scale)',
            '.set::<act::Reset>(vec![1.0]);',
        ],
        [
            'enabled: app.models_mut().insert(true)',
            'blur_radius_px: app.models_mut().insert(vec![14.0])',
            'blur_downsample: app.models_mut().insert(vec![2.0])',
            'refraction_height_px: app.models_mut().insert(vec![20.0])',
            'refraction_amount_px: app.models_mut().insert(vec![12.0])',
            'depth_effect: app.models_mut().insert(vec![0.35])',
            'chromatic_aberration: app.models_mut().insert(vec![0.75])',
            'corner_radius_px: app.models_mut().insert(vec![20.0])',
            'grain_strength: app.models_mut().insert(vec![0.06])',
            'grain_scale: app.models_mut().insert(vec![1.0])',
            'cx.actions().models::<act::Reset>({',
            'cx.on_action_notify_models::<act::Reset>',
        ],
    ),
    (
        'custom_effect_v2_demo.rs',
        [
            'enabled: cx.state().local_init(|| true),',
            'use_non_filterable_input: cx.state().local_init(|| false),',
            'sampling: cx.state().local_init(|| Some(Arc::<str>::from("linear"))),',
            'sampling_open: cx.state().local_init(|| false),',
            'uv_span: cx.state().local_init(|| vec![0.25]),',
            'input_strength: cx.state().local_init(|| vec![0.35]),',
            'rim_strength: cx.state().local_init(|| vec![0.65]),',
            'blur_radius_px: cx.state().local_init(|| vec![10.0]),',
            'debug_input: cx.state().local_init(|| false),',
            'cx.actions().local(&st.enabled).set::<act::Reset>(true);',
            '.local(&st.use_non_filterable_input)',
            '.set::<act::Reset>(false);',
            '.local(&st.sampling)',
            '.set::<act::Reset>(Some(Arc::<str>::from("linear")));',
            '.local(&st.blur_radius_px)',
            '.set::<act::Reset>(vec![10.0]);',
            'cx.actions().local(&st.debug_input).set::<act::Reset>(false);',
        ],
        [
            'enabled: app.models_mut().insert(true)',
            'use_non_filterable_input: app.models_mut().insert(false)',
            'sampling: app.models_mut().insert(Some(Arc::from("linear")))',
            'sampling_open: app.models_mut().insert(false)',
            'uv_span: app.models_mut().insert(vec![0.25])',
            'input_strength: app.models_mut().insert(vec![0.35])',
            'rim_strength: app.models_mut().insert(vec![0.65])',
            'blur_radius_px: app.models_mut().insert(vec![10.0])',
            'debug_input: app.models_mut().insert(false)',
            'cx.actions().models::<act::Reset>({',
            'cx.on_action_notify_models::<act::Reset>',
        ],
    ),
    (
        'custom_effect_v3_demo.rs',
        [
            'enabled: cx.state().local_init(|| true),',
            'show_user0_probe: cx.state().local_init(|| false),',
            'show_user1_probe: cx.state().local_init(|| false),',
            'use_non_filterable_user0: cx.state().local_init(|| false),',
            'use_non_filterable_user1: cx.state().local_init(|| false),',
            'cx.actions().local(&st.enabled).set::<act::Reset>(true);',
            '.local(&st.show_user0_probe)',
            '.set::<act::Reset>(false);',
            '.local(&st.show_user1_probe)',
            '.local(&st.use_non_filterable_user0)',
            '.local(&st.use_non_filterable_user1)',
        ],
        [
            'enabled: app.models_mut().insert(true)',
            'show_user0_probe: app.models_mut().insert(false)',
            'show_user1_probe: app.models_mut().insert(false)',
            'use_non_filterable_user0: app.models_mut().insert(false)',
            'use_non_filterable_user1: app.models_mut().insert(false)',
            'cx.actions().models::<act::Reset>({',
            'cx.on_action_notify_models::<act::Reset>',
        ],
    ),
    (
        'postprocess_theme_demo.rs',
        [
            'enabled: cx.state().local_init(|| true),',
            'compare: cx.state().local_init(|| true),',
            'theme: cx',
            '.local_init(|| Option::<Arc<str>>::Some(Arc::from("cyberpunk"))),',
            'theme_open: cx.state().local_init(|| false),',
            'chromatic_offset_px: cx.state().local_init(|| vec![4.0]),',
            'scanline_strength: cx.state().local_init(|| vec![0.32]),',
            'scanline_spacing_px: cx.state().local_init(|| vec![3.0]),',
            'vignette_strength: cx.state().local_init(|| vec![0.6]),',
            'grain_strength: cx.state().local_init(|| vec![0.12]),',
            'grain_scale: cx.state().local_init(|| vec![1.5]),',
            'retro_pixel_scale: cx.state().local_init(|| vec![10.0]),',
            'retro_dither: cx.state().local_init(|| true),',
            'cx.actions().local(&st.enabled).set::<act::Reset>(true);',
            '.local(&st.theme)',
            '.set::<act::Reset>(Some(Arc::<str>::from("cyberpunk")));',
            '.local(&st.chromatic_offset_px)',
            '.set::<act::Reset>(vec![4.0]);',
            'cx.actions().local(&st.retro_dither).set::<act::Reset>(true);',
        ],
        [
            'enabled: app.models_mut().insert(true)',
            'compare: app.models_mut().insert(true)',
            '.insert(Option::<Arc<str>>::Some(Arc::from("cyberpunk")))',
            'theme_open: app.models_mut().insert(false)',
            'chromatic_offset_px: app.models_mut().insert(vec![4.0])',
            'scanline_strength: app.models_mut().insert(vec![0.32])',
            'scanline_spacing_px: app.models_mut().insert(vec![3.0])',
            'vignette_strength: app.models_mut().insert(vec![0.6])',
            'grain_strength: app.models_mut().insert(vec![0.12])',
            'grain_scale: app.models_mut().insert(vec![1.5])',
            'retro_pixel_scale: app.models_mut().insert(vec![10.0])',
            'retro_dither: app.models_mut().insert(true)',
            'cx.actions().models::<act::Reset>({',
            'cx.on_action_notify_models::<act::Reset>',
        ],
    ),
    (
        'liquid_glass_demo.rs',
        [
            'show_fake: cx.state().local_init(|| true),',
            'custom_v3_pair: cx.state().local_init(|| false),',
            'warp_strength_px: cx.state().local_init(|| vec![10.0]),',
            'cx.actions().local(&self.show_fake).set::<act::Reset>(true);',
            '.local(&self.custom_v3_bevel_secondary)',
            '.set::<act::Reset>(vec![1.0]);',
            '.local(&self.show_inspector)',
            '.toggle_bool::<act::ToggleInspector>();',
        ],
        [
            'show_fake: app.models_mut().insert(true)',
            'custom_v3_pair: app.models_mut().insert(false)',
            'warp_strength_px: app.models_mut().insert(vec![10.0])',
            'cx.on_action_notify_models::<act::Reset>',
            'cx.on_action_notify_models::<act::ToggleInspector>',
            'cx.actions().models::<act::Reset>({',
            'cx.actions().models::<act::ToggleInspector>({',
        ],
    ),
    (
        'genui_demo.rs',
        [
            'cx.actions().transient::<act::ClearActions>(TRANSIENT_GENUI_CLEAR_ACTIONS);',
            'if cx.effects().take_transient(TRANSIENT_GENUI_CLEAR_ACTIONS)',
        ],
        [
            'cx.on_action_notify_transient::<act::ClearActions>',
            'cx.take_transient_on_action_root(TRANSIENT_GENUI_CLEAR_ACTIONS)',
        ],
    ),
    (
        'markdown_demo.rs',
        [
            'if cx.effects().take_transient(TRANSIENT_REFRESH_REMOTE_IMAGES)',
            'cx.actions().transient::<act::RefreshRemoteImages>(TRANSIENT_REFRESH_REMOTE_IMAGES);',
            '.local(&expanded_code_blocks_state)',
            '.payload_update_if::<act::ToggleCodeBlockExpand>(|set, id| {',
            'let expanded_count = expanded_code_blocks_state.layout_read_ref(cx, |set| set.len());',
            'let pending = pending_anchor.layout_value(cx);',
            'let wrap_enabled = wrap_code_state.layout_value(cx);',
            'let cap_enabled = cap_code_height_state.layout_value(cx);',
            'components.on_link_activate = Some(Self::on_link_activate(pending_anchor_state.clone()));',
            'shadcn::Switch::new(&wrap_code_state)',
            'shadcn::Switch::new(&cap_code_height_state)',
        ],
        [
            'cx.take_transient_on_action_root(TRANSIENT_REFRESH_REMOTE_IMAGES)',
            'cx.on_action_notify_transient::<act::RefreshRemoteImages>',
            'cx.on_payload_action_notify::<act::ToggleCodeBlockExpand>({',
            'let expanded_count = cx.data().selector(',
            'self.st.pending_anchor.layout(cx).value_or_default()',
            'self.st.wrap_code.layout(cx).value_or_default()',
            'self.st.cap_code_height.layout(cx).value_or_default()',
            'wrap_code_state.clone_model()',
            'cap_code_height_state.clone_model()',
        ],
    ),
    (
        'table_demo.rs',
        [
            'use fret::advanced::prelude::LocalState;',
            'view_options_open: LocalState<bool>,',
            'enable_grouping: LocalState<bool>,',
            'grouped_column_mode: LocalState<Option<Arc<str>>>,',
            'view_options_open: LocalState::new_in(app.models_mut(), false),',
            'grouped_column_mode: LocalState::new_in(',
            'let enable_grouping = enable_grouping.layout_value_in(cx);',
            'let grouped_column_mode = grouped_column_mode.layout_value_in(cx);',
            'let view_options_open = view_options_open.clone();',
            'shadcn::DropdownMenu::from_open(open).build(',
            'shadcn::DropdownMenuCheckboxItem::new(',
            '&enable_grouping,',
            'shadcn::DropdownMenuRadioGroup::new(',
            '&grouped_column_mode,',
            'shadcn::ContextMenu::from_open(open).into_element(',
        ],
        [
            'use fret_ui_kit::declarative::model_watch::ModelWatchExt as _;',
            'LocalState::from_model(app.models_mut().insert(',
            'cx.watch_model(&enable_grouping_model)',
            'cx.watch_model(&grouped_column_mode_model)',
            'view_options_open: Model<bool>,',
            'enable_grouping: Model<bool>,',
            'grouped_column_mode: Model<Option<Arc<str>>>,',
        ],
    ),
    (
        'async_playground_demo.rs',
        [
            'let selected = locals.selected.layout_value(cx);',
            'let dark = locals.dark.layout_value(cx);',
            "fn tracked_query_inputs<'a, Cx>(cx: &mut Cx, locals: &AsyncPlaygroundLocals) -> QueryKeyInputs",
            "Cx: AppRenderContext<'a>,",
            'let query_inputs = tracked_query_inputs(cx, &locals);',
            'locals.tabs.layout_read_ref(cx, |tab| match tab.as_deref() {',
            'let policy_settings: QueryPolicySettings = cx.data().selector_layout(',
            'let state = handle.read_layout(cx);',
            'config.fail_mode.layout_value(cx)',
        ],
        [
            'let selected = cx.watch_model(&self.st.selected).layout().value_or_default();',
            'let dark = cx.watch_model(&self.st.dark).layout().value_or_default();',
            'let search = cx.watch_model(&st.search_input).layout().value_or_default();',
            'let symbol = cx.watch_model(&st.stock_symbol).layout().value_or_default();',
            'let tab = cx.watch_model(&st.tabs).layout().value_or_default();',
            'let stale_s = cx.watch_model(&config.stale_time_s).layout().value_or_default();',
            'cx.watch_model(&config.fail_mode)',
            'let search = st.search_input.layout_in(cx).value_or_default();',
            'let symbol = st.stock_symbol.layout_in(cx).value_or_default();',
            'let stale_s = config.stale_time_s.layout_in(cx).value_or_default();',
            'let cache_s = config.cache_time_s.layout_in(cx).value_or_default();',
            'let keep_prev = config.keep_prev.layout_in(cx).value_or_default();',
            'locals.tabs.layout_read_ref_in(cx, |tab| match tab.as_deref() {',
            'let policy_settings: QueryPolicySettings = cx.data().selector(',
            'cx.data().selector_layout(&config.fail_mode, |fail_mode| fail_mode)',
            'config.fail_mode.layout_in(cx).value_or_default()',
            'handle.layout_query(cx).value_or_default()',
        ],
    ),
    (
        'genui_demo.rs',
        [
            'auto_apply_standard_actions: LocalState<bool>,',
            'auto_fix_on_apply: LocalState<bool>,',
            'editor_text: LocalState<String>,',
            'stream_text: LocalState<String>,',
            'stream_patch_only: LocalState<bool>,',
            'auto_apply_standard_actions: LocalState::new_in(app.models_mut(), true),',
            'editor_text: LocalState::new_in(app.models_mut(), SPEC_JSON.to_string()),',
            'stream_patch_only: LocalState::new_in(app.models_mut(), false),',
            'let auto_apply_enabled = st.auto_apply_standard_actions.layout_value_in(cx);',
            'let _auto_fix_enabled = st.auto_fix_on_apply.layout_value_in(cx);',
            'let auto_apply_model = st.auto_apply_standard_actions.clone_model();',
            'let auto_fix_model = st.auto_fix_on_apply.clone_model();',
            'st.genui_state',
            '.layout_in(cx)',
            '.read_ref(|v| {',
            'st.action_queue',
            'st.validation_state',
            'let stream_patch_only = st.stream_patch_only.layout_value_in(cx);',
            'let stream_patch_only_model = st.stream_patch_only.clone_model();',
            'shadcn::Textarea::new(&editor_model)',
            'shadcn::Textarea::new(&stream_model)',
        ],
        [
            'auto_apply_standard_actions: Model<bool>,',
            'auto_fix_on_apply: Model<bool>,',
            'editor_text: Model<String>,',
            'stream_text: Model<String>,',
            'stream_patch_only: Model<bool>,',
            'LocalState::from_model(app.models_mut().insert(',
            'cx.watch_model(&st.auto_apply_standard_actions)',
            'cx.watch_model(&st.auto_fix_on_apply)',
            'cx.watch_model(&st.genui_state)',
            'cx.watch_model(&st.action_queue)',
            'cx.watch_model(&st.validation_state)',
            'cx.watch_model(&st.stream_patch_only)',
            'let auto_apply_model = st.auto_apply_standard_actions.clone();',
            'let auto_fix_model = st.auto_fix_on_apply.clone();',
            'let stream_patch_only_model = st.stream_patch_only.clone();',
            'shadcn::Textarea::new(editor_model.clone())',
            'shadcn::Textarea::new(stream_model.clone())',
        ],
    ),
    (
        'custom_effect_v2_demo.rs',
        [
            'model.layout_read_ref_in(cx, |v| v.first().copied().unwrap_or(default))',
            'let view_settings: CustomEffectV2ViewSettings = cx.data().selector_layout(',
            '&st.enabled,',
            '&st.use_non_filterable_input,',
            '&st.sampling,',
            '&st.debug_input,',
            'let enabled_model = st.enabled.clone_model();',
            'let sampling_model = st.sampling.clone_model();',
            'let sampling_open_model = st.sampling_open.clone_model();',
            'let uv_span_state = st.uv_span.clone();',
            'let input_strength_state = st.input_strength.clone();',
            'let rim_strength_state = st.rim_strength.clone();',
            'let blur_radius_state = st.blur_radius_px.clone();',
        ],
        [
            'let view_settings: CustomEffectV2ViewSettings = cx.data().selector(',
            'cx.watch_model(model)',
            'let enabled = cx.watch_model(&st.enabled).layout().value_or(true);',
            'let use_non_filterable_input = cx.watch_model(&st.use_non_filterable_input)',
            'let debug_input = cx.watch_model(&st.debug_input).layout().value_or(false);',
            'let enabled = st.enabled.layout_in(cx).value_or(true);',
            'let use_non_filterable_input = st.use_non_filterable_input.layout_in(cx).value_or(false);',
            'let sampling_value = st',
            'let debug_input = st.debug_input.layout_in(cx).value_or(false);',
            'let enabled_model = st.enabled.clone();',
            'let sampling_model = st.sampling.clone();',
            'let sampling_open_model = st.sampling_open.clone();',
            'let uv_span_model = st.uv_span.clone_model();',
            'let input_strength_model = st.input_strength.clone_model();',
            'let rim_strength_model = st.rim_strength.clone_model();',
            'let blur_radius_model = st.blur_radius_px.clone_model();',
        ],
    ),
    (
        'custom_effect_v2_web_demo.rs',
        [
            'let theme = cx.theme().snapshot();',
            'fn view_settings(',
            '-> CustomEffectV2WebViewSettings {',
            'fn reset_in(&self, models: &mut fret_runtime::ModelStore) {',
            'cx.data().selector_model_paint(',
            '&controls.enabled,',
            '&controls.tile_corner_radius_px,',
            'reset_controls.reset_in(host.models_mut());',
            'state.controls.reset_in(app.models_mut());',
            'let view_settings = Self::view_settings(cx, &controls);',
        ],
        [
            'cx.data().selector(',
            'cx.observe_model(&enabled_deps, Invalidation::Paint);',
            'cx.app.models().revision(&enabled_deps).unwrap_or(0)',
            'cx.app.models().get_cloned(&enabled).unwrap_or(true)',
            'cx.watch_model(model)',
            'model.paint_in(cx).read_ref(|v| v.first().copied().unwrap_or(default))',
            'model.paint_in(cx).read_ref(|v| v.as_ref().map(|s| s.to_string()))',
            'CustomEffectV2WebDriver::reset_controls(app, &state.controls);',
            'let _ = models.update(&reset_controls.enabled, |v| *v = true);',
            'let enabled = controls.enabled.paint_in(cx).value_or(true);',
            'let debug_input = controls.debug_input.paint_in(cx).value_or(false);',
            'Theme::global(&*cx.app).snapshot()',
        ],
    ),
    (
        'custom_effect_v2_glass_chrome_web_demo.rs',
        [
            'let theme = cx.theme().snapshot();',
            'fn view_settings(',
            '-> CustomEffectV2GlassChromeWebViewSettings {',
            'fn reset_in(&self, models: &mut fret_runtime::ModelStore) {',
            'cx.data().selector_model_paint(',
            '&controls.enabled,',
            '&controls.debug_input,',
            'reset_controls.reset_in(host.models_mut());',
            'state.controls.reset_in(app.models_mut());',
            'let view_settings = Self::view_settings(cx, &controls);',
        ],
        [
            'cx.data().selector(',
            'cx.observe_model(&enabled_deps, Invalidation::Paint);',
            'cx.app.models().revision(&enabled_deps).unwrap_or(0)',
            'cx.app.models().get_cloned(&enabled).unwrap_or(true)',
            'cx.watch_model(model)',
            'model.paint_in(cx).read_ref(|v| v.first().copied().unwrap_or(default))',
            'model.paint_in(cx).read_ref(|v| v.as_ref().map(|s| s.to_string()))',
            'CustomEffectV2GlassChromeWebDriver::reset_controls(app, &state.controls);',
            'let _ = models.update(&reset_controls.enabled, |v| *v = true);',
            'let enabled = controls.enabled.paint_in(cx).value_or(true);',
            'let debug_input = controls.debug_input.paint_in(cx).value_or(false);',
            'Theme::global(&*cx.app).snapshot()',
        ],
    ),
    (
        'custom_effect_v2_identity_web_demo.rs',
        [
            'let theme = cx.theme().snapshot();',
            'fn view_settings(',
            '-> CustomEffectV2IdentityWebViewSettings {',
            'fn reset_in(&self, models: &mut fret_runtime::ModelStore) {',
            'cx.data().selector_model_paint(',
            '&controls.enabled,',
            '&controls.debug_input,',
            'reset_controls.reset_in(host.models_mut());',
            'state.controls.reset_in(app.models_mut());',
            'let view_settings = Self::view_settings(cx, &controls);',
        ],
        [
            'cx.data().selector(',
            'cx.observe_model(&enabled_deps, Invalidation::Paint);',
            'cx.app.models().revision(&enabled_deps).unwrap_or(0)',
            'cx.app.models().get_cloned(&enabled).unwrap_or(true)',
            'cx.watch_model(model)',
            'model.paint_in(cx).read_ref(|v| v.first().copied().unwrap_or(default))',
            'model.paint_in(cx).read_ref(|v| v.as_ref().map(|s| s.to_string()))',
            'CustomEffectV2IdentityWebDriver::reset_controls(app, &state.controls);',
            'let _ = models.update(&reset_controls.enabled, |v| *v = true);',
            'let enabled = controls.enabled.paint_in(cx).value_or(true);',
            'let debug_input = controls.debug_input.paint_in(cx).value_or(false);',
            'Theme::global(&*cx.app).snapshot()',
        ],
    ),
    (
        'custom_effect_v2_lut_web_demo.rs',
        [
            'let theme = cx.theme().snapshot();',
            'fn view_settings(',
            '-> CustomEffectV2LutWebViewSettings {',
            'fn reset_in(&self, models: &mut fret_runtime::ModelStore) {',
            'cx.data().selector_model_paint(',
            '&controls.enabled,',
            '&controls.tile_corner_radius_px,',
            'reset_controls.reset_in(host.models_mut());',
            'state.controls.reset_in(app.models_mut());',
            'let view_settings = Self::view_settings(cx, &controls);',
        ],
        [
            'cx.data().selector(',
            'cx.observe_model(&enabled_deps, Invalidation::Paint);',
            'cx.app.models().revision(&enabled_deps).unwrap_or(0)',
            'cx.app.models().get_cloned(&enabled).unwrap_or(true)',
            'cx.watch_model(model)',
            'model.paint_in(cx).read_ref(|v| v.first().copied().unwrap_or(default))',
            'model.paint_in(cx).read_ref(|v| v.as_ref().map(|s| s.to_string()))',
            'CustomEffectV2LutWebDriver::reset_controls(app, &state.controls);',
            'let _ = models.update(&reset_controls.enabled, |v| *v = true);',
            'let enabled = controls.enabled.paint_in(cx).value_or(true);',
            'let debug_input = controls.debug_input.paint_in(cx).value_or(false);',
            'Theme::global(&*cx.app).snapshot()',
        ],
    ),
    (
        'imui_editor_proof_demo.rs',
        [
            "fn render_view<'a, Cx>(cx: &mut Cx) -> ViewElements",
            "Cx: fret::app::ElementContextAccess<'a, KernelApp>",
            'let cx = cx.elements();',
            'render_view(cx)',
            'struct EditorTextAssistReadout {',
            'struct EditorTextFieldReadout {',
            'struct AuthoringParitySharedStateReadout {',
            'fn editor_text_assist_readout(',
            'fn editor_text_field_readout(',
            'fn editor_string_model_readout(',
            'cx.data().selector_model_paint(',
            '(query_model, dismissed_query_model, active_item_id_model),',
            '(committed_model, outcome_model),',
            'editor_string_model_readout(',
            'let name_assist_items = editor_demo_name_assist_items(cx);',
            'let name_assist_readout = editor_text_assist_readout(',
            'let inline_rename_readout = editor_text_field_readout(',
            'let password_readout = editor_text_field_readout(',
            'let notes_readout = editor_text_field_readout(',
            '.selector_model_paint(&editor_gradient_stops_model,',
            '.selector_model_paint(&m.target, |target| target)',
            'let shared = cx.data().selector_model_paint(',
            '(&name_model, &drag_value_model, &numeric_input_model, &slider_model, &enabled_model, &shading_model, &gradient_angle_model, &gradient_stops_model,)',
        ],
        [
            'let query = cx.watch_model(&editor_name_assist_model)',
            'let dismissed_query = cx.watch_model(&editor_name_assist_dismissed_query_model)',
            'let active_item_id = cx.watch_model(&editor_name_assist_active_item_model)',
            'cx.watch_model(&editor_buffered_name_model)',
            'cx.watch_model(&editor_name_assist_accepted_model)',
            'cx.watch_model(&editor_inline_rename_model)',
            'cx.watch_model(&editor_inline_rename_outcome_model)',
            'cx.watch_model(&editor_password_model)',
            'cx.watch_model(&editor_password_outcome_model)',
            'cx.watch_model(&editor_notes_model)',
            'cx.watch_model(&editor_notes_outcome_model)',
            'watch_model(&editor_gradient_stops_model)',
            'watch_model(&m.target)',
            '.get_model_cloned(&editor_drag_value_outcome_model,',
            '.get_model_cloned(&editor_position_outcome_model,',
            '.get_model_cloned(&editor_transform_outcome_model,',
            '.get_model_cloned(&name_model, fret_ui::Invalidation::Paint)',
            '.get_model_copied(&drag_value_model, fret_ui::Invalidation::Paint)',
            '.get_model_copied(&numeric_input_model, fret_ui::Invalidation::Paint)',
            '.get_model_copied(&slider_model, fret_ui::Invalidation::Paint)',
            '.get_model_copied(&enabled_model, fret_ui::Invalidation::Paint)',
            '.get_model_cloned(&shading_model, fret_ui::Invalidation::Paint)',
            'render_view(cx.elements())',
        ],
    ),
    (
        'custom_effect_v3_demo.rs',
        [
            'let view_settings: CustomEffectV3ViewSettings = cx.data().selector_layout(',
            '&st.enabled,',
            '&st.show_user0_probe,',
            '&st.use_non_filterable_user1,',
            'let enabled_model = st.enabled.clone_model();',
            'let show_user0_probe_model = st.show_user0_probe.clone_model();',
        ],
        [
            'let enabled = cx.watch_model(&st.enabled).layout().value_or(true);',
            'let show_user0_probe = cx.watch_model(&st.show_user0_probe)',
            'let use_non_filterable_user1 = cx.watch_model(&st.use_non_filterable_user1)',
            'let view_settings: CustomEffectV3ViewSettings = cx.data().selector(',
            'let enabled = st.enabled.layout_in(cx).value_or(true);',
            'let show_user0_probe = st.show_user0_probe.layout_in(cx).value_or(false);',
            'let show_user1_probe = st.show_user1_probe.layout_in(cx).value_or(false);',
            'let use_non_filterable_user0 = st.use_non_filterable_user0.layout_in(cx).value_or(false);',
            'let use_non_filterable_user1 = st.use_non_filterable_user1.layout_in(cx).value_or(false);',
        ],
    ),
    (
        'custom_effect_v1_demo.rs',
        [
            'model.layout_read_ref_in(cx, |v| v.first().copied().unwrap_or(default))',
            'let enabled = st.enabled.layout_value_in(cx);',
            'let enabled_model = st.enabled.clone_model();',
            'let blur_radius_state = st.blur_radius_px.clone();',
        ],
        [
            'cx.watch_model(model)',
            'let enabled = cx.watch_model(&st.enabled).layout().value_or(true);',
            'let enabled_model = st.enabled.clone();',
            'let blur_radius_model = st.blur_radius_px.clone_model();',
        ],
    ),
    (
        'postprocess_theme_demo.rs',
        [
            'let view_settings: ThemePostprocessViewSettings = cx.data().selector_layout(',
            '&st.enabled,',
            '&st.compare,',
            '&st.theme,',
            '&st.retro_dither',
            'let enabled_model = st.enabled.clone_model();',
            'let theme_model = st.theme.clone_model();',
            'let theme_open_model = st.theme_open.clone_model();',
            'let chromatic_state = st.chromatic_offset_px.clone();',
        ],
        [
            'let view_settings: ThemePostprocessViewSettings = cx.data().selector(',
            'let enabled = cx.watch_model(&self.st.enabled).layout().value_or(true);',
            'let compare = cx.watch_model(&self.st.compare).layout().value_or(true);',
            'let theme = cx.watch_model(&self.st.theme).layout().value_or(Option::<Arc<str>>::None);',
            'let retro_dither = cx.watch_model(&self.st.retro_dither).layout().value_or(true);',
            'let enabled = self.st.enabled.layout_in(cx).value_or(true);',
            'let compare = self.st.compare.layout_in(cx).value_or(true);',
            'let theme = self.st.theme.layout_in(cx).value_or(Option::<Arc<str>>::None);',
            'let retro_dither = self.st.retro_dither.layout_in(cx).value_or(true);',
            'let enabled_model = st.enabled.clone();',
            'let theme_model = st.theme.clone();',
            'let theme_open_model = st.theme_open.clone();',
            'let chromatic_model = st.chromatic_offset_px.clone_model();',
        ],
    ),
    (
        'liquid_glass_demo.rs',
        [
            'model.layout_read_ref_in(cx, |v| v.first().copied().unwrap_or(default))',
            'let visibility_settings: LiquidGlassVisibilitySettings = cx.data().selector_layout(',
            '&st.show_fake,',
            '&st.custom_v3_pair,',
            'let mode_settings: LiquidGlassModeSettings = cx.data().selector_layout(',
            '&st.custom_v3_source_group,',
            'let show_fake_switch_model = st.show_fake.clone_model();',
            'let lens_radius_state = st.lens_radius_px.clone();',
        ],
        [
            'cx.watch_model(model)',
            'let visibility_settings: LiquidGlassVisibilitySettings = cx.data().selector(',
            'let mode_settings: LiquidGlassModeSettings = cx.data().selector(',
            'cx.observe_model(&show_fake_model, Invalidation::Layout);',
            'let lens_radius_model = st.lens_radius_px.clone_model();',
            'let show_fake = st.show_fake.layout_in(cx).value_or(true);',
            'let show_warp = st.show_warp.layout_in(cx).value_or(true);',
            'let show_warp_v2 = st.show_warp_v2.layout_in(cx).value_or(false);',
            'let show_custom_v2 = st.show_custom_v2.layout_in(cx).value_or(false);',
            'let show_custom_v3 = st.show_custom_v3.layout_in(cx).value_or(false);',
            'let custom_v3_pair = st.custom_v3_pair.layout_in(cx).value_or(false);',
            'let custom_v3_source_group = st.custom_v3_source_group.layout_in(cx).value_or(false);',
            'let show_inspector = st.show_inspector.layout_in(cx).value_or(true);',
            'let animate = st.animate.layout_in(cx).value_or(true);',
            'let use_backdrop = st.use_backdrop.layout_in(cx).value_or(true);',
            'let use_dither = st.use_dither.layout_in(cx).value_or(true);',
        ],
    ),
    (
        'launcher_utility_window_demo.rs',
        [
            'always_on_top: LocalState<bool>,',
            'status: LocalState<Arc<str>>,',
            'LocalState::new_in(app.models_mut(), false)',
            'LocalState::new_in(app.models_mut(), Arc::from("Idle"))',
            'let view_settings: LauncherUtilityWindowViewSettings = cx.data().selector_layout(',
            '(&st.always_on_top, &st.status),',
        ],
        [
            'let always_on_top = cx.watch_model(&st.always_on_top).layout().value_or(false);',
            'cx.watch_model(&st.status)',
            'let always_on_top = st.always_on_top.layout_in(cx).value_or(false);',
            'let status = st.status.layout_in(cx).value_or_else(|| Arc::from("Idle"));',
            'always_on_top: fret_runtime::Model<bool>,',
            'status: fret_runtime::Model<Arc<str>>,',
            'LocalState::from_model(app.models_mut().insert(',
            'let view_settings: LauncherUtilityWindowViewSettings = cx.data().selector(',
        ],
    ),
    (
        'window_hit_test_probe_demo.rs',
        [
            'let status = st.status.layout_in(cx).value_or_else(|| Arc::from("Idle"));',
        ],
        [
            'cx.watch_model(&st.status)',
        ],
    ),
    (
        'launcher_utility_window_materials_demo.rs',
        [
            'status: LocalState<Arc<str>>,',
            'LocalState::new_in(app.models_mut(), Arc::from("Idle"))',
            'let status = st.status.layout_value_in(cx);',
        ],
        [
            'cx.watch_model(&st.status)',
            'let status = st.status.layout_in(cx).value_or_else(|| Arc::from("Idle"));',
            'let status = cx.data().selector_layout(&st.status, |status| status);',
            'status: fret_runtime::Model<Arc<str>>,',
            'LocalState::from_model(app.models_mut().insert(',
        ],
    ),
    (
        'workspace_shell_demo.rs',
        [
            "fn workspace_shell_command_button<'a, Cx>(",
            "Cx: fret::app::ElementContextAccess<'a, App>,",
            'let cx = cx.elements();',
            'let (prompt_open, prompt): (bool, Option<WorkspaceShellDirtyClosePrompt>) =',
            'cx.data().selector_model_layout(',
            '(&dirty_close_prompt_open, &dirty_close_prompt),',
            '.selector_model_layout(&tabstrip_two_row_pinned, |two_row_pinned| {',
        ],
        [
            "let button = |cx: &mut fret_ui::ElementContext<'_, App>,",
            '.get_model_cloned(&dirty_close_prompt_open, Invalidation::Layout)',
            '.get_model_cloned(&dirty_close_prompt, Invalidation::Layout)',
            '.get_model_cloned(&tabstrip_two_row_pinned, Invalidation::Layout)',
        ],
    ),
]


CheckMarkers = Callable[..., None]
ReadSource = Callable[[Path], str]


def source_path(examples_src: Path, source_name: str) -> Path:
    return Path(os.path.normpath(str(examples_src / source_name)))


def check_selected_grouped_state_source_policies(
    failures: list[Any],
    *,
    examples_src: Path,
    read_source: ReadSource,
    check_required_forbidden_markers: CheckMarkers,
) -> None:
    for source_name, required, forbidden in SELECTED_GROUPED_STATE_POLICIES:
        path = source_path(examples_src, source_name)
        check_required_forbidden_markers(
            path,
            read_source(path),
            required=list(required),
            forbidden=list(forbidden),
            failures=failures,
        )
