// AUTOGENERATED by `material3_token_import`. DO NOT EDIT BY HAND.
//
// Source: Material Web v30 sassvars in `repo-ref\material-web\tokens\versions\v30_0\sass`

use fret_core::{FontId, FontWeight, Px, TextSlant, TextStyle};
use fret_ui::ThemeConfig;
use fret_ui::theme::CubicBezier;

pub(crate) fn inject_sys_state(cfg: &mut ThemeConfig) {
    cfg.numbers.insert(
        "md.sys.state.disabled.state-layer-opacity".to_string(),
        0.38,
    );
    cfg.numbers
        .insert("md.sys.state.dragged.state-layer-opacity".to_string(), 0.16);
    cfg.numbers
        .insert("md.sys.state.focus.state-layer-opacity".to_string(), 0.1);
    cfg.numbers
        .insert("md.sys.state.hover.state-layer-opacity".to_string(), 0.08);
    cfg.numbers
        .insert("md.sys.state.pressed.state-layer-opacity".to_string(), 0.1);
}

pub(crate) fn inject_sys_state_focus_indicator(cfg: &mut ThemeConfig) {
    cfg.metrics.insert(
        "md.sys.state.focus-indicator.inner-offset".to_string(),
        -3.0,
    );
    cfg.metrics
        .insert("md.sys.state.focus-indicator.outer-offset".to_string(), 2.0);
    cfg.metrics
        .insert("md.sys.state.focus-indicator.thickness".to_string(), 3.0);
}

pub(crate) fn inject_sys_motion(cfg: &mut ThemeConfig) {
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long1".to_string(), 700);
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long2".to_string(), 800);
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long3".to_string(), 900);
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long4".to_string(), 1000);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long1".to_string(), 450);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long2".to_string(), 500);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long3".to_string(), 550);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long4".to_string(), 600);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium1".to_string(), 250);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium2".to_string(), 300);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium3".to_string(), 350);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium4".to_string(), 400);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short1".to_string(), 50);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short2".to_string(), 100);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short3".to_string(), 150);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short4".to_string(), 200);
    cfg.easings.insert(
        "md.sys.motion.easing.emphasized".to_string(),
        CubicBezier {
            x1: 0.2,
            y1: 0.0,
            x2: 0.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.emphasized.accelerate".to_string(),
        CubicBezier {
            x1: 0.3,
            y1: 0.0,
            x2: 0.8,
            y2: 0.15,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.emphasized.decelerate".to_string(),
        CubicBezier {
            x1: 0.05,
            y1: 0.7,
            x2: 0.1,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.legacy".to_string(),
        CubicBezier {
            x1: 0.4,
            y1: 0.0,
            x2: 0.2,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.legacy.accelerate".to_string(),
        CubicBezier {
            x1: 0.4,
            y1: 0.0,
            x2: 1.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.legacy.decelerate".to_string(),
        CubicBezier {
            x1: 0.0,
            y1: 0.0,
            x2: 0.2,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.linear".to_string(),
        CubicBezier {
            x1: 0.0,
            y1: 0.0,
            x2: 1.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.standard".to_string(),
        CubicBezier {
            x1: 0.2,
            y1: 0.0,
            x2: 0.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.standard.accelerate".to_string(),
        CubicBezier {
            x1: 0.3,
            y1: 0.0,
            x2: 1.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.standard.decelerate".to_string(),
        CubicBezier {
            x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 1.0,
        },
    );
}

#[derive(Debug, Clone, Copy)]
struct SysTypescaleRole {
    key: &'static str,
    size_rem: f32,
    line_height_rem: f32,
    tracking_rem: f32,
    weight: u16,
    face: TypefaceFlavor,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TypefaceFlavor {
    Plain,
    Brand,
}

pub(crate) fn inject_sys_typescale(
    cfg: &mut ThemeConfig,
    typography: &super::v30::TypographyOptions,
) {
    let rem_in_px = typography.rem_in_px;
    for role in [
        SysTypescaleRole {
            key: "md.sys.typescale.body-large",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.03125,
            weight: 400,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.body-medium",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.015625,
            weight: 400,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.body-small",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.025,
            weight: 400,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.display-large",
            size_rem: 3.5625,
            line_height_rem: 4.0,
            tracking_rem: -0.015625,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.display-medium",
            size_rem: 2.8125,
            line_height_rem: 3.25,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.display-small",
            size_rem: 2.25,
            line_height_rem: 2.75,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.body-large",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.03125,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.body-medium",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.015625,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.body-small",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.025,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.display-large",
            size_rem: 3.5625,
            line_height_rem: 4.0,
            tracking_rem: -0.015625,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.display-medium",
            size_rem: 2.8125,
            line_height_rem: 3.25,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.display-small",
            size_rem: 2.25,
            line_height_rem: 2.75,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.headline-large",
            size_rem: 2.0,
            line_height_rem: 2.5,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.headline-medium",
            size_rem: 1.75,
            line_height_rem: 2.25,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.headline-small",
            size_rem: 1.5,
            line_height_rem: 2.0,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.label-large",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 700,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.label-medium",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 700,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.label-small",
            size_rem: 0.6875,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 700,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.title-large",
            size_rem: 1.375,
            line_height_rem: 1.75,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.title-medium",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.009375,
            weight: 600,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.title-small",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 600,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.headline-large",
            size_rem: 2.0,
            line_height_rem: 2.5,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.headline-medium",
            size_rem: 1.75,
            line_height_rem: 2.25,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.headline-small",
            size_rem: 1.5,
            line_height_rem: 2.0,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.label-large",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.label-medium",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.label-small",
            size_rem: 0.6875,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.title-large",
            size_rem: 1.375,
            line_height_rem: 1.75,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.title-medium",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.009375,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.title-small",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
    ] {
        let size_px = Px(role.size_rem * rem_in_px);
        let line_height_px = Px(role.line_height_rem * rem_in_px);
        let tracking_em = if role.size_rem.abs() <= f32::EPSILON {
            0.0
        } else {
            role.tracking_rem / role.size_rem
        };
        let font: FontId = match role.face {
            TypefaceFlavor::Plain => typography.plain_font.clone(),
            TypefaceFlavor::Brand => typography.brand_font.clone(),
        };
        cfg.text_styles.insert(
            role.key.to_string(),
            TextStyle {
                font,
                size: size_px,
                weight: FontWeight(role.weight),
                slant: TextSlant::Normal,
                line_height: Some(line_height_px),
                letter_spacing_em: Some(tracking_em),
            },
        );
    }
}

pub(crate) fn inject_comp_switch_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.switch.`

    cfg.metrics
        .insert("md.comp.switch.disabled.handle.elevation".to_string(), 0.0);
    cfg.numbers
        .insert("md.comp.switch.disabled.handle.opacity".to_string(), 0.38);
    cfg.numbers.insert(
        "md.comp.switch.disabled.selected.handle.opacity".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.switch.disabled.selected.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers
        .insert("md.comp.switch.disabled.track.opacity".to_string(), 0.12);
    cfg.numbers.insert(
        "md.comp.switch.disabled.unselected.handle.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.switch.disabled.unselected.icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics
        .insert("md.comp.switch.focus.indicator.offset".to_string(), 2.0);
    cfg.metrics
        .insert("md.comp.switch.focus.indicator.thickness".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.switch.handle.elevation".to_string(), 1.0);
    cfg.metrics
        .insert("md.comp.switch.handle.height".to_string(), 20.0);
    cfg.metrics
        .insert("md.comp.switch.handle.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.switch.handle.width".to_string(), 20.0);
    cfg.metrics
        .insert("md.comp.switch.pressed.handle.height".to_string(), 28.0);
    cfg.metrics
        .insert("md.comp.switch.pressed.handle.width".to_string(), 28.0);
    cfg.numbers.insert(
        "md.comp.switch.selected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.selected.handle.height".to_string(), 24.0);
    cfg.metrics
        .insert("md.comp.switch.selected.handle.width".to_string(), 24.0);
    cfg.numbers.insert(
        "md.comp.switch.selected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.switch.selected.icon.size".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.switch.selected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.state-layer.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.switch.state-layer.size".to_string(), 40.0);
    cfg.metrics
        .insert("md.comp.switch.track.height".to_string(), 32.0);
    cfg.metrics
        .insert("md.comp.switch.track.outline.width".to_string(), 2.0);
    cfg.metrics
        .insert("md.comp.switch.track.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.switch.track.width".to_string(), 52.0);
    cfg.numbers.insert(
        "md.comp.switch.unselected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.unselected.handle.height".to_string(), 16.0);
    cfg.metrics
        .insert("md.comp.switch.unselected.handle.width".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.switch.unselected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.switch.unselected.icon.size".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.switch.unselected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.with-icon.handle.height".to_string(), 24.0);
    cfg.metrics
        .insert("md.comp.switch.with-icon.handle.width".to_string(), 24.0);
}

pub(crate) fn inject_comp_primary_navigation_tab_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.primary-navigation-tab.`

    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.active-indicator.height".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.active.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.active.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.active.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.container.elevation".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.container.height".to_string(),
        48.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.container.shape".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.divider.height".to_string(),
        1.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.focus.indicator.outline.offset".to_string(),
        -3.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.focus.indicator.thickness".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.inactive.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.inactive.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.inactive.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.with-icon-and-label-text.container.height".to_string(),
        64.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.with-icon.icon.size".to_string(),
        24.0,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.with-label-text.label-text.weight".to_string(),
        500.0,
    );
}

pub(crate) fn inject_comp_menu_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.menu.`

    cfg.metrics.insert(
        "md.comp.menu.cascading-menu-indicator.icon.size".to_string(),
        24.0,
    );
    cfg.metrics
        .insert("md.comp.menu.container.elevation".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.menu.container.shape".to_string(), 4.0);
    cfg.metrics
        .insert("md.comp.menu.divider.height".to_string(), 1.0);
    cfg.metrics.insert(
        "md.comp.menu.focus.indicator.outline.offset".to_string(),
        -3.0,
    );
    cfg.metrics
        .insert("md.comp.menu.focus.indicator.thickness".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.menu.list-item.container.height".to_string(), 48.0);
    cfg.numbers.insert(
        "md.comp.menu.list-item.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.label-text.weight".to_string(),
        500.0,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.with-leading-icon.disabled.leading-icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.menu.list-item.with-leading-icon.leading-icon.size".to_string(),
        24.0,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.with-trailing-icon.disabled.trailing-icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.menu.list-item.with-trailing-icon.trailing-icon.size".to_string(),
        24.0,
    );
}

pub(crate) fn inject_comp_outlined_text_field_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.outlined-text-field.`

    cfg.metrics.insert(
        "md.comp.outlined-text-field.container.height".to_string(),
        56.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.container.shape".to_string(),
        4.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.input-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.leading-icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.outline.opacity".to_string(),
        0.12,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.disabled.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.supporting-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.trailing-icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.focus.indicator.outline.thickness".to_string(),
        3.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.focus.outline.width".to_string(),
        3.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.hover.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.input-text.weight".to_string(),
        400.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.label-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.leading-icon.size".to_string(),
        24.0,
    );
    cfg.metrics
        .insert("md.comp.outlined-text-field.outline.width".to_string(), 1.0);
    cfg.numbers.insert(
        "md.comp.outlined-text-field.supporting-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.trailing-icon.size".to_string(),
        24.0,
    );
}

pub(crate) fn inject_comp_filled_text_field_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.filled-text-field.`

    cfg.metrics.insert(
        "md.comp.filled-text-field.active-indicator.height".to_string(),
        1.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.container.height".to_string(),
        56.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.disabled.active-indicator.height".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.active-indicator.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.container.opacity".to_string(),
        0.04,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.input-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.leading-icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.supporting-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.trailing-icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.error.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.focus.active-indicator.height".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.focus.active-indicator.thickness".to_string(),
        3.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.hover.active-indicator.height".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.input-text.weight".to_string(),
        400.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.label-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.leading-icon.size".to_string(),
        24.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.supporting-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.trailing-icon.size".to_string(),
        24.0,
    );
}
