// AUTOGENERATED by `material3_token_import`. DO NOT EDIT BY HAND.
//
// Source: Material Web v30 sassvars in `repo-ref\material-web\tokens\versions\v30_0\sass`

use fret_core::{Corners, FontId, FontWeight, Px, TextSlant, TextStyle};
use fret_ui::ThemeConfig;
use fret_ui::theme::CubicBezier;

pub(crate) fn inject_sys_state(cfg: &mut ThemeConfig) {
    cfg.numbers.insert(
        "md.sys.state.disabled.state-layer-opacity".to_string(),
        0.38,
    );
    cfg.numbers
        .insert("md.sys.state.dragged.state-layer-opacity".to_string(), 0.16);
    cfg.numbers
        .insert("md.sys.state.focus.state-layer-opacity".to_string(), 0.1);
    cfg.numbers
        .insert("md.sys.state.hover.state-layer-opacity".to_string(), 0.08);
    cfg.numbers
        .insert("md.sys.state.pressed.state-layer-opacity".to_string(), 0.1);
}

pub(crate) fn inject_sys_state_focus_indicator(cfg: &mut ThemeConfig) {
    cfg.metrics.insert(
        "md.sys.state.focus-indicator.inner-offset".to_string(),
        -3.0,
    );
    cfg.metrics
        .insert("md.sys.state.focus-indicator.outer-offset".to_string(), 2.0);
    cfg.metrics
        .insert("md.sys.state.focus-indicator.thickness".to_string(), 3.0);
}

pub(crate) fn inject_sys_motion(cfg: &mut ThemeConfig) {
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long1".to_string(), 700);
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long2".to_string(), 800);
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long3".to_string(), 900);
    cfg.durations_ms
        .insert("md.sys.motion.duration.extra-long4".to_string(), 1000);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long1".to_string(), 450);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long2".to_string(), 500);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long3".to_string(), 550);
    cfg.durations_ms
        .insert("md.sys.motion.duration.long4".to_string(), 600);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium1".to_string(), 250);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium2".to_string(), 300);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium3".to_string(), 350);
    cfg.durations_ms
        .insert("md.sys.motion.duration.medium4".to_string(), 400);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short1".to_string(), 50);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short2".to_string(), 100);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short3".to_string(), 150);
    cfg.durations_ms
        .insert("md.sys.motion.duration.short4".to_string(), 200);
    cfg.easings.insert(
        "md.sys.motion.easing.emphasized".to_string(),
        CubicBezier {
            x1: 0.2,
            y1: 0.0,
            x2: 0.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.emphasized.accelerate".to_string(),
        CubicBezier {
            x1: 0.3,
            y1: 0.0,
            x2: 0.8,
            y2: 0.15,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.emphasized.decelerate".to_string(),
        CubicBezier {
            x1: 0.05,
            y1: 0.7,
            x2: 0.1,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.legacy".to_string(),
        CubicBezier {
            x1: 0.4,
            y1: 0.0,
            x2: 0.2,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.legacy.accelerate".to_string(),
        CubicBezier {
            x1: 0.4,
            y1: 0.0,
            x2: 1.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.legacy.decelerate".to_string(),
        CubicBezier {
            x1: 0.0,
            y1: 0.0,
            x2: 0.2,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.linear".to_string(),
        CubicBezier {
            x1: 0.0,
            y1: 0.0,
            x2: 1.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.standard".to_string(),
        CubicBezier {
            x1: 0.2,
            y1: 0.0,
            x2: 0.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.standard.accelerate".to_string(),
        CubicBezier {
            x1: 0.3,
            y1: 0.0,
            x2: 1.0,
            y2: 1.0,
        },
    );
    cfg.easings.insert(
        "md.sys.motion.easing.standard.decelerate".to_string(),
        CubicBezier {
            x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 1.0,
        },
    );
    cfg.numbers.insert(
        "md.sys.motion.spring.default.effects.damping".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.sys.motion.spring.default.effects.stiffness".to_string(),
        1600.0,
    );
    cfg.numbers.insert(
        "md.sys.motion.spring.default.spatial.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.sys.motion.spring.default.spatial.stiffness".to_string(),
        700.0,
    );
    cfg.numbers
        .insert("md.sys.motion.spring.fast.effects.damping".to_string(), 1.0);
    cfg.numbers.insert(
        "md.sys.motion.spring.fast.effects.stiffness".to_string(),
        3800.0,
    );
    cfg.numbers
        .insert("md.sys.motion.spring.fast.spatial.damping".to_string(), 0.9);
    cfg.numbers.insert(
        "md.sys.motion.spring.fast.spatial.stiffness".to_string(),
        1400.0,
    );
    cfg.numbers
        .insert("md.sys.motion.spring.slow.effects.damping".to_string(), 1.0);
    cfg.numbers.insert(
        "md.sys.motion.spring.slow.effects.stiffness".to_string(),
        800.0,
    );
    cfg.numbers
        .insert("md.sys.motion.spring.slow.spatial.damping".to_string(), 0.9);
    cfg.numbers.insert(
        "md.sys.motion.spring.slow.spatial.stiffness".to_string(),
        300.0,
    );
}

pub(crate) fn inject_sys_shape(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.sys.shape.`

    cfg.metrics.insert(
        "md.sys.shape.corner-value.extra-extra-large".to_string(),
        48.0,
    );
    cfg.metrics
        .insert("md.sys.shape.corner-value.extra-large".to_string(), 28.0);
    cfg.metrics.insert(
        "md.sys.shape.corner-value.extra-large-increased".to_string(),
        32.0,
    );
    cfg.metrics
        .insert("md.sys.shape.corner-value.extra-small".to_string(), 4.0);
    cfg.metrics
        .insert("md.sys.shape.corner-value.large".to_string(), 16.0);
    cfg.metrics.insert(
        "md.sys.shape.corner-value.large-increased".to_string(),
        20.0,
    );
    cfg.metrics
        .insert("md.sys.shape.corner-value.medium".to_string(), 12.0);
    cfg.metrics
        .insert("md.sys.shape.corner-value.none".to_string(), 0.0);
    cfg.metrics
        .insert("md.sys.shape.corner-value.small".to_string(), 8.0);
    cfg.metrics
        .insert("md.sys.shape.corner.extra-extra-large".to_string(), 48.0);
    cfg.metrics
        .insert("md.sys.shape.corner.extra-large".to_string(), 28.0);
    cfg.metrics.insert(
        "md.sys.shape.corner.extra-large-increased".to_string(),
        32.0,
    );
    cfg.corners.insert(
        "md.sys.shape.corner.extra-large.top".to_string(),
        Corners {
            top_left: Px(28.0),
            top_right: Px(28.0),
            bottom_right: Px(0.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.metrics
        .insert("md.sys.shape.corner.extra-small".to_string(), 4.0);
    cfg.corners.insert(
        "md.sys.shape.corner.extra-small.top".to_string(),
        Corners {
            top_left: Px(4.0),
            top_right: Px(4.0),
            bottom_right: Px(0.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.metrics
        .insert("md.sys.shape.corner.full".to_string(), 9999.0);
    cfg.metrics
        .insert("md.sys.shape.corner.large".to_string(), 16.0);
    cfg.metrics
        .insert("md.sys.shape.corner.large-increased".to_string(), 20.0);
    cfg.corners.insert(
        "md.sys.shape.corner.large.end".to_string(),
        Corners {
            top_left: Px(0.0),
            top_right: Px(16.0),
            bottom_right: Px(16.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.corners.insert(
        "md.sys.shape.corner.large.start".to_string(),
        Corners {
            top_left: Px(16.0),
            top_right: Px(0.0),
            bottom_right: Px(0.0),
            bottom_left: Px(16.0),
        },
    );
    cfg.corners.insert(
        "md.sys.shape.corner.large.top".to_string(),
        Corners {
            top_left: Px(16.0),
            top_right: Px(16.0),
            bottom_right: Px(0.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.metrics
        .insert("md.sys.shape.corner.medium".to_string(), 12.0);
    cfg.metrics
        .insert("md.sys.shape.corner.none".to_string(), 0.0);
    cfg.metrics
        .insert("md.sys.shape.corner.small".to_string(), 8.0);
}

#[derive(Debug, Clone, Copy)]
struct SysTypescaleRole {
    key: &'static str,
    size_rem: f32,
    line_height_rem: f32,
    tracking_rem: f32,
    weight: u16,
    face: TypefaceFlavor,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TypefaceFlavor {
    Plain,
    Brand,
}

pub(crate) fn inject_sys_typescale(
    cfg: &mut ThemeConfig,
    typography: &super::v30::TypographyOptions,
) {
    let rem_in_px = typography.rem_in_px;
    for role in [
        SysTypescaleRole {
            key: "md.sys.typescale.body-large",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.03125,
            weight: 400,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.body-medium",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.015625,
            weight: 400,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.body-small",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.025,
            weight: 400,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.display-large",
            size_rem: 3.5625,
            line_height_rem: 4.0,
            tracking_rem: -0.015625,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.display-medium",
            size_rem: 2.8125,
            line_height_rem: 3.25,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.display-small",
            size_rem: 2.25,
            line_height_rem: 2.75,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.body-large",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.03125,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.body-medium",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.015625,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.body-small",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.025,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.display-large",
            size_rem: 3.5625,
            line_height_rem: 4.0,
            tracking_rem: -0.015625,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.display-medium",
            size_rem: 2.8125,
            line_height_rem: 3.25,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.display-small",
            size_rem: 2.25,
            line_height_rem: 2.75,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.headline-large",
            size_rem: 2.0,
            line_height_rem: 2.5,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.headline-medium",
            size_rem: 1.75,
            line_height_rem: 2.25,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.headline-small",
            size_rem: 1.5,
            line_height_rem: 2.0,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.label-large",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 700,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.label-medium",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 700,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.label-small",
            size_rem: 0.6875,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 700,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.title-large",
            size_rem: 1.375,
            line_height_rem: 1.75,
            tracking_rem: 0.0,
            weight: 500,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.title-medium",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.009375,
            weight: 600,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.emphasized.title-small",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 600,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.headline-large",
            size_rem: 2.0,
            line_height_rem: 2.5,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.headline-medium",
            size_rem: 1.75,
            line_height_rem: 2.25,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.headline-small",
            size_rem: 1.5,
            line_height_rem: 2.0,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.label-large",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.label-medium",
            size_rem: 0.75,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.label-small",
            size_rem: 0.6875,
            line_height_rem: 1.0,
            tracking_rem: 0.03125,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.title-large",
            size_rem: 1.375,
            line_height_rem: 1.75,
            tracking_rem: 0.0,
            weight: 400,
            face: TypefaceFlavor::Brand,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.title-medium",
            size_rem: 1.0,
            line_height_rem: 1.5,
            tracking_rem: 0.009375,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
        SysTypescaleRole {
            key: "md.sys.typescale.title-small",
            size_rem: 0.875,
            line_height_rem: 1.25,
            tracking_rem: 0.00625,
            weight: 500,
            face: TypefaceFlavor::Plain,
        },
    ] {
        let size_px = Px(role.size_rem * rem_in_px);
        let line_height_px = Px(role.line_height_rem * rem_in_px);
        let tracking_em = if role.size_rem.abs() <= f32::EPSILON {
            0.0
        } else {
            role.tracking_rem / role.size_rem
        };
        let font: FontId = match role.face {
            TypefaceFlavor::Plain => typography.plain_font.clone(),
            TypefaceFlavor::Brand => typography.brand_font.clone(),
        };
        cfg.text_styles.insert(
            role.key.to_string(),
            TextStyle {
                font,
                size: size_px,
                weight: FontWeight(role.weight),
                slant: TextSlant::Normal,
                line_height: Some(line_height_px),
                letter_spacing_em: Some(tracking_em),
            },
        );
    }
}

pub(crate) fn inject_comp_button_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.button.`

    cfg.metrics
        .insert("md.comp.button.container.elevation".to_string(), 0.0);
    cfg.metrics
        .insert("md.comp.button.container.height".to_string(), 40.0);
    cfg.metrics
        .insert("md.comp.button.container.shape.round".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.button.container.shape.square".to_string(), 12.0);
    cfg.metrics.insert(
        "md.comp.button.disabled.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers
        .insert("md.comp.button.disabled.container.opacity".to_string(), 0.1);
    cfg.numbers
        .insert("md.comp.button.disabled.icon.opacity".to_string(), 0.38);
    cfg.numbers.insert(
        "md.comp.button.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.button.elevated.container.elevation".to_string(),
        1.0,
    );
    cfg.metrics.insert(
        "md.comp.button.elevated.disabled.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.elevated.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.elevated.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.button.elevated.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.button.elevated.focused.container.elevation".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.elevated.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.button.elevated.hovered.container.elevation".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.button.elevated.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics.insert(
        "md.comp.button.elevated.pressed.container.elevation".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.elevated.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.button.filled.container.elevation".to_string(), 0.0);
    cfg.metrics.insert(
        "md.comp.button.filled.disabled.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.filled.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.filled.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.button.filled.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.button.filled.focused.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.filled.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.button.filled.hovered.container.elevation".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.filled.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics.insert(
        "md.comp.button.filled.pressed.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.filled.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.button.focus.indicator.outline.offset".to_string(),
        2.0,
    );
    cfg.metrics
        .insert("md.comp.button.focus.indicator.thickness".to_string(), 3.0);
    cfg.metrics.insert(
        "md.comp.button.focused.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.button.hovered.container.elevation".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.button.icon-label-space".to_string(), 8.0);
    cfg.metrics
        .insert("md.comp.button.icon.size".to_string(), 20.0);
    cfg.metrics
        .insert("md.comp.button.large.container.height".to_string(), 96.0);
    cfg.metrics.insert(
        "md.comp.button.large.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.button.large.container.shape.square".to_string(),
        28.0,
    );
    cfg.metrics
        .insert("md.comp.button.large.icon-label-space".to_string(), 12.0);
    cfg.metrics
        .insert("md.comp.button.large.icon.size".to_string(), 32.0);
    cfg.metrics
        .insert("md.comp.button.large.leading-space".to_string(), 48.0);
    cfg.metrics.insert(
        "md.comp.button.large.outlined.outline.width".to_string(),
        2.0,
    );
    cfg.numbers.insert(
        "md.comp.button.large.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.button.large.pressed.container.corner-size.motion.spring.stiffness".to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.button.large.pressed.container.shape".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.button.large.selected.container.shape.round".to_string(),
        28.0,
    );
    cfg.metrics.insert(
        "md.comp.button.large.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics
        .insert("md.comp.button.large.trailing-space".to_string(), 48.0);
    cfg.metrics
        .insert("md.comp.button.leading-space".to_string(), 24.0);
    cfg.metrics
        .insert("md.comp.button.medium.container.height".to_string(), 56.0);
    cfg.metrics.insert(
        "md.comp.button.medium.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.button.medium.container.shape.square".to_string(),
        16.0,
    );
    cfg.metrics
        .insert("md.comp.button.medium.icon-label-space".to_string(), 8.0);
    cfg.metrics
        .insert("md.comp.button.medium.icon.size".to_string(), 24.0);
    cfg.metrics
        .insert("md.comp.button.medium.leading-space".to_string(), 24.0);
    cfg.metrics.insert(
        "md.comp.button.medium.outlined.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.medium.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.button.medium.pressed.container.corner-size.motion.spring.stiffness".to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.button.medium.pressed.container.shape".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.button.medium.selected.container.shape.round".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.button.medium.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics
        .insert("md.comp.button.medium.trailing-space".to_string(), 24.0);
    cfg.numbers.insert(
        "md.comp.button.outlined.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.outlined.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.button.outlined.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.button.outlined.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.outlined.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.button.outlined.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.button.pressed.container.corner-size.motion.spring.stiffness".to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.button.pressed.container.elevation".to_string(),
        0.0,
    );
    cfg.metrics
        .insert("md.comp.button.pressed.container.shape".to_string(), 8.0);
    cfg.numbers.insert(
        "md.comp.button.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.button.selected.container.shape.round".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.button.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics
        .insert("md.comp.button.small.container.height".to_string(), 40.0);
    cfg.metrics.insert(
        "md.comp.button.small.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.button.small.container.shape.square".to_string(),
        12.0,
    );
    cfg.metrics
        .insert("md.comp.button.small.icon-label-space".to_string(), 8.0);
    cfg.metrics
        .insert("md.comp.button.small.icon.size".to_string(), 20.0);
    cfg.metrics
        .insert("md.comp.button.small.leading-space".to_string(), 16.0);
    cfg.metrics.insert(
        "md.comp.button.small.outlined.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.small.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.button.small.pressed.container.corner-size.motion.spring.stiffness".to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.button.small.pressed.container.shape".to_string(),
        8.0,
    );
    cfg.metrics.insert(
        "md.comp.button.small.selected.container.shape.round".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.button.small.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics
        .insert("md.comp.button.small.trailing-space".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.button.text.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.text.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.button.text.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.button.text.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.text.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.button.text.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.button.tonal.container.elevation".to_string(), 0.0);
    cfg.metrics.insert(
        "md.comp.button.tonal.disabled.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.tonal.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.button.tonal.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.button.tonal.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.button.tonal.focused.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.tonal.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.button.tonal.hovered.container.elevation".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.tonal.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics.insert(
        "md.comp.button.tonal.pressed.container.elevation".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.button.tonal.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.button.trailing-space".to_string(), 24.0);
    cfg.metrics
        .insert("md.comp.button.xlarge.container.height".to_string(), 136.0);
    cfg.metrics.insert(
        "md.comp.button.xlarge.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xlarge.container.shape.square".to_string(),
        28.0,
    );
    cfg.metrics
        .insert("md.comp.button.xlarge.icon-label-space".to_string(), 16.0);
    cfg.metrics
        .insert("md.comp.button.xlarge.icon.size".to_string(), 40.0);
    cfg.metrics
        .insert("md.comp.button.xlarge.leading-space".to_string(), 64.0);
    cfg.metrics.insert(
        "md.comp.button.xlarge.outlined.outline.width".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.button.xlarge.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.button.xlarge.pressed.container.corner-size.motion.spring.stiffness".to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xlarge.pressed.container.shape".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xlarge.selected.container.shape.round".to_string(),
        28.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xlarge.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics
        .insert("md.comp.button.xlarge.trailing-space".to_string(), 64.0);
    cfg.metrics
        .insert("md.comp.button.xsmall.container.height".to_string(), 32.0);
    cfg.metrics.insert(
        "md.comp.button.xsmall.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xsmall.container.shape.square".to_string(),
        12.0,
    );
    cfg.metrics
        .insert("md.comp.button.xsmall.icon-label-space".to_string(), 8.0);
    cfg.metrics
        .insert("md.comp.button.xsmall.icon.size".to_string(), 20.0);
    cfg.metrics
        .insert("md.comp.button.xsmall.leading-space".to_string(), 12.0);
    cfg.metrics.insert(
        "md.comp.button.xsmall.outlined.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.button.xsmall.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.button.xsmall.pressed.container.corner-size.motion.spring.stiffness".to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xsmall.pressed.container.shape".to_string(),
        8.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xsmall.selected.container.shape.round".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.button.xsmall.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics
        .insert("md.comp.button.xsmall.trailing-space".to_string(), 12.0);
}

pub(crate) fn inject_comp_checkbox_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.checkbox.`

    cfg.metrics
        .insert("md.comp.checkbox.container.height".to_string(), 18.0);
    cfg.metrics
        .insert("md.comp.checkbox.container.shape".to_string(), 2.0);
    cfg.metrics
        .insert("md.comp.checkbox.container.size".to_string(), 18.0);
    cfg.metrics
        .insert("md.comp.checkbox.container.width".to_string(), 18.0);
    cfg.numbers.insert(
        "md.comp.checkbox.disabled.selected.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.disabled.unselected.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.error.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.error.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.error.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.focus.indicator.outline.offset".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.focus.indicator.thickness".to_string(),
        3.0,
    );
    cfg.metrics
        .insert("md.comp.checkbox.icon.size".to_string(), 18.0);
    cfg.numbers.insert(
        "md.comp.checkbox.selected.disabled.container.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.selected.disabled.container.outline.width".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.selected.error.focus.outline.width".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.selected.error.hover.outline.width".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.selected.error.pressed.outline.width".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.selected.focus.outline.width".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.selected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.selected.hover.outline.width".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.selected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.checkbox.selected.outline.width".to_string(), 0.0);
    cfg.metrics.insert(
        "md.comp.checkbox.selected.pressed.outline.width".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.selected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.checkbox.state-layer.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.checkbox.state-layer.size".to_string(), 40.0);
    cfg.numbers.insert(
        "md.comp.checkbox.unselected.disabled.container.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.unselected.disabled.outline.width".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.unselected.error.focus.outline.width".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.unselected.error.hover.outline.width".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.unselected.error.pressed.outline.width".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.unselected.focus.outline.width".to_string(),
        2.0,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.unselected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.checkbox.unselected.hover.outline.width".to_string(),
        2.0,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.unselected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.checkbox.unselected.outline.width".to_string(), 2.0);
    cfg.metrics.insert(
        "md.comp.checkbox.unselected.pressed.outline.width".to_string(),
        2.0,
    );
    cfg.numbers.insert(
        "md.comp.checkbox.unselected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
}

pub(crate) fn inject_comp_switch_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.switch.`

    cfg.metrics
        .insert("md.comp.switch.disabled.handle.elevation".to_string(), 0.0);
    cfg.numbers
        .insert("md.comp.switch.disabled.handle.opacity".to_string(), 0.38);
    cfg.numbers.insert(
        "md.comp.switch.disabled.selected.handle.opacity".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.switch.disabled.selected.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers
        .insert("md.comp.switch.disabled.track.opacity".to_string(), 0.12);
    cfg.numbers.insert(
        "md.comp.switch.disabled.unselected.handle.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.switch.disabled.unselected.icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics
        .insert("md.comp.switch.focus.indicator.offset".to_string(), 2.0);
    cfg.metrics
        .insert("md.comp.switch.focus.indicator.thickness".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.switch.handle.elevation".to_string(), 1.0);
    cfg.metrics
        .insert("md.comp.switch.handle.height".to_string(), 20.0);
    cfg.metrics
        .insert("md.comp.switch.handle.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.switch.handle.width".to_string(), 20.0);
    cfg.metrics
        .insert("md.comp.switch.pressed.handle.height".to_string(), 28.0);
    cfg.metrics
        .insert("md.comp.switch.pressed.handle.width".to_string(), 28.0);
    cfg.numbers.insert(
        "md.comp.switch.selected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.selected.handle.height".to_string(), 24.0);
    cfg.metrics
        .insert("md.comp.switch.selected.handle.width".to_string(), 24.0);
    cfg.numbers.insert(
        "md.comp.switch.selected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.switch.selected.icon.size".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.switch.selected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.state-layer.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.switch.state-layer.size".to_string(), 40.0);
    cfg.metrics
        .insert("md.comp.switch.track.height".to_string(), 32.0);
    cfg.metrics
        .insert("md.comp.switch.track.outline.width".to_string(), 2.0);
    cfg.metrics
        .insert("md.comp.switch.track.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.switch.track.width".to_string(), 52.0);
    cfg.numbers.insert(
        "md.comp.switch.unselected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.unselected.handle.height".to_string(), 16.0);
    cfg.metrics
        .insert("md.comp.switch.unselected.handle.width".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.switch.unselected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.switch.unselected.icon.size".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.switch.unselected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.switch.with-icon.handle.height".to_string(), 24.0);
    cfg.metrics
        .insert("md.comp.switch.with-icon.handle.width".to_string(), 24.0);
}

pub(crate) fn inject_comp_icon_button_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.icon-button.`

    cfg.metrics
        .insert("md.comp.icon-button.container.height".to_string(), 40.0);
    cfg.metrics.insert(
        "md.comp.icon-button.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.container.shape.square".to_string(),
        12.0,
    );
    cfg.metrics
        .insert("md.comp.icon-button.default.leading-space".to_string(), 8.0);
    cfg.metrics.insert(
        "md.comp.icon-button.default.trailing-space".to_string(),
        8.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.filled.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.filled.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.filled.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.filled.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.filled.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.focus.indicator.outline.offset".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.focus.indicator.thickness".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.icon-button.icon.size".to_string(), 24.0);
    cfg.metrics.insert(
        "md.comp.icon-button.large.container.height".to_string(),
        96.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.container.shape.square".to_string(),
        28.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.default.leading-space".to_string(),
        32.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.default.trailing-space".to_string(),
        32.0,
    );
    cfg.metrics
        .insert("md.comp.icon-button.large.icon.size".to_string(), 32.0);
    cfg.metrics.insert(
        "md.comp.icon-button.large.narrow.leading-space".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.narrow.trailing-space".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.outlined.outline.width".to_string(),
        2.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.large.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.large.pressed.container.corner-size.motion.spring.stiffness"
            .to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.pressed.container.shape".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.selected.container.shape.round".to_string(),
        28.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.wide.leading-space".to_string(),
        48.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.large.wide.trailing-space".to_string(),
        48.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.container.height".to_string(),
        56.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.container.shape.square".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.default.leading-space".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.default.trailing-space".to_string(),
        16.0,
    );
    cfg.metrics
        .insert("md.comp.icon-button.medium.icon.size".to_string(), 24.0);
    cfg.metrics.insert(
        "md.comp.icon-button.medium.narrow.leading-space".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.narrow.trailing-space".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.outlined.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.medium.pressed.container.corner-size.motion.spring.damping"
            .to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.medium.pressed.container.corner-size.motion.spring.stiffness"
            .to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.pressed.container.shape".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.selected.container.shape.round".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.wide.leading-space".to_string(),
        24.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.medium.wide.trailing-space".to_string(),
        24.0,
    );
    cfg.metrics
        .insert("md.comp.icon-button.narrow.leading-space".to_string(), 4.0);
    cfg.metrics
        .insert("md.comp.icon-button.narrow.trailing-space".to_string(), 4.0);
    cfg.numbers.insert(
        "md.comp.icon-button.outlined.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.outlined.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.outlined.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.outlined.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.outlined.selected.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.pressed.container.corner-size.motion.spring.stiffness".to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.pressed.container.shape".to_string(),
        8.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.selected.container.shape.round".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.selected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.selected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.selected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.container.height".to_string(),
        40.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.container.shape.square".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.default.leading-space".to_string(),
        8.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.default.trailing-space".to_string(),
        8.0,
    );
    cfg.metrics
        .insert("md.comp.icon-button.small.icon.size".to_string(), 24.0);
    cfg.metrics.insert(
        "md.comp.icon-button.small.narrow.leading-space".to_string(),
        4.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.narrow.trailing-space".to_string(),
        4.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.outlined.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.small.pressed.container.corner-size.motion.spring.damping".to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.small.pressed.container.corner-size.motion.spring.stiffness"
            .to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.pressed.container.shape".to_string(),
        8.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.selected.container.shape.round".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.wide.leading-space".to_string(),
        14.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.small.wide.trailing-space".to_string(),
        14.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.standard.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.standard.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.standard.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.standard.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.icon-button.state-layer.height".to_string(), 40.0);
    cfg.metrics
        .insert("md.comp.icon-button.state-layer.shape".to_string(), 9999.0);
    cfg.metrics
        .insert("md.comp.icon-button.state-layer.size".to_string(), 40.0);
    cfg.metrics
        .insert("md.comp.icon-button.state-layer.width".to_string(), 40.0);
    cfg.numbers.insert(
        "md.comp.icon-button.tonal.disabled.container.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.tonal.disabled.icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.tonal.focused.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.tonal.hovered.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.tonal.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.unselected.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.unselected.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.unselected.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.icon-button.wide.leading-space".to_string(), 14.0);
    cfg.metrics
        .insert("md.comp.icon-button.wide.trailing-space".to_string(), 14.0);
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.container.height".to_string(),
        136.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.container.shape.square".to_string(),
        28.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.default.leading-space".to_string(),
        48.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.default.trailing-space".to_string(),
        48.0,
    );
    cfg.metrics
        .insert("md.comp.icon-button.xlarge.icon.size".to_string(), 40.0);
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.narrow.leading-space".to_string(),
        32.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.narrow.trailing-space".to_string(),
        32.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.outlined.outline.width".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.xlarge.pressed.container.corner-size.motion.spring.damping"
            .to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.xlarge.pressed.container.corner-size.motion.spring.stiffness"
            .to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.pressed.container.shape".to_string(),
        16.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.selected.container.shape.round".to_string(),
        28.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.wide.leading-space".to_string(),
        72.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xlarge.wide.trailing-space".to_string(),
        72.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.container.height".to_string(),
        32.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.container.shape.round".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.container.shape.square".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.default.leading-space".to_string(),
        6.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.default.trailing-space".to_string(),
        6.0,
    );
    cfg.metrics
        .insert("md.comp.icon-button.xsmall.icon.size".to_string(), 20.0);
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.narrow.leading-space".to_string(),
        4.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.narrow.trailing-space".to_string(),
        4.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.outlined.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.xsmall.pressed.container.corner-size.motion.spring.damping"
            .to_string(),
        0.9,
    );
    cfg.numbers.insert(
        "md.comp.icon-button.xsmall.pressed.container.corner-size.motion.spring.stiffness"
            .to_string(),
        1400.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.pressed.container.shape".to_string(),
        8.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.selected.container.shape.round".to_string(),
        12.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.selected.container.shape.square".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.wide.leading-space".to_string(),
        10.0,
    );
    cfg.metrics.insert(
        "md.comp.icon-button.xsmall.wide.trailing-space".to_string(),
        10.0,
    );
}

pub(crate) fn inject_comp_primary_navigation_tab_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.primary-navigation-tab.`

    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.active-indicator.height".to_string(),
        3.0,
    );
    cfg.corners.insert(
        "md.comp.primary-navigation-tab.active-indicator.shape".to_string(),
        Corners {
            top_left: Px(3.0),
            top_right: Px(3.0),
            bottom_right: Px(0.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.active.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.active.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.active.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.container.elevation".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.container.height".to_string(),
        48.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.container.shape".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.divider.height".to_string(),
        1.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.focus.indicator.outline.offset".to_string(),
        -3.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.focus.indicator.thickness".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.inactive.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.inactive.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.inactive.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.with-icon-and-label-text.container.height".to_string(),
        64.0,
    );
    cfg.metrics.insert(
        "md.comp.primary-navigation-tab.with-icon.icon.size".to_string(),
        24.0,
    );
    cfg.numbers.insert(
        "md.comp.primary-navigation-tab.with-label-text.label-text.weight".to_string(),
        500.0,
    );
}

pub(crate) fn inject_comp_navigation_bar_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.navigation-bar.`

    cfg.metrics.insert(
        "md.comp.navigation-bar.active-indicator.height".to_string(),
        32.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-bar.active-indicator.shape".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-bar.active-indicator.width".to_string(),
        64.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-bar.active.label-text.weight".to_string(),
        700.0,
    );
    cfg.metrics
        .insert("md.comp.navigation-bar.badge.shape".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.navigation-bar.badge.size".to_string(), 6.0);
    cfg.metrics.insert(
        "md.comp.navigation-bar.container.elevation".to_string(),
        3.0,
    );
    cfg.metrics
        .insert("md.comp.navigation-bar.container.height".to_string(), 80.0);
    cfg.metrics
        .insert("md.comp.navigation-bar.container.shape".to_string(), 0.0);
    cfg.metrics.insert(
        "md.comp.navigation-bar.focus.indicator.outline.offset".to_string(),
        -3.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-bar.focus.indicator.thickness".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-bar.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.navigation-bar.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.navigation-bar.icon.size".to_string(), 24.0);
    cfg.numbers.insert(
        "md.comp.navigation-bar.label-text.weight".to_string(),
        500.0,
    );
    cfg.metrics
        .insert("md.comp.navigation-bar.large-badge.shape".to_string(), 8.0);
    cfg.metrics
        .insert("md.comp.navigation-bar.large-badge.size".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.navigation-bar.pressed.state-layer.opacity".to_string(),
        0.1,
    );
}

pub(crate) fn inject_comp_navigation_drawer_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.navigation-drawer.`

    cfg.metrics.insert(
        "md.comp.navigation-drawer.active-indicator.height".to_string(),
        56.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-drawer.active-indicator.shape".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-drawer.active-indicator.width".to_string(),
        336.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-drawer.active.label-text.weight".to_string(),
        700.0,
    );
    cfg.corners.insert(
        "md.comp.navigation-drawer.bottom.container.shape".to_string(),
        Corners {
            top_left: Px(16.0),
            top_right: Px(16.0),
            bottom_right: Px(0.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.corners.insert(
        "md.comp.navigation-drawer.container.shape".to_string(),
        Corners {
            top_left: Px(0.0),
            top_right: Px(16.0),
            bottom_right: Px(16.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.metrics.insert(
        "md.comp.navigation-drawer.container.width".to_string(),
        360.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-drawer.focus.indicator.outline.offset".to_string(),
        -3.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-drawer.focus.indicator.thickness".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-drawer.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.navigation-drawer.headline.weight".to_string(),
        500.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-drawer.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.navigation-drawer.icon.size".to_string(), 24.0);
    cfg.numbers.insert(
        "md.comp.navigation-drawer.label-text.weight".to_string(),
        500.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-drawer.large-badge-label.weight".to_string(),
        500.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-drawer.modal.container.elevation".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-drawer.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers
        .insert("md.comp.navigation-drawer.scrim.opacity".to_string(), 0.4);
    cfg.metrics.insert(
        "md.comp.navigation-drawer.standard.container.elevation".to_string(),
        0.0,
    );
}

pub(crate) fn inject_comp_navigation_rail_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.navigation-rail.`

    cfg.metrics.insert(
        "md.comp.navigation-rail.active-indicator.height".to_string(),
        32.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-rail.active-indicator.shape".to_string(),
        9999.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-rail.active-indicator.width".to_string(),
        56.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-rail.active.label-text.weight".to_string(),
        700.0,
    );
    cfg.metrics
        .insert("md.comp.navigation-rail.badge.shape".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.navigation-rail.badge.size".to_string(), 6.0);
    cfg.metrics.insert(
        "md.comp.navigation-rail.container.elevation".to_string(),
        0.0,
    );
    cfg.metrics
        .insert("md.comp.navigation-rail.container.shape".to_string(), 0.0);
    cfg.metrics
        .insert("md.comp.navigation-rail.container.width".to_string(), 80.0);
    cfg.numbers.insert(
        "md.comp.navigation-rail.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.navigation-rail.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.navigation-rail.icon.size".to_string(), 24.0);
    cfg.numbers.insert(
        "md.comp.navigation-rail.label-text.weight".to_string(),
        500.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-rail.large-badge-label.weight".to_string(),
        500.0,
    );
    cfg.metrics
        .insert("md.comp.navigation-rail.large-badge.shape".to_string(), 8.0);
    cfg.metrics
        .insert("md.comp.navigation-rail.large-badge.size".to_string(), 16.0);
    cfg.numbers.insert(
        "md.comp.navigation-rail.menu.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.navigation-rail.menu.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics
        .insert("md.comp.navigation-rail.menu.icon.size".to_string(), 24.0);
    cfg.numbers.insert(
        "md.comp.navigation-rail.menu.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.navigation-rail.no-label.active-indicator.height".to_string(),
        56.0,
    );
    cfg.metrics.insert(
        "md.comp.navigation-rail.no-label.active-indicator.shape".to_string(),
        9999.0,
    );
    cfg.numbers.insert(
        "md.comp.navigation-rail.pressed.state-layer.opacity".to_string(),
        0.1,
    );
}

pub(crate) fn inject_comp_menu_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.menu.`

    cfg.metrics.insert(
        "md.comp.menu.cascading-menu-indicator.icon.size".to_string(),
        24.0,
    );
    cfg.metrics
        .insert("md.comp.menu.container.elevation".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.menu.container.shape".to_string(), 4.0);
    cfg.metrics
        .insert("md.comp.menu.divider.height".to_string(), 1.0);
    cfg.metrics.insert(
        "md.comp.menu.focus.indicator.outline.offset".to_string(),
        -3.0,
    );
    cfg.metrics
        .insert("md.comp.menu.focus.indicator.thickness".to_string(), 3.0);
    cfg.metrics
        .insert("md.comp.menu.list-item.container.height".to_string(), 48.0);
    cfg.numbers.insert(
        "md.comp.menu.list-item.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.label-text.weight".to_string(),
        500.0,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.with-leading-icon.disabled.leading-icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.menu.list-item.with-leading-icon.leading-icon.size".to_string(),
        24.0,
    );
    cfg.numbers.insert(
        "md.comp.menu.list-item.with-trailing-icon.disabled.trailing-icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.menu.list-item.with-trailing-icon.trailing-icon.size".to_string(),
        24.0,
    );
}

pub(crate) fn inject_comp_dialog_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.dialog.`

    cfg.numbers.insert(
        "md.comp.dialog.action.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.dialog.action.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers
        .insert("md.comp.dialog.action.label-text.weight".to_string(), 500.0);
    cfg.numbers.insert(
        "md.comp.dialog.action.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics
        .insert("md.comp.dialog.container.elevation".to_string(), 6.0);
    cfg.metrics
        .insert("md.comp.dialog.container.shape".to_string(), 28.0);
    cfg.numbers
        .insert("md.comp.dialog.headline.weight".to_string(), 400.0);
    cfg.numbers
        .insert("md.comp.dialog.subhead.weight".to_string(), 400.0);
    cfg.numbers
        .insert("md.comp.dialog.supporting-text.weight".to_string(), 400.0);
    cfg.metrics.insert(
        "md.comp.dialog.with-divider.divider.height".to_string(),
        1.0,
    );
    cfg.metrics
        .insert("md.comp.dialog.with-icon.icon.size".to_string(), 24.0);
}

pub(crate) fn inject_comp_full_screen_dialog_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.full-screen-dialog.`

    cfg.metrics.insert(
        "md.comp.full-screen-dialog.action-bar.container.elevation".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.action-bar.container.height".to_string(),
        56.0,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.action-bar.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.action-bar.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.action-bar.label-text.weight".to_string(),
        500.0,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.action-bar.on-scroll.container.elevation".to_string(),
        3.0,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.action-bar.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.container.elevation".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.container.shape".to_string(),
        0.0,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.header.action.focus.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.header.action.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.header.action.label-text.weight".to_string(),
        500.0,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.header.action.pressed.state-layer.opacity".to_string(),
        0.1,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.header.container.elevation".to_string(),
        0.0,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.header.container.height".to_string(),
        56.0,
    );
    cfg.numbers.insert(
        "md.comp.full-screen-dialog.header.headline.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.header.icon.size".to_string(),
        24.0,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.header.on-scroll.container.elevation".to_string(),
        3.0,
    );
    cfg.metrics.insert(
        "md.comp.full-screen-dialog.with-divider.divider.height".to_string(),
        1.0,
    );
}

pub(crate) fn inject_comp_outlined_text_field_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.outlined-text-field.`

    cfg.metrics.insert(
        "md.comp.outlined-text-field.container.height".to_string(),
        56.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.container.shape".to_string(),
        4.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.input-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.leading-icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.outline.opacity".to_string(),
        0.12,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.disabled.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.supporting-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.disabled.trailing-icon.opacity".to_string(),
        0.38,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.focus.indicator.outline.thickness".to_string(),
        3.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.focus.outline.width".to_string(),
        3.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.hover.outline.width".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.input-text.weight".to_string(),
        400.0,
    );
    cfg.numbers.insert(
        "md.comp.outlined-text-field.label-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.leading-icon.size".to_string(),
        24.0,
    );
    cfg.metrics
        .insert("md.comp.outlined-text-field.outline.width".to_string(), 1.0);
    cfg.numbers.insert(
        "md.comp.outlined-text-field.supporting-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.outlined-text-field.trailing-icon.size".to_string(),
        24.0,
    );
}

pub(crate) fn inject_comp_filled_text_field_scalars(cfg: &mut ThemeConfig) {
    // Source: Material Web v30 sassvars
    // Prefix: `md.comp.filled-text-field.`

    cfg.metrics.insert(
        "md.comp.filled-text-field.active-indicator.height".to_string(),
        1.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.container.height".to_string(),
        56.0,
    );
    cfg.corners.insert(
        "md.comp.filled-text-field.container.shape".to_string(),
        Corners {
            top_left: Px(4.0),
            top_right: Px(4.0),
            bottom_right: Px(0.0),
            bottom_left: Px(0.0),
        },
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.disabled.active-indicator.height".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.active-indicator.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.container.opacity".to_string(),
        0.04,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.input-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.label-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.leading-icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.supporting-text.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.disabled.trailing-icon.opacity".to_string(),
        0.38,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.error.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.focus.active-indicator.height".to_string(),
        2.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.focus.active-indicator.thickness".to_string(),
        3.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.hover.active-indicator.height".to_string(),
        1.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.hover.state-layer.opacity".to_string(),
        0.08,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.input-text.weight".to_string(),
        400.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.label-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.leading-icon.size".to_string(),
        24.0,
    );
    cfg.numbers.insert(
        "md.comp.filled-text-field.supporting-text.weight".to_string(),
        400.0,
    );
    cfg.metrics.insert(
        "md.comp.filled-text-field.trailing-icon.size".to_string(),
        24.0,
    );
}
