/// Public command classes exposed by the IMUI debug draw list.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum DebugDrawCommandKind {
    Line,
    Polyline,
    ConvexPolyFilled,
    ConcavePolyFilled,
    Rect,
    RectFilled,
    RectFilledMultiColor,
    Quad,
    QuadFilled,
    Triangle,
    TriangleFilled,
    TriangleMesh,
    ImageTriangleMesh,
    Circle,
    CircleFilled,
    Ngon,
    NgonFilled,
    Ellipse,
    EllipseFilled,
    BezierQuadratic,
    BezierCubic,
    PushClipRect,
    PopClipRect,
    Image,
    ImageRegion,
    ImageQuad,
    ImageRounded,
    ImageRegionRounded,
    SvgImage,
    SvgMaskIcon,
    Text,
}
