#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from icon_codegen import IconPackSpec, generate_pack, repo_root


RADIX_SPEC = IconPackSpec(
    pack_name="Radix",
    namespace="radix",
    id_prefix="radix",
    source_comment="third_party/radix-icons/packages/radix-icons/icons/*.svg",
    generated_header="// @generated by tools/gen_radix.py. DO NOT EDIT.",
    generator_script="gen_radix.py",
)


def main() -> None:
    root = repo_root()
    parser = argparse.ArgumentParser(
        description="Generate full Radix icon list and Rust vendor constants from third_party/radix-icons."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=root / "third_party" / "radix-icons" / "packages" / "radix-icons" / "icons",
        help="Radix SVG source directory (default: third_party/radix-icons/packages/radix-icons/icons)",
    )
    parser.add_argument(
        "--list-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-radix" / "icon-list.txt",
        help="Output path for icon-list.txt",
    )
    parser.add_argument(
        "--ids-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-radix" / "src" / "generated_ids.rs",
        help="Output path for generated Rust constants",
    )
    args = parser.parse_args()

    generate_pack(
        spec=RADIX_SPEC,
        source=args.source,
        list_out=args.list_out,
        ids_out=args.ids_out,
    )


if __name__ == "__main__":
    main()
