#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def normalize_const_name(icon_stem: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9]+", "_", icon_stem).strip("_").upper()
    if not normalized:
        normalized = "ICON"
    if normalized[0].isdigit():
        normalized = f"ICON_{normalized}"
    return normalized


def collect_icon_stems(source_dir: Path) -> list[str]:
    if not source_dir.exists():
        raise SystemExit(f"Source directory not found: {source_dir}")

    stems = sorted(path.stem for path in source_dir.glob("*.svg"))
    if not stems:
        raise SystemExit(f"No SVG icons found in {source_dir}")

    return stems


def write_icon_list(stems: list[str], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by tools/gen_radix.py. Do not edit manually.",
        "# Source: third_party/radix-icons/packages/radix-icons/icons/*.svg",
        "",
    ]
    lines.extend(f"{stem}.svg" for stem in stems)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_generated_ids(stems: list[str], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    const_to_stem: dict[str, str] = {}
    collisions: dict[str, list[str]] = {}

    for stem in stems:
        const_name = normalize_const_name(stem)
        if const_name in const_to_stem:
            collisions.setdefault(const_name, [const_to_stem[const_name]]).append(stem)
        else:
            const_to_stem[const_name] = stem

    if collisions:
        collision_lines = [
            f"{const_name}: {', '.join(names)}"
            for const_name, names in sorted(collisions.items())
        ]
        raise SystemExit(
            "Detected normalized constant name collisions in Radix icons:\n"
            + "\n".join(collision_lines)
        )

    lines = [
        "// @generated by tools/gen_radix.py. DO NOT EDIT.",
        "//! Generated vendor icon constants for Radix.",
        "",
        "use fret_icons::IconId;",
        "",
        "pub mod radix {",
        "    use super::IconId;",
        "",
    ]

    for const_name, stem in sorted(const_to_stem.items()):
        lines.append(
            f"    pub const {const_name}: IconId = IconId::new_static(\"radix.{stem}\");"
        )

    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    root = repo_root()
    parser = argparse.ArgumentParser(
        description="Generate full Radix icon list and Rust vendor constants from third_party/radix-icons."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=root / "third_party" / "radix-icons" / "packages" / "radix-icons" / "icons",
        help="Radix SVG source directory (default: third_party/radix-icons/packages/radix-icons/icons)",
    )
    parser.add_argument(
        "--list-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-radix" / "icon-list.txt",
        help="Output path for icon-list.txt",
    )
    parser.add_argument(
        "--ids-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-radix" / "src" / "generated_ids.rs",
        help="Output path for generated Rust constants",
    )
    args = parser.parse_args()

    stems = collect_icon_stems(args.source)
    write_icon_list(stems, args.list_out)
    write_generated_ids(stems, args.ids_out)

    print(f"Generated Radix metadata from {args.source}")
    print(f"  icons: {len(stems)}")
    print(f"  list : {args.list_out}")
    print(f"  ids  : {args.ids_out}")


if __name__ == "__main__":
    main()

