#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from icon_codegen import IconPackSpec, generate_pack, repo_root


LUCIDE_SPEC = IconPackSpec(
    pack_name="Lucide",
    namespace="lucide",
    id_prefix="lucide",
    source_comment="third_party/lucide/icons/*.svg",
    generated_header="// @generated by tools/gen_lucide.py. DO NOT EDIT.",
    generator_script="gen_lucide.py",
)


def main() -> None:
    root = repo_root()
    parser = argparse.ArgumentParser(
        description="Generate full Lucide icon list and Rust vendor constants from third_party/lucide."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=root / "third_party" / "lucide" / "icons",
        help="Lucide SVG source directory (default: third_party/lucide/icons)",
    )
    parser.add_argument(
        "--list-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-lucide" / "icon-list.txt",
        help="Output path for icon-list.txt",
    )
    parser.add_argument(
        "--ids-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-lucide" / "src" / "generated_ids.rs",
        help="Output path for generated Rust constants",
    )
    parser.add_argument(
        "--aliases-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-lucide" / "vendor-aliases.txt",
        help="Output path for generated legacy vendor alias mappings",
    )
    args = parser.parse_args()

    generate_pack(
        spec=LUCIDE_SPEC,
        source=args.source,
        list_out=args.list_out,
        ids_out=args.ids_out,
    )
    write_vendor_aliases(
        source_dir=args.source,
        out_path=args.aliases_out,
    )


def write_vendor_aliases(*, source_dir: Path, out_path: Path) -> int:
    if not source_dir.exists():
        raise SystemExit(f"Source directory not found: {source_dir}")

    svg_stems = {path.stem for path in source_dir.glob("*.svg")}
    alias_to_target: dict[str, str] = {}

    for metadata_path in sorted(source_dir.glob("*.json")):
        canonical_stem = metadata_path.stem
        if canonical_stem not in svg_stems:
            continue

        data = json.loads(metadata_path.read_text(encoding="utf-8"))
        aliases = data.get("aliases", [])
        if not isinstance(aliases, list):
            raise SystemExit(f"Invalid aliases array in {metadata_path}")

        for alias in aliases:
            if not isinstance(alias, dict):
                raise SystemExit(f"Invalid alias entry in {metadata_path}")
            alias_name = alias.get("name")
            if not isinstance(alias_name, str) or not alias_name.strip():
                raise SystemExit(f"Invalid alias name in {metadata_path}")
            if alias_name == canonical_stem:
                continue
            if alias_name in svg_stems:
                raise SystemExit(
                    f"Alias `{alias_name}` from {metadata_path.name} collides with a canonical Lucide SVG stem."
                )

            previous_target = alias_to_target.get(alias_name)
            if previous_target is not None and previous_target != canonical_stem:
                raise SystemExit(
                    f"Alias `{alias_name}` maps to multiple Lucide icons: `{previous_target}` and `{canonical_stem}`."
                )
            alias_to_target[alias_name] = canonical_stem

    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by tools/gen_lucide.py. Do not edit manually.",
        "# Source: third_party/lucide/icons/*.json aliases[]",
        "# Format: <legacy-name>=<canonical-svg-stem>",
        "",
    ]
    lines.extend(
        f"{alias_name}={canonical_stem}"
        for alias_name, canonical_stem in sorted(alias_to_target.items())
    )
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"  aliases: {len(alias_to_target)}")
    print(f"  map  : {out_path}")
    return len(alias_to_target)


if __name__ == "__main__":
    main()
