#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from icon_codegen import IconPackSpec, generate_pack, repo_root


LUCIDE_SPEC = IconPackSpec(
    pack_name="Lucide",
    namespace="lucide",
    id_prefix="lucide",
    source_comment="third_party/lucide/icons/*.svg",
    generated_header="// @generated by tools/gen_lucide.py. DO NOT EDIT.",
    generator_script="gen_lucide.py",
)


def main() -> None:
    root = repo_root()
    parser = argparse.ArgumentParser(
        description="Generate full Lucide icon list and Rust vendor constants from third_party/lucide."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=root / "third_party" / "lucide" / "icons",
        help="Lucide SVG source directory (default: third_party/lucide/icons)",
    )
    parser.add_argument(
        "--list-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-lucide" / "icon-list.txt",
        help="Output path for icon-list.txt",
    )
    parser.add_argument(
        "--ids-out",
        type=Path,
        default=root / "ecosystem" / "fret-icons-lucide" / "src" / "generated_ids.rs",
        help="Output path for generated Rust constants",
    )
    args = parser.parse_args()

    generate_pack(
        spec=LUCIDE_SPEC,
        source=args.source,
        list_out=args.list_out,
        ids_out=args.ids_out,
    )


if __name__ == "__main__":
    main()
