#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re


@dataclass(frozen=True)
class IconPackSpec:
    pack_name: str
    namespace: str
    id_prefix: str
    source_comment: str
    generated_header: str
    generator_script: str


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def normalize_const_name(icon_stem: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9]+", "_", icon_stem).strip("_").upper()
    if not normalized:
        normalized = "ICON"
    if normalized[0].isdigit():
        normalized = f"ICON_{normalized}"
    return normalized


def collect_icon_stems(source_dir: Path) -> list[str]:
    if not source_dir.exists():
        raise SystemExit(f"Source directory not found: {source_dir}")

    stems = sorted(path.stem for path in source_dir.glob("*.svg"))
    if not stems:
        raise SystemExit(f"No SVG icons found in {source_dir}")

    return stems


def write_icon_list(
    stems: list[str],
    out_path: Path,
    source_comment: str,
    generator_script: str,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Generated by tools/{generator_script}. Do not edit manually.",
        f"# Source: {source_comment}",
        "",
    ]
    lines.extend(f"{stem}.svg" for stem in stems)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _const_map(stems: list[str], pack_name: str) -> dict[str, str]:
    const_to_stem: dict[str, str] = {}
    collisions: dict[str, list[str]] = {}

    for stem in stems:
        const_name = normalize_const_name(stem)
        if const_name in const_to_stem:
            collisions.setdefault(const_name, [const_to_stem[const_name]]).append(stem)
        else:
            const_to_stem[const_name] = stem

    if collisions:
        collision_lines = [
            f"{const_name}: {', '.join(names)}"
            for const_name, names in sorted(collisions.items())
        ]
        raise SystemExit(
            f"Detected normalized constant name collisions in {pack_name} icons:\n"
            + "\n".join(collision_lines)
        )

    return const_to_stem


def write_generated_ids(stems: list[str], out_path: Path, spec: IconPackSpec) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    const_to_stem = _const_map(stems, spec.pack_name)

    lines = [
        spec.generated_header,
        f"//! Generated vendor icon constants for {spec.pack_name}.",
        "",
        "use fret_icons::IconId;",
        "",
        f"pub mod {spec.namespace} {{",
        "    use super::IconId;",
        "",
    ]

    for const_name, stem in sorted(const_to_stem.items()):
        lines.append(
            f"    pub const {const_name}: IconId = IconId::new_static(\"{spec.id_prefix}.{stem}\");"
        )

    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def generate_pack(
    *,
    spec: IconPackSpec,
    source: Path,
    list_out: Path,
    ids_out: Path,
) -> int:
    stems = collect_icon_stems(source)
    write_icon_list(stems, list_out, spec.source_comment, spec.generator_script)
    write_generated_ids(stems, ids_out, spec)

    print(f"Generated {spec.pack_name} metadata from {source}")
    print(f"  icons: {len(stems)}")
    print(f"  list : {list_out}")
    print(f"  ids  : {ids_out}")
    return len(stems)
