import type { BundleModel, SnapshotModel, SemanticsNodeModel, DiffResult } from './types'
import { getDiffSummary, diffSnapshots } from './diff'

type JsonObject = Record<string, unknown>

function asObject(v: unknown): JsonObject | null {
  if (!v || typeof v !== 'object' || Array.isArray(v)) return null
  return v as JsonObject
}

function asArray(v: unknown): unknown[] | null {
  return Array.isArray(v) ? v : null
}

export function generateMarkdownSummary(
  bundle: BundleModel,
  selectedWindow: number,
  selectedSnapshotA: number,
  selectedSnapshotB: number | null,
  selectedNodeId: string | null
): string {
  const lines: string[] = []

  lines.push('# Fret Bundle Diagnostic Summary')
  lines.push('')
  lines.push(`**Generated:** ${new Date().toISOString()}`)
  lines.push(`**File:** ${bundle.meta.fileName ?? 'Unknown'}`)
  lines.push(`**File Size:** ${formatFileSize(bundle.meta.fileSize ?? 0)}`)
  lines.push('')

  // Warnings
  if (bundle.warnings.length > 0) {
    lines.push('## Parse Warnings')
    lines.push('')
    for (const warning of bundle.warnings) {
      lines.push(`- ${warning}`)
    }
    lines.push('')
  }

  // Windows overview
  lines.push('## Windows Overview')
  lines.push('')
  lines.push(`Total windows: ${bundle.windows.length}`)
  lines.push('')
  for (let i = 0; i < bundle.windows.length; i++) {
    const w = bundle.windows[i]
    lines.push(`- **${w.windowId}**: ${w.snapshots.length} snapshots`)
  }
  lines.push('')

  // Selected window details
  const window = bundle.windows[selectedWindow]
  if (window) {
    lines.push(`## Selected Window: ${window.windowId}`)
    lines.push('')

    const snapshotA = window.snapshots[selectedSnapshotA]
    if (snapshotA) {
      lines.push('### Snapshot A')
      lines.push('')
      lines.push(formatSnapshotSummary(snapshotA, window.events))
      lines.push('')
    }

    if (selectedSnapshotB !== null) {
      const snapshotB = window.snapshots[selectedSnapshotB]
      if (snapshotB && snapshotA) {
        lines.push('### Snapshot B')
        lines.push('')
        lines.push(formatSnapshotSummary(snapshotB, window.events))
        lines.push('')

        lines.push('### Diff Summary')
        lines.push('')
        const diff = diffSnapshots(snapshotA, snapshotB)
        lines.push(`- **Added nodes:** ${diff.added.length}`)
        lines.push(`- **Removed nodes:** ${diff.removed.length}`)
        lines.push(`- **Changed nodes:** ${diff.changed.length}`)
        lines.push('')
      }
    }

    // Selected node
    if (selectedNodeId && snapshotA?.semantics) {
      const node = snapshotA.semantics.nodesById[selectedNodeId]
      if (node) {
        lines.push('### Selected Node')
        lines.push('')
        lines.push(formatNodeSummary(node))
        lines.push('')
      }
    }
  }

  lines.push('---')
  lines.push('*Generated by Fret Bundle Viewer*')

  return lines.join('\n')
}

function formatSnapshotSummary(snapshot: SnapshotModel, windowEvents?: Array<{ kind: string; summary: string; tickId?: string; frameId?: string }>): string {
  const lines: string[] = []

  if (snapshot.tickId) lines.push(`- **Tick ID:** ${snapshot.tickId}`)
  if (snapshot.frameId) lines.push(`- **Frame ID:** ${snapshot.frameId}`)
  if (snapshot.timestampMonoNs) lines.push(`- **Timestamp:** ${snapshot.timestampMonoNs}`)
  if (snapshot.scaleFactor) lines.push(`- **Scale Factor:** ${snapshot.scaleFactor}`)
  if (snapshot.windowSizeLogical) {
    lines.push(`- **Window Size:** ${snapshot.windowSizeLogical.w} x ${snapshot.windowSizeLogical.h}`)
  }

  if (snapshot.semantics) {
    const nodeCount = Object.keys(snapshot.semantics.nodesById).length
    lines.push(`- **Semantics Nodes:** ${nodeCount}`)
  }

  if (snapshot.focus?.focusedNodeId) {
    lines.push(`- **Focused Node:** ${snapshot.focus.focusedNodeId}`)
  }

  if (snapshot.overlay?.barrierRootId) {
    lines.push(`- **Barrier Root:** ${snapshot.overlay.barrierRootId}`)
  }

  if (snapshot.overlay?.layerRoots && snapshot.overlay.layerRoots.length > 0) {
    const roots = snapshot.overlay.layerRoots
      .slice(0, 6)
      .map((r) => {
        const flags: string[] = []
        if (r.blocksUnderlay) flags.push('blocks_underlay')
        if (r.hitTestable === false) flags.push('no_hit_test')
        if (r.zIndex !== undefined) flags.push(`z=${r.zIndex}`)
        return `${r.nodeId ?? '—'}${flags.length > 0 ? ` (${flags.join(', ')})` : ''}`
      })
    lines.push(`- **Layer Roots:** ${roots.join('; ')}${snapshot.overlay.layerRoots.length > 6 ? ' …' : ''}`)
  }

  if (snapshot.perf) {
    if (snapshot.perf.totalUs) lines.push(`- **Total Time:** ${snapshot.perf.totalUs}us`)
    if (snapshot.perf.layoutUs) lines.push(`- **Layout Time:** ${snapshot.perf.layoutUs}us`)
    if (snapshot.perf.prepaintUs) lines.push(`- **Prepaint Time:** ${snapshot.perf.prepaintUs}us`)
    if (snapshot.perf.paintUs) lines.push(`- **Paint Time:** ${snapshot.perf.paintUs}us`)
    if (snapshot.perf.cache?.hits !== undefined || snapshot.perf.cache?.misses !== undefined) {
      lines.push(
        `- **Paint Cache:** hits=${snapshot.perf.cache?.hits ?? 0} misses=${snapshot.perf.cache?.misses ?? 0}`
      )
    }
    if (snapshot.perf.invalidations && typeof snapshot.perf.invalidations === 'object') {
      const inv = snapshot.perf.invalidations as any
      const count = typeof inv.count === 'number' ? inv.count : undefined
      const nodes = typeof inv.nodes === 'number' ? inv.nodes : undefined
      if (count !== undefined || nodes !== undefined) {
        lines.push(`- **Invalidation Walks:** calls=${count ?? '—'} nodes=${nodes ?? '—'}`)
      }
    }
  }

  // Deep debug summaries (best-effort from raw snapshot)
  const debug = asObject(asObject(snapshot.raw)?.debug)

  const inv = asArray(debug?.invalidation_walks)
  if (inv && inv.length > 0) {
    const rows: Array<{ walkedNodes: number; kind: string; source: string; detail?: string }> = []
    for (const r of inv) {
      const o = asObject(r)
      if (!o) continue
      rows.push({
        walkedNodes: typeof o.walked_nodes === 'number' ? o.walked_nodes : 0,
        kind: typeof o.kind === 'string' ? o.kind : 'unknown',
        source: typeof o.source === 'string' ? o.source : 'unknown',
        detail: typeof o.detail === 'string' ? o.detail : undefined,
      })
    }
    rows.sort((a, b) => b.walkedNodes - a.walkedNodes)
    const top = rows.slice(0, 8).map((r) => `${r.walkedNodes} ${r.kind}/${r.source}${r.detail ? ` (${r.detail})` : ''}`)
    lines.push(`- **Top Invalidation Walks:** ${top.join('; ')}${rows.length > 8 ? ' …' : ''}`)
  }

  const solves = asArray(debug?.layout_engine_solves)
  if (solves && solves.length > 0) {
    const s0 = asObject(solves[0])
    if (s0) {
      const solveUs = typeof s0.solve_time_us === 'number' ? s0.solve_time_us : undefined
      const measureUs = typeof s0.measure_time_us === 'number' ? s0.measure_time_us : undefined
      if (solveUs !== undefined || measureUs !== undefined) {
        lines.push(`- **Layout Solve:** solve_us=${solveUs ?? '—'} measure_us=${measureUs ?? '—'}`)
      }
      const topMeasures = asArray(s0.top_measures)
      if (topMeasures && topMeasures.length > 0) {
        const tm = topMeasures
          .slice(0, 6)
          .map((m) => {
            const mo = asObject(m)
            if (!mo) return null
            const us = typeof mo.measure_time_us === 'number' ? mo.measure_time_us : undefined
            const kind = typeof mo.element_kind === 'string' ? mo.element_kind : 'unknown'
            const calls = typeof mo.calls === 'number' ? mo.calls : undefined
            return `${us ?? '—'} ${kind}${calls !== undefined ? ` (calls=${calls})` : ''}`
          })
          .filter(Boolean)
        if (tm.length > 0) {
          lines.push(`- **Top Measures:** ${tm.join('; ')}${topMeasures.length > 6 ? ' …' : ''}`)
        }
      }
    }
  }

  const cacheRoots = asArray(debug?.cache_roots)
  if (cacheRoots && cacheRoots.length > 0) {
    const top = cacheRoots.slice(0, 6).map((r) => {
      const ro = asObject(r)
      if (!ro) return null
      const root = ro.root != null ? String(ro.root) : '—'
      const reused = typeof ro.reused === 'boolean' ? ro.reused : undefined
      const reason = typeof ro.reuse_reason === 'string' ? ro.reuse_reason : undefined
      const ops = typeof ro.paint_replayed_ops === 'number' ? ro.paint_replayed_ops : undefined
      const nodes = typeof ro.subtree_nodes === 'number' ? ro.subtree_nodes : undefined
      return `${root}${reused !== undefined ? (reused ? ' reused' : ' new') : ''}${reason ? ` (${reason})` : ''}${ops !== undefined ? ` ops=${ops}` : ''}${nodes !== undefined ? ` nodes=${nodes}` : ''}`
    }).filter(Boolean)
    if (top.length > 0) {
      lines.push(`- **Cache Roots:** ${top.join('; ')}${cacheRoots.length > 6 ? ' …' : ''}`)
    }
  }

  // Events (window-level), filtered up to selected tick if possible.
  if (windowEvents && windowEvents.length > 0) {
    const maxTick = snapshot.tickId ? Number(snapshot.tickId) : NaN
    const filtered = Number.isFinite(maxTick)
      ? windowEvents.filter((e) => (e.tickId ? Number(e.tickId) <= maxTick : true))
      : windowEvents
    const tail = filtered.slice(-8)
    if (tail.length > 0) {
      lines.push(`- **Recent Events:** ${tail.map((e) => `${e.kind}: ${e.summary}`).join(' | ')}`)
    }
  }

  return lines.join('\n')
}

function formatNodeSummary(node: SemanticsNodeModel): string {
  const lines: string[] = []

  lines.push(`- **ID:** ${node.id}`)
  if (node.role) lines.push(`- **Role:** ${node.role}`)
  if (node.testId) lines.push(`- **Test ID:** ${node.testId}`)
  if (node.label) lines.push(`- **Label:** ${node.label}`)
  if (node.name) lines.push(`- **Name:** ${node.name}`)
  if (node.bounds) {
    lines.push(`- **Bounds:** x=${node.bounds.x}, y=${node.bounds.y}, w=${node.bounds.w}, h=${node.bounds.h}`)
  }
  if (node.parentId) lines.push(`- **Parent:** ${node.parentId}`)
  if (node.children.length > 0) {
    lines.push(`- **Children:** ${node.children.join(', ')}`)
  }

  return lines.join('\n')
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function downloadMarkdown(content: string, fileName: string): void {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = fileName
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function downloadJson(content: unknown, fileName: string): void {
  const blob = new Blob([JSON.stringify(content, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = fileName
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function parseOutDirContext(outDir: string | undefined): {
  kind: 'script_step' | 'label' | 'unknown'
  timestampPrefix?: string
  stepIndex?: number
  action?: string
  label?: string
} {
  if (!outDir) return { kind: 'unknown' }

  // Examples:
  // - 1769177393463-script-step-0000-press_key
  // - 1769177364221-ui-gallery-alert-dialog-open
  const m = outDir.match(/^(\d+)-(.*)$/)
  const timestampPrefix = m?.[1]
  const tail = m?.[2] ?? outDir

  const sm = tail.match(/^script-step-(\d+)-(.+)$/)
  if (sm) {
    return {
      kind: 'script_step',
      timestampPrefix,
      stepIndex: Number(sm[1]),
      action: sm[2],
    }
  }

  return {
    kind: 'label',
    timestampPrefix,
    label: tail,
  }
}

export function exportTriageJson(
  bundle: BundleModel,
  selectedWindow: number,
  selectedSnapshotA: number,
  selectedSnapshotB: number | null,
  selectedNodeId: string | null
): void {
  const window = bundle.windows[selectedWindow]
  const snapshotA = window?.snapshots[selectedSnapshotA]
  const snapshotB = selectedSnapshotB !== null ? window?.snapshots[selectedSnapshotB] : null

  const triage: Array<{ level: 'info' | 'warn'; kind: string; message: string; evidence?: unknown }> = []

  if (snapshotA?.perf?.totalUs !== undefined) {
    const us = snapshotA.perf.totalUs
    if (us >= 1_000_000) {
      triage.push({ level: 'warn', kind: 'slow_frame', message: `Severe slow frame (${us}us)`, evidence: { total_us: us } })
    } else if (us >= 33_000) {
      triage.push({ level: 'warn', kind: 'slow_frame', message: `Slow frame (${us}us)`, evidence: { total_us: us } })
    } else {
      triage.push({ level: 'info', kind: 'frame_time', message: `Frame time (${us}us)`, evidence: { total_us: us } })
    }
  }

  if (snapshotA?.overlay?.barrierRootId) {
    triage.push({
      level: 'info',
      kind: 'barrier_root',
      message: `Barrier root active (${snapshotA.overlay.barrierRootId})`,
      evidence: { barrier_root: snapshotA.overlay.barrierRootId },
    })
  }

  const blockingRoots = snapshotA?.overlay?.layerRoots?.filter((r) => r.blocksUnderlay).map((r) => r.nodeId).filter(Boolean)
  if (blockingRoots && blockingRoots.length > 0) {
    triage.push({
      level: 'warn',
      kind: 'blocks_underlay',
      message: `Underlay input may be blocked (count=${blockingRoots.length})`,
      evidence: { blocking_roots: blockingRoots },
    })
  }

  const inv = snapshotA?.perf?.invalidations as any
  const invCalls = typeof inv?.count === 'number' ? inv.count : undefined
  const invNodes = typeof inv?.nodes === 'number' ? inv.nodes : undefined
  if (invCalls !== undefined || invNodes !== undefined) {
    const level: 'info' | 'warn' = (invCalls ?? 0) >= 1000 ? 'warn' : 'info'
    triage.push({
      level,
      kind: 'invalidation_walks',
      message: `Invalidation walks (calls=${invCalls ?? '—'}, nodes=${invNodes ?? '—'})`,
      evidence: { calls: invCalls, nodes: invNodes },
    })
  }

  if (snapshotA?.perf?.layoutUs !== undefined || snapshotA?.perf?.prepaintUs !== undefined || snapshotA?.perf?.paintUs !== undefined) {
    triage.push({
      level: 'info',
      kind: 'phase_breakdown',
      message: 'Phase breakdown (layout/prepaint/paint)',
      evidence: {
        layout_us: snapshotA?.perf?.layoutUs,
        prepaint_us: snapshotA?.perf?.prepaintUs,
        paint_us: snapshotA?.perf?.paintUs,
      },
    })
  }

  // Optional semantics evidence for selected node.
  if (selectedNodeId && snapshotA?.semantics?.nodesById[selectedNodeId]) {
    const n = snapshotA.semantics.nodesById[selectedNodeId]
    triage.push({
      level: 'info',
      kind: 'selected_node',
      message: `Selected node (${selectedNodeId})`,
      evidence: {
        id: n.id,
        role: n.role,
        test_id: n.testId,
        label: n.label,
        name: n.name,
        parent: n.parentId,
        children: n.children.slice(0, 20),
        bounds: n.bounds,
      },
    })
  }

  // Diff summary when comparing.
  let diff: DiffResult | null = null
  if (snapshotA && snapshotB) {
    diff = diffSnapshots(snapshotA, snapshotB)
    triage.push({
      level: 'info',
      kind: 'diff',
      message: getDiffSummary(diff),
      evidence: { added: diff.added.length, removed: diff.removed.length, changed: diff.changed.length },
    })
  }

  const outDirContext = parseOutDirContext(bundle.meta.outDir)

  const payload = {
    schema_version: 1,
    generated_at: new Date().toISOString(),
    bundle: {
      file_name: bundle.meta.fileName,
      file_size: bundle.meta.fileSize,
      schema_version: bundle.meta.schemaVersion,
      exported_unix_ms: bundle.meta.exportedUnixMs,
      out_dir: bundle.meta.outDir,
      out_dir_context: outDirContext,
    },
    selection: {
      window_id: window?.windowId,
      snapshot_a: {
        tick_id: snapshotA?.tickId,
        frame_id: snapshotA?.frameId,
      },
      snapshot_b: snapshotB
        ? {
            tick_id: snapshotB.tickId,
            frame_id: snapshotB.frameId,
          }
        : null,
      selected_node_id: selectedNodeId,
    },
    triage,
  }

  const baseName = bundle.meta.fileName ? bundle.meta.fileName.replace(/\\.json$/i, '') : 'bundle'
  downloadJson(payload, `${baseName}.triage.json`)
}
