import type { BundleModel, SnapshotModel, SemanticsNodeModel, DiffResult } from './types'
import { getDiffSummary, diffSnapshots } from './diff'

export function generateMarkdownSummary(
  bundle: BundleModel,
  selectedWindow: number,
  selectedSnapshotA: number,
  selectedSnapshotB: number | null,
  selectedNodeId: string | null
): string {
  const lines: string[] = []

  lines.push('# Fret Bundle Diagnostic Summary')
  lines.push('')
  lines.push(`**Generated:** ${new Date().toISOString()}`)
  lines.push(`**File:** ${bundle.meta.fileName ?? 'Unknown'}`)
  lines.push(`**File Size:** ${formatFileSize(bundle.meta.fileSize ?? 0)}`)
  lines.push('')

  // Warnings
  if (bundle.warnings.length > 0) {
    lines.push('## Parse Warnings')
    lines.push('')
    for (const warning of bundle.warnings) {
      lines.push(`- ${warning}`)
    }
    lines.push('')
  }

  // Windows overview
  lines.push('## Windows Overview')
  lines.push('')
  lines.push(`Total windows: ${bundle.windows.length}`)
  lines.push('')
  for (let i = 0; i < bundle.windows.length; i++) {
    const w = bundle.windows[i]
    lines.push(`- **${w.windowId}**: ${w.snapshots.length} snapshots`)
  }
  lines.push('')

  // Selected window details
  const window = bundle.windows[selectedWindow]
  if (window) {
    lines.push(`## Selected Window: ${window.windowId}`)
    lines.push('')

    const snapshotA = window.snapshots[selectedSnapshotA]
    if (snapshotA) {
      lines.push('### Snapshot A')
      lines.push('')
      lines.push(formatSnapshotSummary(snapshotA))
      lines.push('')
    }

    if (selectedSnapshotB !== null) {
      const snapshotB = window.snapshots[selectedSnapshotB]
      if (snapshotB && snapshotA) {
        lines.push('### Snapshot B')
        lines.push('')
        lines.push(formatSnapshotSummary(snapshotB))
        lines.push('')

        lines.push('### Diff Summary')
        lines.push('')
        const diff = diffSnapshots(snapshotA, snapshotB)
        lines.push(`- **Added nodes:** ${diff.added.length}`)
        lines.push(`- **Removed nodes:** ${diff.removed.length}`)
        lines.push(`- **Changed nodes:** ${diff.changed.length}`)
        lines.push('')
      }
    }

    // Selected node
    if (selectedNodeId && snapshotA?.semantics) {
      const node = snapshotA.semantics.nodesById[selectedNodeId]
      if (node) {
        lines.push('### Selected Node')
        lines.push('')
        lines.push(formatNodeSummary(node))
        lines.push('')
      }
    }
  }

  lines.push('---')
  lines.push('*Generated by Fret Bundle Viewer*')

  return lines.join('\n')
}

function formatSnapshotSummary(snapshot: SnapshotModel): string {
  const lines: string[] = []

  if (snapshot.tickId) lines.push(`- **Tick ID:** ${snapshot.tickId}`)
  if (snapshot.frameId) lines.push(`- **Frame ID:** ${snapshot.frameId}`)
  if (snapshot.timestampMonoNs) lines.push(`- **Timestamp:** ${snapshot.timestampMonoNs}`)
  if (snapshot.scaleFactor) lines.push(`- **Scale Factor:** ${snapshot.scaleFactor}`)
  if (snapshot.windowSizeLogical) {
    lines.push(`- **Window Size:** ${snapshot.windowSizeLogical.w} x ${snapshot.windowSizeLogical.h}`)
  }

  if (snapshot.semantics) {
    const nodeCount = Object.keys(snapshot.semantics.nodesById).length
    lines.push(`- **Semantics Nodes:** ${nodeCount}`)
  }

  if (snapshot.focus?.focusedNodeId) {
    lines.push(`- **Focused Node:** ${snapshot.focus.focusedNodeId}`)
  }

  if (snapshot.perf) {
    if (snapshot.perf.totalUs) lines.push(`- **Total Time:** ${snapshot.perf.totalUs}us`)
    if (snapshot.perf.layoutUs) lines.push(`- **Layout Time:** ${snapshot.perf.layoutUs}us`)
    if (snapshot.perf.paintUs) lines.push(`- **Paint Time:** ${snapshot.perf.paintUs}us`)
  }

  return lines.join('\n')
}

function formatNodeSummary(node: SemanticsNodeModel): string {
  const lines: string[] = []

  lines.push(`- **ID:** ${node.id}`)
  if (node.role) lines.push(`- **Role:** ${node.role}`)
  if (node.testId) lines.push(`- **Test ID:** ${node.testId}`)
  if (node.label) lines.push(`- **Label:** ${node.label}`)
  if (node.name) lines.push(`- **Name:** ${node.name}`)
  if (node.bounds) {
    lines.push(`- **Bounds:** x=${node.bounds.x}, y=${node.bounds.y}, w=${node.bounds.w}, h=${node.bounds.h}`)
  }
  if (node.parentId) lines.push(`- **Parent:** ${node.parentId}`)
  if (node.children.length > 0) {
    lines.push(`- **Children:** ${node.children.join(', ')}`)
  }

  return lines.join('\n')
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function downloadMarkdown(content: string, fileName: string): void {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = fileName
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
