// Sample bundle data for demo/testing

export const simpleSampleBundle = {
  windows: [
    {
      window_id: 'main-editor',
      snapshots: [
        {
          tick_id: '1',
          frame_id: 'f-001',
          timestamp_mono_ns: '1705234567890000000',
          scale_factor: 2.0,
          window_size_logical: { w: 1920, h: 1080 },
          semantics: {
            roots: ['root-1'],
            nodes: [
              {
                id: 'root-1',
                role: 'Window',
                name: 'Editor Window',
                test_id: 'editor-root',
                bounds: { x: 0, y: 0, w: 1920, h: 1080 },
                children: ['toolbar-1', 'viewport-1', 'panel-1'],
              },
              {
                id: 'toolbar-1',
                role: 'Toolbar',
                name: 'Main Toolbar',
                test_id: 'main-toolbar',
                bounds: { x: 0, y: 0, w: 1920, h: 48 },
                parent_id: 'root-1',
                children: ['btn-new', 'btn-open', 'btn-save'],
              },
              {
                id: 'btn-new',
                role: 'Button',
                label: 'New File',
                test_id: 'btn-new-file',
                bounds: { x: 8, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
                actions: { click: true },
              },
              {
                id: 'btn-open',
                role: 'Button',
                label: 'Open',
                test_id: 'btn-open-file',
                bounds: { x: 96, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
                actions: { click: true },
              },
              {
                id: 'btn-save',
                role: 'Button',
                label: 'Save',
                test_id: 'btn-save-file',
                bounds: { x: 184, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
                actions: { click: true },
                flags: { disabled: true },
              },
              {
                id: 'viewport-1',
                role: 'Viewport',
                name: 'Scene Viewport',
                test_id: 'scene-viewport',
                bounds: { x: 0, y: 48, w: 1400, h: 832 },
                parent_id: 'root-1',
                children: ['canvas-1'],
              },
              {
                id: 'canvas-1',
                role: 'Canvas',
                name: 'Render Canvas',
                bounds: { x: 0, y: 0, w: 1400, h: 832 },
                parent_id: 'viewport-1',
                children: [],
              },
              {
                id: 'panel-1',
                role: 'Panel',
                name: 'Properties Panel',
                test_id: 'properties-panel',
                bounds: { x: 1400, y: 48, w: 520, h: 832 },
                parent_id: 'root-1',
                children: ['input-name', 'input-scale'],
              },
              {
                id: 'input-name',
                role: 'TextField',
                label: 'Object Name',
                test_id: 'input-object-name',
                bounds: { x: 1408, y: 80, w: 504, h: 32 },
                parent_id: 'panel-1',
                children: [],
                actions: { focus: true, setValue: true },
              },
              {
                id: 'input-scale',
                role: 'TextField',
                label: 'Scale',
                test_id: 'input-scale',
                bounds: { x: 1408, y: 120, w: 504, h: 32 },
                parent_id: 'panel-1',
                children: [],
                actions: { focus: true, setValue: true },
              },
            ],
          },
          focus: {
            focused_node_id: 'input-name',
          },
          overlay: {
            barrier_root_id: null,
            layer_roots: [],
          },
          hit_test: {
            pointer: { x: 1500, y: 100 },
            chain: [
              { node_id: 'input-name', role: 'TextField', test_id: 'input-object-name', label: 'Object Name' },
              { node_id: 'panel-1', role: 'Panel', test_id: 'properties-panel' },
              { node_id: 'root-1', role: 'Window', test_id: 'editor-root' },
            ],
          },
          events: [
            { kind: 'click', summary: 'Click on btn-open at (136, 24)' },
            { kind: 'focus', summary: 'Focus moved to input-name' },
            { kind: 'key', summary: 'Key pressed: Tab' },
          ],
          perf: {
            total_us: 2450,
            layout_us: 890,
            prepaint_us: 320,
            paint_us: 1240,
            invalidations: { count: 3, sources: ['style', 'layout', 'paint'] },
            cache: { hits: 45, misses: 8 },
          },
        },
        {
          tick_id: '2',
          frame_id: 'f-002',
          timestamp_mono_ns: '1705234567906666666',
          scale_factor: 2.0,
          window_size_logical: { w: 1920, h: 1080 },
          semantics: {
            roots: ['root-1'],
            nodes: [
              {
                id: 'root-1',
                role: 'Window',
                name: 'Editor Window',
                test_id: 'editor-root',
                bounds: { x: 0, y: 0, w: 1920, h: 1080 },
                children: ['toolbar-1', 'viewport-1', 'panel-1'],
              },
              {
                id: 'toolbar-1',
                role: 'Toolbar',
                name: 'Main Toolbar',
                test_id: 'main-toolbar',
                bounds: { x: 0, y: 0, w: 1920, h: 48 },
                parent_id: 'root-1',
                children: ['btn-new', 'btn-open', 'btn-save'],
              },
              {
                id: 'btn-new',
                role: 'Button',
                label: 'New File',
                test_id: 'btn-new-file',
                bounds: { x: 8, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
                actions: { click: true },
              },
              {
                id: 'btn-open',
                role: 'Button',
                label: 'Open',
                test_id: 'btn-open-file',
                bounds: { x: 96, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
                actions: { click: true },
              },
              {
                id: 'btn-save',
                role: 'Button',
                label: 'Save',
                test_id: 'btn-save-file',
                bounds: { x: 184, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
                actions: { click: true },
                flags: { disabled: false },
              },
              {
                id: 'viewport-1',
                role: 'Viewport',
                name: 'Scene Viewport',
                test_id: 'scene-viewport',
                bounds: { x: 0, y: 48, w: 1400, h: 832 },
                parent_id: 'root-1',
                children: ['canvas-1'],
              },
              {
                id: 'canvas-1',
                role: 'Canvas',
                name: 'Render Canvas',
                bounds: { x: 0, y: 0, w: 1400, h: 832 },
                parent_id: 'viewport-1',
                children: [],
              },
              {
                id: 'panel-1',
                role: 'Panel',
                name: 'Properties Panel',
                test_id: 'properties-panel',
                bounds: { x: 1400, y: 48, w: 520, h: 832 },
                parent_id: 'root-1',
                children: ['input-name', 'input-scale'],
              },
              {
                id: 'input-name',
                role: 'TextField',
                label: 'Object Name',
                test_id: 'input-object-name',
                bounds: { x: 1408, y: 80, w: 504, h: 32 },
                parent_id: 'panel-1',
                children: [],
                actions: { focus: true, setValue: true },
              },
              {
                id: 'input-scale',
                role: 'TextField',
                label: 'Scale',
                test_id: 'input-scale',
                bounds: { x: 1408, y: 120, w: 504, h: 32 },
                parent_id: 'panel-1',
                children: [],
                actions: { focus: true, setValue: true },
              },
            ],
          },
          focus: {
            focused_node_id: 'input-scale',
          },
          events: [
            { kind: 'key', summary: 'Key pressed: Tab' },
            { kind: 'focus', summary: 'Focus moved to input-scale' },
          ],
          perf: {
            total_us: 1850,
            layout_us: 650,
            prepaint_us: 280,
            paint_us: 920,
            invalidations: { count: 2, sources: ['focus', 'style'] },
            cache: { hits: 52, misses: 3 },
          },
        },
        {
          tick_id: '3',
          frame_id: 'f-003',
          timestamp_mono_ns: '1705234567923333333',
          scale_factor: 2.0,
          window_size_logical: { w: 1920, h: 1080 },
          semantics: {
            roots: ['root-1'],
            nodes: [
              {
                id: 'root-1',
                role: 'Window',
                name: 'Editor Window',
                test_id: 'editor-root',
                bounds: { x: 0, y: 0, w: 1920, h: 1080 },
                children: ['toolbar-1', 'viewport-1', 'panel-1', 'dialog-1'],
              },
              {
                id: 'toolbar-1',
                role: 'Toolbar',
                name: 'Main Toolbar',
                test_id: 'main-toolbar',
                bounds: { x: 0, y: 0, w: 1920, h: 48 },
                parent_id: 'root-1',
                children: ['btn-new', 'btn-open', 'btn-save'],
              },
              {
                id: 'btn-new',
                role: 'Button',
                label: 'New File',
                test_id: 'btn-new-file',
                bounds: { x: 8, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
              },
              {
                id: 'btn-open',
                role: 'Button',
                label: 'Open',
                test_id: 'btn-open-file',
                bounds: { x: 96, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
              },
              {
                id: 'btn-save',
                role: 'Button',
                label: 'Save',
                test_id: 'btn-save-file',
                bounds: { x: 184, y: 8, w: 80, h: 32 },
                parent_id: 'toolbar-1',
                children: [],
              },
              {
                id: 'viewport-1',
                role: 'Viewport',
                name: 'Scene Viewport',
                test_id: 'scene-viewport',
                bounds: { x: 0, y: 48, w: 1400, h: 832 },
                parent_id: 'root-1',
                children: ['canvas-1'],
              },
              {
                id: 'canvas-1',
                role: 'Canvas',
                name: 'Render Canvas',
                bounds: { x: 0, y: 0, w: 1400, h: 832 },
                parent_id: 'viewport-1',
                children: [],
              },
              {
                id: 'panel-1',
                role: 'Panel',
                name: 'Properties Panel',
                test_id: 'properties-panel',
                bounds: { x: 1400, y: 48, w: 520, h: 832 },
                parent_id: 'root-1',
                children: ['input-name', 'input-scale'],
              },
              {
                id: 'input-name',
                role: 'TextField',
                label: 'Object Name',
                test_id: 'input-object-name',
                bounds: { x: 1408, y: 80, w: 504, h: 32 },
                parent_id: 'panel-1',
                children: [],
              },
              {
                id: 'input-scale',
                role: 'TextField',
                label: 'Scale',
                test_id: 'input-scale',
                bounds: { x: 1408, y: 120, w: 504, h: 32 },
                parent_id: 'panel-1',
                children: [],
              },
              {
                id: 'dialog-1',
                role: 'Dialog',
                name: 'Confirm Save',
                test_id: 'save-dialog',
                bounds: { x: 660, y: 390, w: 600, h: 300 },
                parent_id: 'root-1',
                children: ['dialog-title', 'dialog-content', 'dialog-actions'],
              },
              {
                id: 'dialog-title',
                role: 'Heading',
                label: 'Save Changes?',
                bounds: { x: 680, y: 410, w: 560, h: 32 },
                parent_id: 'dialog-1',
                children: [],
              },
              {
                id: 'dialog-content',
                role: 'Text',
                label: 'Do you want to save changes before closing?',
                bounds: { x: 680, y: 450, w: 560, h: 48 },
                parent_id: 'dialog-1',
                children: [],
              },
              {
                id: 'dialog-actions',
                role: 'Generic',
                bounds: { x: 680, y: 620, w: 560, h: 48 },
                parent_id: 'dialog-1',
                children: ['btn-cancel', 'btn-dont-save', 'btn-save-dialog'],
              },
              {
                id: 'btn-cancel',
                role: 'Button',
                label: 'Cancel',
                test_id: 'dialog-btn-cancel',
                bounds: { x: 840, y: 620, w: 100, h: 40 },
                parent_id: 'dialog-actions',
                children: [],
                actions: { click: true },
              },
              {
                id: 'btn-dont-save',
                role: 'Button',
                label: "Don't Save",
                test_id: 'dialog-btn-dont-save',
                bounds: { x: 950, y: 620, w: 120, h: 40 },
                parent_id: 'dialog-actions',
                children: [],
                actions: { click: true },
              },
              {
                id: 'btn-save-dialog',
                role: 'Button',
                label: 'Save',
                test_id: 'dialog-btn-save',
                bounds: { x: 1080, y: 620, w: 100, h: 40 },
                parent_id: 'dialog-actions',
                children: [],
                actions: { click: true },
                flags: { default: true },
              },
            ],
          },
          focus: {
            focused_node_id: 'btn-save-dialog',
          },
          overlay: {
            barrier_root_id: 'dialog-1',
            layer_roots: [{ node_id: 'dialog-1', z_index: 100, hit_testable: true, blocks_underlay: true }],
          },
          hit_test: {
            pointer: { x: 1130, y: 640 },
            chain: [
              { node_id: 'btn-save-dialog', role: 'Button', test_id: 'dialog-btn-save', label: 'Save' },
              { node_id: 'dialog-actions', role: 'Generic' },
              { node_id: 'dialog-1', role: 'Dialog', test_id: 'save-dialog' },
            ],
          },
          events: [
            { kind: 'click', summary: 'Click on btn-save at (224, 24)' },
            { kind: 'dialog_open', summary: 'Dialog save-dialog opened' },
            { kind: 'focus', summary: 'Focus moved to btn-save-dialog' },
          ],
          perf: {
            total_us: 4200,
            layout_us: 1800,
            prepaint_us: 600,
            paint_us: 1800,
            invalidations: { count: 8, sources: ['tree', 'layout', 'paint', 'overlay'] },
            cache: { hits: 38, misses: 15 },
          },
        },
      ],
    },
  ],
}

export const multiWindowSampleBundle = {
  windows: [
    {
      window_id: 'main-window',
      snapshots: [
        {
          tick_id: '100',
          frame_id: 'mw-001',
          timestamp_mono_ns: '1705234500000000000',
          scale_factor: 1.0,
          window_size_logical: { w: 1280, h: 720 },
          semantics: {
            roots: ['mw-root'],
            nodes: [
              {
                id: 'mw-root',
                role: 'Window',
                name: 'Main Application',
                test_id: 'main-app',
                bounds: { x: 0, y: 0, w: 1280, h: 720 },
                children: ['mw-header', 'mw-content'],
              },
              {
                id: 'mw-header',
                role: 'Header',
                name: 'Application Header',
                test_id: 'app-header',
                bounds: { x: 0, y: 0, w: 1280, h: 60 },
                parent_id: 'mw-root',
                children: ['mw-title', 'mw-menu'],
              },
              {
                id: 'mw-title',
                role: 'Heading',
                label: 'Fret Studio',
                bounds: { x: 16, y: 16, w: 200, h: 28 },
                parent_id: 'mw-header',
                children: [],
              },
              {
                id: 'mw-menu',
                role: 'MenuBar',
                name: 'Main Menu',
                test_id: 'main-menu',
                bounds: { x: 240, y: 16, w: 400, h: 28 },
                parent_id: 'mw-header',
                children: ['menu-file', 'menu-edit', 'menu-view'],
              },
              {
                id: 'menu-file',
                role: 'MenuItem',
                label: 'File',
                test_id: 'menu-file',
                bounds: { x: 240, y: 16, w: 60, h: 28 },
                parent_id: 'mw-menu',
                children: [],
                actions: { click: true },
              },
              {
                id: 'menu-edit',
                role: 'MenuItem',
                label: 'Edit',
                test_id: 'menu-edit',
                bounds: { x: 310, y: 16, w: 60, h: 28 },
                parent_id: 'mw-menu',
                children: [],
                actions: { click: true },
              },
              {
                id: 'menu-view',
                role: 'MenuItem',
                label: 'View',
                test_id: 'menu-view',
                bounds: { x: 380, y: 16, w: 60, h: 28 },
                parent_id: 'mw-menu',
                children: [],
                actions: { click: true },
              },
              {
                id: 'mw-content',
                role: 'Generic',
                name: 'Content Area',
                bounds: { x: 0, y: 60, w: 1280, h: 660 },
                parent_id: 'mw-root',
                children: ['mw-sidebar', 'mw-main'],
              },
              {
                id: 'mw-sidebar',
                role: 'Navigation',
                name: 'Sidebar',
                test_id: 'sidebar',
                bounds: { x: 0, y: 60, w: 240, h: 660 },
                parent_id: 'mw-content',
                children: ['nav-home', 'nav-projects', 'nav-settings'],
              },
              {
                id: 'nav-home',
                role: 'Link',
                label: 'Home',
                test_id: 'nav-home',
                bounds: { x: 8, y: 68, w: 224, h: 40 },
                parent_id: 'mw-sidebar',
                children: [],
                actions: { click: true },
              },
              {
                id: 'nav-projects',
                role: 'Link',
                label: 'Projects',
                test_id: 'nav-projects',
                bounds: { x: 8, y: 116, w: 224, h: 40 },
                parent_id: 'mw-sidebar',
                children: [],
                actions: { click: true },
                flags: { selected: true },
              },
              {
                id: 'nav-settings',
                role: 'Link',
                label: 'Settings',
                test_id: 'nav-settings',
                bounds: { x: 8, y: 164, w: 224, h: 40 },
                parent_id: 'mw-sidebar',
                children: [],
                actions: { click: true },
              },
              {
                id: 'mw-main',
                role: 'Main',
                name: 'Main Content',
                bounds: { x: 240, y: 60, w: 1040, h: 660 },
                parent_id: 'mw-content',
                children: ['project-list'],
              },
              {
                id: 'project-list',
                role: 'List',
                name: 'Project List',
                test_id: 'project-list',
                bounds: { x: 256, y: 76, w: 1008, h: 628 },
                parent_id: 'mw-main',
                children: ['project-1', 'project-2'],
              },
              {
                id: 'project-1',
                role: 'ListItem',
                label: 'Demo Project',
                test_id: 'project-demo',
                bounds: { x: 256, y: 76, w: 1008, h: 80 },
                parent_id: 'project-list',
                children: [],
                actions: { click: true, doubleClick: true },
              },
              {
                id: 'project-2',
                role: 'ListItem',
                label: 'Tutorial Scene',
                test_id: 'project-tutorial',
                bounds: { x: 256, y: 164, w: 1008, h: 80 },
                parent_id: 'project-list',
                children: [],
                actions: { click: true, doubleClick: true },
              },
            ],
          },
          focus: {
            focused_node_id: 'nav-projects',
          },
          events: [
            { kind: 'startup', summary: 'Application started' },
            { kind: 'click', summary: 'Click on nav-projects' },
          ],
          perf: {
            total_us: 3100,
            layout_us: 1200,
            paint_us: 1900,
            cache: { hits: 28, misses: 12 },
          },
        },
        {
          tick_id: '101',
          frame_id: 'mw-002',
          timestamp_mono_ns: '1705234500016666666',
          scale_factor: 1.0,
          window_size_logical: { w: 1280, h: 720 },
          semantics: {
            roots: ['mw-root'],
            nodes: [
              {
                id: 'mw-root',
                role: 'Window',
                name: 'Main Application',
                test_id: 'main-app',
                bounds: { x: 0, y: 0, w: 1280, h: 720 },
                children: ['mw-header', 'mw-content'],
              },
              {
                id: 'mw-header',
                role: 'Header',
                name: 'Application Header',
                test_id: 'app-header',
                bounds: { x: 0, y: 0, w: 1280, h: 60 },
                parent_id: 'mw-root',
                children: ['mw-title', 'mw-menu'],
              },
              {
                id: 'mw-title',
                role: 'Heading',
                label: 'Fret Studio',
                bounds: { x: 16, y: 16, w: 200, h: 28 },
                parent_id: 'mw-header',
                children: [],
              },
              {
                id: 'mw-menu',
                role: 'MenuBar',
                name: 'Main Menu',
                test_id: 'main-menu',
                bounds: { x: 240, y: 16, w: 400, h: 28 },
                parent_id: 'mw-header',
                children: ['menu-file', 'menu-edit', 'menu-view'],
              },
              {
                id: 'menu-file',
                role: 'MenuItem',
                label: 'File',
                test_id: 'menu-file',
                bounds: { x: 240, y: 16, w: 60, h: 28 },
                parent_id: 'mw-menu',
                children: [],
              },
              {
                id: 'menu-edit',
                role: 'MenuItem',
                label: 'Edit',
                test_id: 'menu-edit',
                bounds: { x: 310, y: 16, w: 60, h: 28 },
                parent_id: 'mw-menu',
                children: [],
              },
              {
                id: 'menu-view',
                role: 'MenuItem',
                label: 'View',
                test_id: 'menu-view',
                bounds: { x: 380, y: 16, w: 60, h: 28 },
                parent_id: 'mw-menu',
                children: [],
              },
              {
                id: 'mw-content',
                role: 'Generic',
                name: 'Content Area',
                bounds: { x: 0, y: 60, w: 1280, h: 660 },
                parent_id: 'mw-root',
                children: ['mw-sidebar', 'mw-main'],
              },
              {
                id: 'mw-sidebar',
                role: 'Navigation',
                name: 'Sidebar',
                test_id: 'sidebar',
                bounds: { x: 0, y: 60, w: 240, h: 660 },
                parent_id: 'mw-content',
                children: ['nav-home', 'nav-projects', 'nav-settings'],
              },
              {
                id: 'nav-home',
                role: 'Link',
                label: 'Home',
                test_id: 'nav-home',
                bounds: { x: 8, y: 68, w: 224, h: 40 },
                parent_id: 'mw-sidebar',
                children: [],
              },
              {
                id: 'nav-projects',
                role: 'Link',
                label: 'Projects',
                test_id: 'nav-projects',
                bounds: { x: 8, y: 116, w: 224, h: 40 },
                parent_id: 'mw-sidebar',
                children: [],
                flags: { selected: true },
              },
              {
                id: 'nav-settings',
                role: 'Link',
                label: 'Settings',
                test_id: 'nav-settings',
                bounds: { x: 8, y: 164, w: 224, h: 40 },
                parent_id: 'mw-sidebar',
                children: [],
              },
              {
                id: 'mw-main',
                role: 'Main',
                name: 'Main Content',
                bounds: { x: 240, y: 60, w: 1040, h: 660 },
                parent_id: 'mw-content',
                children: ['project-list'],
              },
              {
                id: 'project-list',
                role: 'List',
                name: 'Project List',
                test_id: 'project-list',
                bounds: { x: 256, y: 76, w: 1008, h: 628 },
                parent_id: 'mw-main',
                children: ['project-1', 'project-2'],
              },
              {
                id: 'project-1',
                role: 'ListItem',
                label: 'Demo Project',
                test_id: 'project-demo',
                bounds: { x: 256, y: 76, w: 1008, h: 80 },
                parent_id: 'project-list',
                children: [],
                flags: { selected: true },
              },
              {
                id: 'project-2',
                role: 'ListItem',
                label: 'Tutorial Scene',
                test_id: 'project-tutorial',
                bounds: { x: 256, y: 164, w: 1008, h: 80 },
                parent_id: 'project-list',
                children: [],
              },
            ],
          },
          focus: {
            focused_node_id: 'project-1',
          },
          events: [{ kind: 'click', summary: 'Click on project-1' }],
          perf: {
            total_us: 1800,
            layout_us: 600,
            paint_us: 1200,
            cache: { hits: 35, misses: 5 },
          },
        },
      ],
    },
    {
      window_id: 'inspector-window',
      snapshots: [
        {
          tick_id: '100',
          frame_id: 'iw-001',
          timestamp_mono_ns: '1705234500000000000',
          scale_factor: 1.0,
          window_size_logical: { w: 400, h: 600 },
          semantics: {
            roots: ['iw-root'],
            nodes: [
              {
                id: 'iw-root',
                role: 'Window',
                name: 'Inspector',
                test_id: 'inspector-window',
                bounds: { x: 0, y: 0, w: 400, h: 600 },
                children: ['iw-header', 'iw-content'],
              },
              {
                id: 'iw-header',
                role: 'Header',
                label: 'Inspector',
                bounds: { x: 0, y: 0, w: 400, h: 40 },
                parent_id: 'iw-root',
                children: [],
              },
              {
                id: 'iw-content',
                role: 'Generic',
                name: 'Inspector Content',
                bounds: { x: 0, y: 40, w: 400, h: 560 },
                parent_id: 'iw-root',
                children: ['iw-empty'],
              },
              {
                id: 'iw-empty',
                role: 'Text',
                label: 'No selection',
                bounds: { x: 100, y: 280, w: 200, h: 24 },
                parent_id: 'iw-content',
                children: [],
              },
            ],
          },
          focus: { focused_node_id: null },
          events: [],
          perf: { total_us: 500, layout_us: 200, paint_us: 300 },
        },
        {
          tick_id: '101',
          frame_id: 'iw-002',
          timestamp_mono_ns: '1705234500016666666',
          scale_factor: 1.0,
          window_size_logical: { w: 400, h: 600 },
          semantics: {
            roots: ['iw-root'],
            nodes: [
              {
                id: 'iw-root',
                role: 'Window',
                name: 'Inspector',
                test_id: 'inspector-window',
                bounds: { x: 0, y: 0, w: 400, h: 600 },
                children: ['iw-header', 'iw-content'],
              },
              {
                id: 'iw-header',
                role: 'Header',
                label: 'Inspector - Demo Project',
                bounds: { x: 0, y: 0, w: 400, h: 40 },
                parent_id: 'iw-root',
                children: [],
              },
              {
                id: 'iw-content',
                role: 'Generic',
                name: 'Inspector Content',
                bounds: { x: 0, y: 40, w: 400, h: 560 },
                parent_id: 'iw-root',
                children: ['iw-section-transform', 'iw-section-material'],
              },
              {
                id: 'iw-section-transform',
                role: 'Group',
                name: 'Transform',
                test_id: 'section-transform',
                bounds: { x: 8, y: 48, w: 384, h: 180 },
                parent_id: 'iw-content',
                children: ['field-pos-x', 'field-pos-y', 'field-pos-z'],
              },
              {
                id: 'field-pos-x',
                role: 'TextField',
                label: 'Position X',
                test_id: 'field-pos-x',
                bounds: { x: 16, y: 80, w: 360, h: 32 },
                parent_id: 'iw-section-transform',
                children: [],
                actions: { focus: true, setValue: true },
              },
              {
                id: 'field-pos-y',
                role: 'TextField',
                label: 'Position Y',
                test_id: 'field-pos-y',
                bounds: { x: 16, y: 120, w: 360, h: 32 },
                parent_id: 'iw-section-transform',
                children: [],
                actions: { focus: true, setValue: true },
              },
              {
                id: 'field-pos-z',
                role: 'TextField',
                label: 'Position Z',
                test_id: 'field-pos-z',
                bounds: { x: 16, y: 160, w: 360, h: 32 },
                parent_id: 'iw-section-transform',
                children: [],
                actions: { focus: true, setValue: true },
              },
              {
                id: 'iw-section-material',
                role: 'Group',
                name: 'Material',
                test_id: 'section-material',
                bounds: { x: 8, y: 236, w: 384, h: 120 },
                parent_id: 'iw-content',
                children: ['field-color'],
              },
              {
                id: 'field-color',
                role: 'ColorPicker',
                label: 'Base Color',
                test_id: 'field-base-color',
                bounds: { x: 16, y: 268, w: 360, h: 40 },
                parent_id: 'iw-section-material',
                children: [],
                actions: { click: true },
              },
            ],
          },
          focus: { focused_node_id: 'field-pos-x' },
          events: [
            { kind: 'selection_changed', summary: 'Selection changed to Demo Project' },
            { kind: 'focus', summary: 'Focus moved to field-pos-x' },
          ],
          perf: {
            total_us: 2200,
            layout_us: 900,
            paint_us: 1300,
            invalidations: { count: 4, sources: ['content', 'layout'] },
            cache: { hits: 12, misses: 8 },
          },
        },
      ],
    },
  ],
}
